PISM, A Parallel Ice Sheet Model: main
btutest_context
help
main
main()
int main (int argc, char * argv[])
Definition at line 77 of file btutest.cc.
References pism::io::append_time(), btutest_context(), pism::units::convert(), pism::IceModelVec2S::copy_from(), pism::io::define_time(), exactK(), TestKParameters::F, pism::energy::BTUGrid::FromOptions(), pism::handle_fatal_errors(), help, pism::GridParameters::Lx, pism::GridParameters::Ly, pism::energy::BTUGrid::Mbz, pism::GridParameters::Mx, pism::GridParameters::My, n, pism::PointsWithGhosts::next(), pism::IceModelVec::norm(), pism::GridParameters::ownership_ranges_from_options(), pism::PISM_READWRITE_MOVE, pism::process_input_options(), pism::IceModelVec::set_attrs(), pism::IceModelVec::shift(), pism::show_usage_check_req_opts(), pism::string_to_backend(), TestKParameters::T, pism::MaxTimestep::value(), pism::options::Option< T >::value(), pism::GridParameters::vertical_grid_from_options(), pism::WITHOUT_GHOSTS, and pism::IceModelVec::write().