PISM, A Parallel Ice Sheet Model: ccs_err_str
calcalcs_cal
CALCALCS_ERR_DATE_NOT_IN_CALENDAR
CALCALCS_ERR_INVALID_CALENDAR
CALCALCS_ERR_INVALID_DAY_OF_YEAR
CALCALCS_ERR_NO_YEAR_ZERO
CALCALCS_ERR_NOT_A_MIXED_CALENDAR
CALCALCS_ERR_NULL_CALENDAR
CALCALCS_ERR_OUT_OF_RANGE
CALCALCS_ERR_UNKNOWN_COUNTRY_CODE
CALCALCS_VERSION_NUMBER
ccs_country_code
ccs_date2doy
ccs_date2jday
ccs_dayssince
ccs_doy2date
ccs_dpm
ccs_err_str
ccs_free_calendar
ccs_get_xition_date
ccs_init_calendar
ccs_isleap
ccs_jday2date
ccs_set_xition_date
ccs_err_str()
char* ccs_err_str (int error_code)
Definition at line 907 of file calcalcs.c.
References CALCALCS_ERR_INVALID_CALENDAR, CALCALCS_ERR_NULL_CALENDAR, CALCALCS_VERSION_NUMBER, and error_message.
Referenced by pism::increment_date(), set_xition_extra_info(), utCalendar2_cal(), and utInvCalendar2_cal().