PISM, A Parallel Ice Sheet Model: pism::Logger::message
ConstPtr
disable
enable
error
error_impl
get_threshold
Logger
Logger
m_impl
message
message
message_impl
operator=
Ptr
set_threshold
~Logger
message() [1/2]
void pism::Logger::message (int threshold, const char format[], ...) const
Print a message to the log.
Does nothing if threshold is greater than the value provided to the constructor or set using set_threshold().
Definition at line 50 of file Logger.cc.
References pism::Logger::Impl::enabled, m_impl, message_impl(), and pism::Logger::Impl::threshold.
Referenced by pism::stressbalance::BedSmoother::BedSmoother(), pism::calendar(), pism::ForcingOptions::ForcingOptions(), pism::IceGrid::FromFile(), pism::options::ignored(), pism::DefaultConfig::init(), pism::Time::init_from_file(), pism::print_config(), pism::print_diagnostics(), pism::print_diagnostics_json(), pism::IceBasalResistancePlasticLaw::print_info(), pism::IceBasalResistancePseudoPlasticLaw::print_info(), pism::IceBasalResistanceRegularizedLaw::print_info(), pism::print_unused_parameters(), pism::io::read_spatial_variable(), pism::io::read_time_bounds(), pism::io::read_timeseries(), pism::reference_date(), pism::io::regrid_spatial_variable(), pism::grid_info::report(), pism::IceGrid::report_parameters(), pism::VariableMetadata::report_range(), pism::report_range(), pism::VariableMetadata::report_to_stdout(), pism::show_usage(), pism::show_usage_check_req_opts(), pism::Time::Time(), pism::energy::TemperatureModel::update_impl(), and pism::warn_about_missing().