PISM, A Parallel Ice Sheet Model: pism::fem::DirichletData::constrain
constrain
DirichletData
finish
init
m_indices
m_indices_e
m_weight
operator bool
~DirichletData
constrain()
void pism::fem::DirichletData::constrain (Element2 & element)
Constrain element, i.e. ensure that quadratures do not contribute to Dirichlet nodes by marking corresponding rows and columns as "invalid".
Definition at line 79 of file DirichletData.cc.
References pism::IceModelVec2S::array(), pism::k, m_indices, m_indices_e, pism::fem::Element2::mark_col_invalid(), pism::fem::Element2::mark_row_invalid(), pism::fem::Element::n_chi(), pism::fem::linear::n_chi, and pism::fem::Element2::nodal_values().
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_H1NormFunctional2S::assemble_form(), pism::inverse::IPGroundedIceH1NormFunctional2S::assemble_form(), pism::stressbalance::SSAFEM::compute_local_function(), pism::stressbalance::SSAFEM::compute_local_jacobian(), pism::inverse::IP_H1NormFunctional2S::gradientAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::gradientAt(), and pism::inverse::IPTotalVariationFunctional2S::gradientAt().