PISM, A Parallel Ice Sheet Model: pism::array::Staggered1::star
Staggered1
star
star()
stencils::Star< double > pism::array::Staggered1::star (int i, int j) const inline
Returns the values at interfaces of the cell i,j using the staggered grid.
The ij member of the return value is set to 0, since it has no meaning in this context.
Definition at line 73 of file Staggered.hh.
References pism::stencils::Star< T >::c, pism::stencils::Star< T >::e, pism::stencils::Star< T >::n, pism::stencils::Star< T >::s, and pism::stencils::Star< T >::w.
Referenced by pism::GeometryEvolution::compute_flux_divergence(), pism::grounding_line_flux(), pism::fct::limit(), pism::make_nonnegative_preserving(), pism::array::staggered_to_regular(), pism::step(), pism::total_grounding_line_flux(), pism::hydrology::EmptyingProblem::update(), pism::hydrology::Distributed::update_P(), and pism::hydrology::Routing::W_change_due_to_flow().