PISM, A Parallel Ice Sheet Model: pism::ocean::GivenTH::subshelf_salinity
GivenTH
init_impl
m_salinity_ocean
m_theta_ocean
max_timestep_impl
pointwise_update
subshelf_salinity
subshelf_salinity_diffusion_only
subshelf_salinity_freeze_on
subshelf_salinity_melt
update_impl
~GivenTH
subshelf_salinity()
void pism::ocean::GivenTH::subshelf_salinity (const Constants & c, double sea_water_salinity, double sea_water_potential_temperature, double thickness, double * shelf_base_salinity) private
Compute the basal salinity and make sure that it is consistent with the basal melt rate.
Parameters
[in] c constants
[in] sea_water_salinity sea water salinity
[in] sea_water_potential_temperature sea water potential temperature
[in] thickness ice shelf thickness
[out] shelf_base_salinity resulting shelf base salinity
Returns
0 on success
Definition at line 294 of file GivenTH.cc.
References pism::ocean::shelf_base_melt_rate(), subshelf_salinity_diffusion_only(), subshelf_salinity_freeze_on(), and subshelf_salinity_melt().
Referenced by pointwise_update().