PISM, A Parallel Ice Sheet Model: pism::stressbalance::Inputs::dump
age
basal_melt_rate
basal_yield_stress
bc_mask
bc_values
dump
enthalpy
fracture_density
geometry
Inputs
new_bed_elevation
no_model_ice_thickness
no_model_mask
no_model_surface_elevation
water_column_pressure
dump()
void pism::stressbalance::Inputs::dump (const char * filename) const
Save stress balance inputs to a file (for debugging).
Definition at line 62 of file StressBalance.cc.
References age, pism::io::append_time(), basal_melt_rate, basal_yield_stress, bc_mask, bc_values, pism::Geometry::bed_elevation, pism::Geometry::cell_grounded_fraction, pism::Geometry::cell_type, pism::io::define_time(), enthalpy, fracture_density, geometry, pism::IceModelVec::grid(), pism::Geometry::ice_area_specific_volume, pism::Geometry::ice_surface_elevation, pism::Geometry::ice_thickness, pism::Geometry::latitude, pism::Geometry::longitude, no_model_ice_thickness, no_model_mask, no_model_surface_elevation, pism::PISM_READWRITE_MOVE, pism::Geometry::sea_level_elevation, pism::string_to_backend(), water_column_pressure, and pism::IceModelVec::write().