PISM, A Parallel Ice Sheet Model: pism::Geometry::ensure_consistency
bed_elevation
cell_grounded_fraction
cell_type
dump
ensure_consistency
Geometry
ice_area_specific_volume
ice_surface_elevation
ice_thickness
latitude
longitude
m_stencil_width
sea_level_elevation
ensure_consistency()
void pism::Geometry::ensure_consistency (double ice_free_thickness_threshold)
Ensures consistency of ice geometry by re-computing cell type, cell grounded fraction, and ice surface elevation.
Definition at line 122 of file Geometry.cc.
References pism::RuntimeError::add_context(), bed_elevation, cell_grounded_fraction, cell_type, pism::ParallelSection::check(), pism::check_minimum_ice_thickness(), pism::GeometryCalculator::compute(), pism::compute_grounded_cell_fraction(), dump(), pism::ParallelSection::failed(), pism::filename_add_suffix(), pism::IceModelVec::grid(), ice_area_specific_volume, ice_surface_elevation, ice_thickness, pism::PointsWithGhosts::next(), sea_level_elevation, pism::GeometryCalculator::set_icefree_thickness(), and pism::IceModelVec::update_ghosts().
Referenced by pism::IceModel::enforce_consistency_of_geometry(), pism::IceModel::front_retreat_step(), Geometry(), pism::inverse::IP_SSAHardavForwardProblem::init(), pism::inverse::IP_SSATaucForwardProblem::init(), pism::stressbalance::SSATestCaseCFBC::initializeSSACoefficients(), pism::stressbalance::SSATestCaseI::initializeSSACoefficients(), main(), and pism::stressbalance::SSATestCase::run().