PISM, A Parallel Ice Sheet Model: pism::IceModel::process_signals
allocate_age_model
allocate_basal_yield_stress
allocate_bed_deformation
allocate_bedrock_thermal_unit
allocate_couplers
allocate_energy_model
allocate_geometry_evolution
allocate_iceberg_remover
allocate_storage
allocate_stressbalance
allocate_subglacial_hydrology
allocate_submodels
basal_yield_stress_model
bed_deformation_model
bedrock_thermal_model
bedrock_thermal_model_step
bootstrap_2d
calving
combine_basal_melt_rate
compute_geometry_change
compute_lat_lon
compute_original_ice_fraction
compute_temperate_base_fraction
ConsistencyFlag
ctx
define_diagnostics
define_model_state
dt
dt_TempAge
energy_balance_model
energy_model_inputs
energy_step
enforce_consistency_of_geometry
extras_max_timestep
flush_timeseries
forced_retreat
front_retreat_step
frontal_melt
geometry
geometry_evolution
grid
HistoryTreatment
hydrology_step
ice_area_cold
ice_area_temperate
ice_volume_cold
ice_volume_temperate
IceModel
init
init_backups
init_calving
init_diagnostics
init_extras
init_front_retreat
init_frontal_melt
init_snapshots
init_timeseries
initialize_2d
list_diagnostics
list_diagnostics_json
m_adaptive_timestep_reason
m_age_model
m_backup_filename
m_backup_vars
m_basal_melt_rate
m_basal_yield_stress
m_basal_yield_stress_model
m_beddef
m_bedtoptemp
m_btu
m_calving_rate_factor
m_config
m_ctx
m_current_snapshot
m_diagnostics
m_dt
m_eigen_calving
m_energy_model
m_extra_bounds
m_extra_file
m_extra_file_is_ready
m_extra_filename
m_extra_times
m_extra_vars
m_float_kill_calving
m_fracture
m_front_retreat
m_frontal_melt
m_geometry
m_geometry_evolution
m_grid
m_hayhurst_calving
m_ice_thickness_bc_mask
m_iceberg_remover
m_last_backup_time
m_last_extra
m_log
m_model_state
m_n_work2d
m_new_bed_elevation
m_next_extra
m_ocean
m_output_global_attributes
m_output_vars
m_prescribed_retreat
m_run_stats
m_save_extra
m_save_snapshots
m_sea_level
m_skip_countdown
m_snapshot_times
m_snapshot_vars
m_snapshots_file_is_ready
m_snapshots_filename
m_split_extra
m_split_snapshots
m_start_time
m_stdout_flags
m_stress_balance
m_subglacial_hydrology
m_submodels
m_surface
m_surface_input_for_hydrology
m_sys
m_thickness_change
m_thickness_threshold_calving
m_time
m_timestamp
m_timestep_hit_multiples_last_time
m_ts_diagnostics
m_ts_filename
m_ts_times
m_ts_vars
m_velocity_bc_mask
m_velocity_bc_values
m_viewers
m_vonmises_calving
m_wide_stencil
m_work2d
MappingTreatment
max_timestep
max_timestep_diffusivity
misc_setup
model_state_setup
ocean_model
output_variables
OutputKind
post_step_hook
pre_step_hook
prepend_history
print_summary
print_summary_line
process_options
process_signals
prune_diagnostics
regrid
reset_counters
reset_diagnostics
restart_2d
run
run_to
save_max_timestep
save_results
save_variables
skip_counter
step
stress_balance
stress_balance_inputs
t_TempAge
time_setup
ts_max_timestep
update_diagnostics
update_fracture_density
update_run_stats
update_viewers
view_field
write_backup
write_diagnostics
write_extras
write_mapping
write_metadata
write_model_state
write_run_stats
write_snapshot
yield_stress_inputs
~IceModel
process_signals()
int pism::IceModel::process_signals () protected virtual
Catch signals -USR1, -USR2 and -TERM.
Signal SIGTERM makes PISM end, saving state under original -o name (or default name). We also add an indication to the history attribute of the output NetCDF file.
Signal SIGUSR1 makes PISM save state under a filename based on the the name of the executable (e.g. pismr or pismv) and the current model year. In addition the time series (-ts_file, etc.) is flushed out There is no indication of these actions in the history attribute of the output (-o) NetCDF file because there is no effect on it, but there is an indication at stdout.
Signal SIGUSR2 makes PISM flush time-series, without saving model state.
Definition at line 48 of file utilities.cc.
References flush_timeseries(), INCLUDE_MODEL_STATE, m_config, m_ctx, m_grid, m_log, m_output_vars, m_time, pism::PISM_READWRITE_MOVE, pism_signal, prepend_history(), pism::printf(), pism::replace_character(), save_variables(), and pism::string_to_backend().
Referenced by run().