PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSATestCaseCFBC::initializeSSACoefficients
C
exactSolution
H0
initializeSSACoefficients
SSATestCaseCFBC
V0
write_nuH
initializeSSACoefficients()
void pism::stressbalance::SSATestCaseCFBC::initializeSSACoefficients () protected virtual
Set up the coefficient variables as appropriate for the test case.
Implements pism::stressbalance::SSATestCase.
Definition at line 97 of file ssa_test_cfbc.cc.
References pism::Geometry::bed_elevation, C, pism::Geometry::cell_type, pism::Geometry::ensure_consistency(), H0, pism::stressbalance::H_exact(), pism::Geometry::ice_surface_elevation, pism::Geometry::ice_thickness, pism::stressbalance::SSATestCase::m_bc_mask, pism::stressbalance::SSATestCase::m_bc_values, pism::stressbalance::SSATestCase::m_enthalpyconverter, pism::stressbalance::SSATestCase::m_geometry, pism::stressbalance::SSATestCase::m_grid, pism::stressbalance::SSATestCase::m_ice_enthalpy, pism::stressbalance::SSATestCase::m_tauc, pism::PointsWithGhosts::next(), pism::IceModelVec::set(), pism::IceModelVec::update_ghosts(), and V0.