PISM, A Parallel Ice Sheet Model: pism::LocalInterpCtx::LocalInterpCtx
buffer
count
LocalInterpCtx
start
x
y
z
LocalInterpCtx()
pism::LocalInterpCtx::LocalInterpCtx (const grid_info & input, const IceGrid & grid, const std::vector< double > & z_output, InterpolationType type)
Construct a local interpolation context.
The essential quantities to compute are where each processor should start within the NetCDF file grid (start[]) and how many grid points, from the starting place, the processor has. The resulting portion of the grid is stored in array a (a field of the LocalInterpCtx).
We make conservative choices about start[] and count[]. In particular, the portions owned by processors must overlap at one point in the NetCDF file grid, but they may overlap more than that (as computed here).
Note this constructor doesn't extract new information from the NetCDF file or do communication. The information from the NetCDF file must already be extracted, validly stored in a grid_info structure input.
The IceGrid is used to determine what ranges of the target arrays (i.e. Vecs into which NetCDF information will be interpolated) are owned by each processor.
Definition at line 83 of file LocalInterpCtx.cc.
References buffer, pism::ParallelSection::check(), pism::IceGrid::com, count, pism::IceGrid::ctx(), pism::ParallelSection::failed(), pism::LINEAR, pism::max(), pism::NEAREST, PISM_ERROR_LOCATION, pism::IceGrid::rank(), pism::grid_info::report(), start, pism::subset_start_and_count(), pism::grid_info::t_len, pism::grid_info::x, pism::IceGrid::x(), x, pism::IceGrid::xm(), pism::IceGrid::xs(), pism::grid_info::y, pism::IceGrid::y(), y, pism::IceGrid::ym(), pism::IceGrid::ys(), pism::grid_info::z, z, and pism::grid_info::z_len.