PISM, A Parallel Ice Sheet Model: pism::diagnostics::scalar::IceVolumeGlacierizedGrounded::compute
compute
IceVolumeGlacierizedGrounded
compute()
double pism::diagnostics::scalar::IceVolumeGlacierizedGrounded::compute () inline virtual
Compute the diagnostic. Regular (snapshot) quantity should be computed here; for rates of change, compute() should return the total change during the time step from t0 to t1. The rate itself is computed in evaluate_rate().
Implements pism::TSDiagnostic.
Definition at line 1409 of file diagnostics.cc.
References pism::Geometry::cell_type, pism::IceModel::geometry(), pism::GlobalSum(), pism::IceModelVec2CellType::grounded(), pism::Geometry::ice_thickness, pism::TSDiagnostic::m_config, pism::TSDiagnostic::m_grid, pism::TSDiag< TSSnapshotDiagnostic, IceModel >::model, and pism::PointsWithGhosts::next().