PISM, A Parallel Ice Sheet Model: pism::ocean::OceanModel::update_impl
allocate_shelf_base_mass_flux
allocate_shelf_base_temperature
allocate_water_column_pressure
average_water_column_pressure
average_water_column_pressure_impl
compute_average_water_column_pressure
define_model_state_impl
diagnostics_impl
init
init_impl
m_input_model
m_water_column_pressure
max_timestep_impl
OceanModel
OceanModel
shelf_base_mass_flux
shelf_base_mass_flux_impl
shelf_base_temperature
shelf_base_temperature_impl
ts_diagnostics_impl
update
update_impl
write_model_state_impl
~OceanModel
update_impl()
void pism::ocean::OceanModel::update_impl (const Geometry & geometry, double t, double dt) protected virtual
Reimplemented in pism::ocean::Runoff_SMB, pism::ocean::Pico, pism::ocean::InitializationHelper, pism::ocean::GivenTH, pism::ocean::Given, pism::ocean::Frac_SMB, pism::ocean::Frac_MBP, pism::ocean::Delta_T, pism::ocean::Delta_SMB, pism::ocean::Delta_MBP, pism::ocean::Constant, pism::ocean::Anomaly, pism::ocean::PIK, and pism::ocean::Cache.
Definition at line 112 of file OceanModel.cc.
References pism::RuntimeError::formatted(), m_input_model, and PISM_ERROR_LOCATION.
Referenced by update(), and pism::ocean::InitializationHelper::update_impl().