PISM, A Parallel Ice Sheet Model: pism::energy::EnthalpyModel_Regional::EnthalpyModel_Regional
bootstrap_impl
EnthalpyModel_Regional
initialize_impl
m_basal_melt_rate_stored
m_no_model_mask
restart_impl
update_impl
EnthalpyModel_Regional()
pism::energy::EnthalpyModel_Regional::EnthalpyModel_Regional (std::shared_ptr< const Grid > grid, std::shared_ptr< const stressbalance::StressBalance > stress_balance)
Definition at line 25 of file EnthalpyModel_Regional.cc.
References pism::VariableMetadata::long_name(), m_basal_melt_rate_stored, pism::array::Array::metadata(), and pism::VariableMetadata::units().