PISM, A Parallel Ice Sheet Model: pism::Diagnostic::to_internal
allocate
compute
compute_impl
define
define_impl
define_state
define_state_impl
Diagnostic
init
init_impl
m_config
m_fill_value
m_grid
m_sys
m_vars
metadata
n_variables
Ptr
reset
reset_impl
to_external
to_internal
update
update_impl
wrap
write_state
write_state_impl
~Diagnostic
to_internal()
double pism::Diagnostic::to_internal (double x) const protected
Convert from external (output) units to internal units.
Definition at line 59 of file Diagnostic.cc.
References pism::units::convert(), m_sys, and m_vars.
Referenced by pism::surface::diagnostics::Accumulation::Accumulation(), pism::diagnostics::BasalFlux::BasalFlux(), pism::diagnostics::BMBSplit::BMBSplit(), pism::diagnostics::CalvingFlux::CalvingFlux(), pism::stressbalance::PSB_velbar_mag::compute_impl(), pism::stressbalance::PSB_flux_mag::compute_impl(), pism::stressbalance::PSB_velbase_mag::compute_impl(), pism::stressbalance::PSB_velsurf_mag::compute_impl(), pism::stressbalance::PSB_velsurf::compute_impl(), pism::stressbalance::PSB_wvelsurf::compute_impl(), pism::stressbalance::PSB_wvelbase::compute_impl(), pism::stressbalance::PSB_velbase::compute_impl(), pism::DiagAverageRate< M >::compute_impl(), pism::hydrology::diagnostics::ConservationErrorFlux::ConservationErrorFlux(), pism::diagnostics::ConservationErrorFlux::ConservationErrorFlux(), pism::surface::diagnostics::DEBMSBackroundMelt::DEBMSBackroundMelt(), pism::surface::diagnostics::DEBMSTemperatureMelt::DEBMSTemperatureMelt(), pism::diagnostics::DischargeFlux::DischargeFlux(), pism::hydrology::diagnostics::DomainBoundaryFlux::DomainBoundaryFlux(), pism::diagnostics::ForcedRetreatFlux::ForcedRetreatFlux(), pism::diagnostics::FrontalMeltFlux::FrontalMeltFlux(), pism::frontalmelt::diagnostics::FrontalMeltRate::FrontalMeltRate(), pism::frontalmelt::diagnostics::FrontalMeltRetreatRate::FrontalMeltRetreatRate(), pism::hydrology::diagnostics::GroundedMarginFlux::GroundedMarginFlux(), pism::hydrology::diagnostics::GroundingLineFlux::GroundingLineFlux(), pism::diagnostics::GroundingLineFlux::GroundingLineFlux(), pism::stressbalance::PSB_flux_mag::PSB_flux_mag(), pism::stressbalance::PSB_velbar_mag::PSB_velbar_mag(), pism::stressbalance::PSB_velbase::PSB_velbase(), pism::stressbalance::PSB_velbase_mag::PSB_velbase_mag(), pism::stressbalance::PSB_velsurf::PSB_velsurf(), pism::stressbalance::PSB_velsurf_mag::PSB_velsurf_mag(), pism::stressbalance::PSB_wvel::PSB_wvel(), pism::stressbalance::PSB_wvelbase::PSB_wvelbase(), pism::stressbalance::PSB_wvelsurf::PSB_wvelsurf(), pism::surface::diagnostics::SMBAdjustment::SMBAdjustment(), pism::hydrology::diagnostics::SubglacialWaterFlux::SubglacialWaterFlux(), pism::diagnostics::SurfaceFlux::SurfaceFlux(), pism::surface::diagnostics::SurfaceMelt::SurfaceMelt(), pism::surface::diagnostics::SurfaceRunoff::SurfaceRunoff(), pism::diagnostics::TendencyOfIceAmount::TendencyOfIceAmount(), pism::diagnostics::TendencyOfIceAmountDueToFlow::TendencyOfIceAmountDueToFlow(), pism::hydrology::diagnostics::TendencyOfWaterMass::TendencyOfWaterMass(), pism::hydrology::diagnostics::TendencyOfWaterMassDueToFlow::TendencyOfWaterMassDueToFlow(), pism::diagnostics::ThicknessRateOfChange::ThicknessRateOfChange(), pism::hydrology::diagnostics::TotalInputRate::TotalInputRate(), and pism::hydrology::diagnostics::WaterInputFlux::WaterInputFlux().