PISM, A Parallel Ice Sheet Model: pism::array::Scalar::as_int
as_int
box_int
duplicate
Scalar
Scalar
star_int
as_int()
int pism::array::Scalar::as_int (int i, int j) const inline
Definition at line 45 of file Scalar.hh.
Referenced by pism::stressbalance::SSAFD::assemble_matrix(), pism::stressbalance::SSAFD::assemble_rhs(), pism::Poisson::assemble_rhs(), pism::ocean::Pico::beckmann_goosse(), box_int(), pism::ocean::Pico::compute_box_area(), pism::ocean::Pico::compute_box_average(), pism::ocean::PicoGeometry::compute_box_mask(), pism::ocean::PicoGeometry::compute_continental_shelf_mask(), pism::ocean::PicoGeometry::compute_distances_cf(), pism::ocean::PicoGeometry::compute_distances_gl(), pism::ocean::PicoGeometry::compute_ice_shelf_mask(), pism::RegionalGeometryEvolution::compute_interface_fluxes(), pism::hydrology::EmptyingProblem::compute_mask(), pism::ocean::Pico::compute_ocean_input_per_basin(), pism::GeometryEvolution::compute_surface_and_basal_mass_balance(), pism::ocean::eikonal_equation(), pism::array::CellType::floating_ice(), pism::array::CellType::grounded(), pism::array::CellType::grounded_ice(), pism::array::CellType::ice_free(), pism::array::CellType::ice_free_land(), pism::array::CellType::ice_free_ocean(), pism::array::CellType::icy(), pism::ocean::PicoGeometry::identify_calving_front_connection(), pism::IceModel::model_state_setup(), pism::array::CellType::ocean(), pism::ocean::Pico::process_box1(), pism::ocean::Pico::process_other_boxes(), pism::ocean::relabel(), pism::ocean::Pico::set_ocean_input_fields(), pism::ocean::PicoGeometry::split_ice_shelves(), star_int(), and pism::FrontRetreat::update_geometry().