PISM, A Parallel Ice Sheet Model: pism::calving::HayhurstCalving::update
calving_rate
diagnostics_impl
HayhurstCalving
init
m_B_tilde
m_calving_rate
m_exponent_r
m_sigma_threshold
update
~HayhurstCalving
update()
void pism::calving::HayhurstCalving::update (const IceModelVec2CellType & cell_type, const IceModelVec2S & ice_thickness, const IceModelVec2S & sea_level, const IceModelVec2S & bed_elevation)
Definition at line 69 of file HayhurstCalving.cc.
References pism::units::convert(), pism::East, pism::IceModelVec2CellType::ice_free(), pism::IceModelVec2CellType::icy(), pism::mask::icy(), m_B_tilde, m_calving_rate, pism::Component::m_config, m_exponent_r, pism::Component::m_grid, m_sigma_threshold, pism::Component::m_sys, pism::max(), pism::min(), n, pism::PointsWithGhosts::next(), pism::IceModelVec2CellType::next_to_ice(), pism::North, pism::South, pism::IceModelVec2S::star(), pism::IceModelVec2Int::star(), pism::IceModelVec::update_ghosts(), and pism::West.