PISM, A Parallel Ice Sheet Model: pism::array::Array2D::add
add
add
array
array
Array2D
box
copy_from
operator()
operator()
star
value_type
add() [1/2]
template<typename T > void pism::array::Array2D< T >::add (double alpha, const Array2D< T > & x) inline
Definition at line 65 of file Array2D.hh.
References pism::array::details::add().
Referenced by pism::diagnostics::accumulate_changes(), pism::GeometryEvolution::apply_flux_divergence(), pism::inverse::IP_SSATaucTikhonovGNSolver::apply_GN(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::bed::BedDef::apply_topg_offset(), pism::inverse::IP_SSATaucTikhonovGNSolver::assemble_GN_rhs(), pism::stressbalance::SSAFD::assemble_matrix(), pism::stressbalance::SSAFD::assemble_rhs(), pism::bed::LingleClark::bootstrap_impl(), pism::stressbalance::SSAFEM::cache_inputs(), pism::IceModel::combine_basal_melt_rate(), pism::hydrology::Routing::compute_conductivity(), pism::inverse::IP_SSATaucTikhonovGNSolver::compute_dlogalpha(), pism::stressbalance::SSA::compute_driving_stress(), pism::diagnostics::ThicknessRateOfChange::compute_impl(), pism::diagnostics::IceAreaFraction::compute_impl(), pism::diagnostics::IceMass::compute_impl(), pism::hydrology::EmptyingProblem::compute_mask(), pism::bed::BedDef::compute_uplift(), pism::inverse::IPMeanSquareFunctional2S::dot(), pism::inverse::IPMeanSquareFunctional2V::dot(), pism::icebin::IBIceModel::energy_step(), pism::hydrology::Hydrology::enforce_bounds(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluate_objective_and_gradient(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluateGNFunctional(), pism::GeometryEvolution::flow_step(), pism::IceModel::front_retreat_step(), pism::inverse::IPMeanSquareFunctional2S::gradientAt(), pism::inverse::IPLogRatioFunctional::gradientAt(), pism::inverse::IPLogRelativeFunctional::gradientAt(), pism::inverse::IPMeanSquareFunctional2V::gradientAt(), pism::ice_volume(), pism::bed::LingleClark::init_impl(), pism::diagnostics::scalar::mass_change(), pism::IceModel::max_timestep(), pism::bed::LingleClark::step(), pism::hydrology::EmptyingProblem::update(), pism::IceModel::update_fracture_density(), pism::bed::Given::update_impl(), pism::surface::TemperatureIndex::update_impl(), pism::MohrCoulombYieldStress::update_impl(), pism::hydrology::diagnostics::SubglacialWaterFlux::update_impl(), pism::DiagAverageRate< M >::update_impl(), pism::hydrology::NullTransport::update_impl(), pism::GeometryEvolution::update_in_place(), pism::hydrology::Routing::update_W(), pism::inverse::IPLogRatioFunctional::valueAt(), pism::inverse::IPLogRelativeFunctional::valueAt(), pism::inverse::IPMeanSquareFunctional2V::valueAt(), and pism::hydrology::wall_melt().