PISM, A Parallel Ice Sheet Model: pism::fem::DirichletData_Scalar::enforce_homogeneous
DirichletData_Scalar
enforce
enforce_homogeneous
fix_jacobian
fix_residual
fix_residual_homogeneous
m_values
~DirichletData_Scalar
enforce_homogeneous()
void pism::fem::DirichletData_Scalar::enforce_homogeneous (const Element2 & element, double * x_e)
Definition at line 113 of file DirichletData.cc.
References pism::IceModelVec2S::array(), pism::k, pism::fem::DirichletData::m_indices, pism::fem::DirichletData::m_indices_e, pism::fem::Element::n_chi(), and pism::fem::Element2::nodal_values().
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_H1NormFunctional2S::dot(), pism::inverse::IPGroundedIceH1NormFunctional2S::dot(), pism::inverse::IP_H1NormFunctional2S::gradientAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::gradientAt(), pism::inverse::IPTotalVariationFunctional2S::gradientAt(), pism::inverse::IP_H1NormFunctional2S::valueAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::valueAt(), and pism::inverse::IPTotalVariationFunctional2S::valueAt().