PISM, A Parallel Ice Sheet Model: pism::Geometry::dump
bed_elevation
cell_grounded_fraction
cell_type
dump
ensure_consistency
Geometry
ice_area_specific_volume
ice_surface_elevation
ice_thickness
latitude
longitude
sea_level_elevation
dump()
void pism::Geometry::dump (const char * filename) const
Definition at line 193 of file Geometry.cc.
References pism::io::append_time(), bed_elevation, cell_grounded_fraction, cell_type, pism::io::define_time(), pism::array::Array::grid(), ice_area_specific_volume, ice_surface_elevation, ice_thickness, latitude, longitude, pism::io::PISM_READWRITE_CLOBBER, sea_level_elevation, pism::string_to_backend(), and pism::array::Array::write().
Referenced by ensure_consistency().