PISM, A Parallel Ice Sheet Model: pism::hydrology::Routing::update_impl
advective_fluxes
bootstrap_impl
compute_conductivity
compute_velocity
define_model_state_impl
diagnostics_impl
init_impl
initialization_message
m_bottom_surface
m_dx
m_dy
m_Kstag
m_Qstag
m_Qstag_average
m_R
m_rg
m_Vstag
m_Wnew
m_Wstag
m_Wtillnew
max_timestep_W_cfl
max_timestep_W_diff
restart_impl
Routing
subglacial_water_pressure
ts_diagnostics_impl
update_impl
update_W
update_Wtill
velocity_staggered
W_change_due_to_flow
water_thickness_staggered
write_model_state_impl
~Routing
update_impl()
void pism::hydrology::Routing::update_impl (double t, double dt, const Inputs & inputs) protected virtual
Update the model state variables W and Wtill by applying the subglacial hydrology model equations.
Runs the hydrology model from time t to time t + dt. Here [t, dt] is generally on the order of months to years. This hydrology model will take its own shorter time steps, perhaps hours to weeks.
To update W = bwat we call update_W(), and to update Wtill = tillwat we call update_Wtill().
Implements pism::hydrology::Hydrology.
Reimplemented in pism::hydrology::Distributed.
Definition at line 835 of file Routing.cc.
References pism::array::Array::add(), advective_fluxes(), pism::Profiling::begin(), pism::Geometry::cell_type, pism::hydrology::check_bounds(), compute_conductivity(), compute_velocity(), pism::units::convert(), pism::array::Array2D< T >::copy_from(), pism::Profiling::end(), pism::hydrology::Hydrology::enforce_bounds(), pism::hydrology::Inputs::geometry, pism::ice_bottom_surface(), pism::hydrology::Hydrology::m_basal_melt_rate, m_bottom_surface, pism::Component::m_config, pism::hydrology::Hydrology::m_conservation_error_change, pism::hydrology::Hydrology::m_grounded_margin_change, pism::hydrology::Hydrology::m_grounding_line_change, m_Kstag, pism::Component::m_log, pism::hydrology::Hydrology::m_no_model_mask_change, pism::hydrology::Hydrology::m_Q, m_Qstag, m_Qstag_average, pism::hydrology::Hydrology::m_surface_input_rate, pism::Component::m_sys, m_Vstag, pism::hydrology::Hydrology::m_W, m_Wnew, m_Wstag, pism::hydrology::Hydrology::m_Wtill, m_Wtillnew, max_timestep_W_cfl(), max_timestep_W_diff(), pism::array::min(), pism::hydrology::Inputs::no_model_mask, pism::Component::profiling(), pism::array::Array::scale(), pism::array::Array::set(), pism::array::staggered_to_regular(), subglacial_water_pressure(), pism::array::Array::update_ghosts(), update_W(), update_Wtill(), and water_thickness_staggered().