PISM, A Parallel Ice Sheet Model: pism::calving::vonMisesCalving::update
diagnostics_impl
init
m_calving_threshold
m_flow_law
threshold
update
vonMisesCalving
~vonMisesCalving
update()
void pism::calving::vonMisesCalving::update (const array::CellType1 & cell_type, const array::Scalar & ice_thickness, const array::Vector1 & ice_velocity, const array::Array3D & ice_enthalpy)
Uses principal strain rates to apply the "von Mises" calving method.
See equation (4) in [Morlighem2016].
Definition at line 101 of file vonMisesCalving.cc.
References pism::rheology::averaged_hardness(), pism::stressbalance::compute_2D_principal_strain_rates(), pism::array::Array2D< T >::copy_from(), pism::array::Array3D::get_column(), I, pism::array::CellType::ice_free_ocean(), pism::array::CellType::icy(), J, pism::k, pism::calving::StressCalving::m_calving_rate, m_calving_threshold, pism::calving::StressCalving::m_cell_type, m_flow_law, pism::Component::m_grid, pism::calving::StressCalving::m_stencil_width, pism::calving::StressCalving::m_strain_rates, pism::array::max(), and pism::array::CellType1::next_to_ice().