PISM, A Parallel Ice Sheet Model: pism::inverse::IPDesignVariableParameterization::set_scales
convertFromDesignVariable
convertToDesignVariable
fromDesignVariable
IPDesignVariableParameterization
m_d_scale
set_scales
toDesignVariable
~IPDesignVariableParameterization
set_scales()
void pism::inverse::IPDesignVariableParameterization::set_scales (const Config & config, const std::string & design_var_name) virtual
Initializes the scale parameters of the parameterization.
Every IPDesignVariableParameterization has an associated scale for the design variable \(d_{\rm scale}\) that equals 1 in internal units. The scale for a design variable named foo is stored in an Config file as design_param_foo_scale. Subclasses may have additional parameters that are follow the naming convention design_param_foo_*.
Parameters
config The config file to read the scale parameters from.
design_var_name The associated name of the design variable, e.g. 'tauc' or 'hardav'
Reimplemented in pism::inverse::IPDesignVariableParamTruncatedIdent, and pism::inverse::IPDesignVariableParamExp.
Definition at line 41 of file IPDesignVariableParameterization.cc.
References pism::Config::get_number(), and m_d_scale.
Referenced by pism::inverse::IPDesignVariableParamExp::set_scales(), and pism::inverse::IPDesignVariableParamTruncatedIdent::set_scales().