PISM, A Parallel Ice Sheet Model: pism::IceModelVec::set
AccessList
add
allocate_proc0_copy
begin_access
cast
check_array_indices
checkCompatibility
checksum
ConstPtr
copy_to_vec
define
dm
dump
end_access
fletcher64
fletcher64_serial
get_dof
get_from_proc0
get_from_proc0
get_name
grid
IceModelVec
IceModelVec
inc_state_counter
levels
m_array
m_impl
metadata
metadata
ndims
ndof
norm
operator=
print_checksum
Ptr
put_on_proc0
put_on_proc0
range
read
read
read_impl
regrid
regrid
regrid_impl
scale
set
set_attrs
set_begin_access_use_dof
set_dof
set_name
set_time_independent
shape
shift
size
state_counter
stencil_width
update_ghosts
vec
view
write
write
write_impl
~IceModelVec
set()
void pism::IceModelVec::set (double c)
Result: v[j] <- c for all j.
Definition at line 683 of file iceModelVec.cc.
References inc_state_counter(), PISM_CHK, and vec().
Referenced by pism::IceModel::allocate_storage(), pism::IceRegionalModel::allocate_storage(), pism::inverse::IP_SSATaucTikhonovGNSolver::assemble_GN_rhs(), pism::stressbalance::SSAFD::assemble_rhs(), pism::IceModel::bootstrap_2d(), pism::stressbalance::SSAFEM::cache_inputs(), pism::stressbalance::SSAFEM::cache_residual_cfbc(), pism::ocean::PicoGeometry::compute_box_mask(), pism::compute_cell_areas(), pism::stressbalance::SIAFD::compute_diffusivity(), pism::ocean::PicoGeometry::compute_distances_cf(), pism::ocean::PicoGeometry::compute_distances_gl(), pism::stressbalance::Blatter::compute_node_type(), pism::hydrology::Hydrology::compute_surface_input_rate(), pism::DiagAverageRate< M >::DiagAverageRate(), pism::surface::ForceThickness::ForceThickness(), pism::IceModel::front_retreat_step(), pism::Geometry::Geometry(), pism::inverse::IP_H1NormFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2S::gradientAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::gradientAt(), pism::inverse::IPMeanSquareFunctional2S::gradientAt(), pism::inverse::IPTotalVariationFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2V::gradientAt(), pism::inverse::IPLogRatioFunctional::gradientAt(), pism::inverse::IPLogRelativeFunctional::gradientAt(), pism::inverse::IPMeanSquareFunctional2V::gradientAt(), pism::hydrology::Hydrology::Hydrology(), pism::calving::EigenCalving::init(), pism::calving::vonMisesCalving::init(), pism::inverse::IP_SSAHardavForwardProblem::init(), pism::inverse::IP_SSATaucForwardProblem::init(), pism::AgeModel::init(), pism::stressbalance::SSA::init_impl(), pism::DiagAverageRate< M >::init_impl(), pism::ocean::sea_level::SeaLevel::init_impl(), pism::surface::TemperatureIndex::init_impl(), pism::icebin::IBSurfaceModel::init_impl(), pism::hydrology::SteadyState::init_impl(), pism::bed::Null::init_impl(), pism::ConstantYieldStress::init_impl(), pism::MohrCoulombYieldStress::init_impl(), pism::FractureDensity::initialize(), pism::IceEISModel::initialize_2d(), pism::IceCompModel::initialize_2d(), pism::energy::BedThermalUnit::initialize_bottom_surface_flux(), pism::energy::BTU_Verification::initialize_bottom_surface_flux(), pism::energy::TemperatureModel_Verification::initialize_impl(), pism::stressbalance::SSATestCaseCFBC::initializeSSACoefficients(), pism::stressbalance::SSATestCaseConst::initializeSSACoefficients(), pism::stressbalance::SSATestCaseExp::initializeSSACoefficients(), pism::stressbalance::SSATestCasePlug::initializeSSACoefficients(), pism::stressbalance::SSATestCaseI::initializeSSACoefficients(), pism::stressbalance::SSATestCaseJ::initializeSSACoefficients(), pism::IceCompModel::initTestABCDH(), pism::IceCompModel::initTestFG(), pism::IceCompModel::initTestL(), pism::IceCompModel::initTestsKO(), main(), pism::IceModel::max_timestep(), pism::IceModel::model_state_setup(), pism::IceRegionalModel::model_state_setup(), pism::OptTillphiYieldStress::OptTillphiYieldStress(), pism::ocean::relabel(), pism::GeometryEvolution::reset(), pism::DiagAverageRate< M >::reset_impl(), pism::GeometryEvolution::residual_redistribution_iteration(), pism::setInitStateF(), pism::stressbalance::SSATestCase::SSATestCase(), pism::surface::TemperatureIndex::TemperatureIndex(), pism::IceCompModel::test_V_init(), pism::stressbalance::BedSmoother::theta(), pism::hydrology::EmptyingProblem::update(), pism::stressbalance::BlatterMod::update(), pism::stressbalance::ConstantInColumn::update(), pism::stressbalance::ZeroSliding::update(), pism::stressbalance::PrescribedSliding::update(), pism::hydrology::Hydrology::update(), pism::FrontRetreat::update_geometry(), pism::ocean::Pico::update_impl(), pism::ocean::sea_level::SeaLevel::update_impl(), pism::calving::IcebergRemover::update_impl(), pism::calving::IcebergRemoverFEM::update_impl(), pism::hydrology::Distributed::update_impl(), pism::hydrology::NullTransport::update_impl(), pism::hydrology::Routing::update_impl(), pism::GeometryEvolution::update_in_place(), and pism::OptTillphiYieldStress::update_tillphi().