PISM, A Parallel Ice Sheet Model: pism::IceModelVec::grid
AccessList
add
allocate_proc0_copy
begin_access
cast
check_array_indices
checkCompatibility
checksum
ConstPtr
copy_to_vec
define
dm
dump
end_access
fletcher64
get_dof
get_from_proc0
get_from_proc0
get_name
grid
IceModelVec
IceModelVec
inc_state_counter
levels
m_array
m_impl
metadata
metadata
ndims
ndof
norm
operator=
print_checksum
Ptr
put_on_proc0
put_on_proc0
range
read
read
read_impl
regrid
regrid
regrid_impl
scale
set
set_attrs
set_begin_access_use_dof
set_dof
set_name
set_time_independent
shape
shift
size
state_counter
stencil_width
update_ghosts
vec
view
write
write
write_impl
~IceModelVec
grid()
IceGrid::ConstPtr pism::IceModelVec::grid () const
Definition at line 128 of file iceModelVec.cc.
References pism::IceModelVec::Impl::grid, and m_impl.
Referenced by pism::absmax(), pism::apply_mask(), pism::rheology::averaged_hardness_vec(), pism::bedrock_surface_temperature(), pism::energy::bootstrap_ice_temperature(), check_array_indices(), pism::hydrology::check_bounds(), pism::check_maximum_ice_thickness(), pism::check_minimum_ice_thickness(), pism::stressbalance::compute_2D_principal_strain_rates(), pism::stressbalance::compute_2D_stresses(), pism::ocean::OceanModel::compute_average_water_column_pressure(), pism::compute_cell_areas(), pism::energy::compute_cts(), pism::energy::compute_enthalpy(), pism::energy::compute_enthalpy_cold(), pism::compute_grounded_cell_fraction(), pism::energy::compute_liquid_water_fraction(), pism::bed::compute_load(), pism::compute_magnitude(), pism::GeometryCalculator::compute_mask(), pism::compute_node_types(), pism::hydrology::diagnostics::compute_sinks(), pism::GeometryCalculator::compute_surface(), pism::energy::compute_temperature(), pism::IceModelVec2T::Constant(), pism::inverse::IPDesignVariableParameterization::convertFromDesignVariable(), pism::inverse::IPDesignVariableParameterization::convertToDesignVariable(), pism::stressbalance::copy_staggered_vec(), pism::count_CFL_violations(), pism::energy::cryo_hydrologic_warming_flux(), pism::diff_x(), pism::diff_x_p(), pism::diff_y(), pism::diff_y_p(), dm(), pism::Geometry::dump(), pism::stressbalance::Inputs::dump(), pism::duplicate(), pism::hydrology::diagnostics::effective_water_velocity(), pism::ocean::eikonal_equation(), pism::Geometry::ensure_consistency(), pism::atmosphere::era_interim(), pism::atmosphere::era_interim_lon(), pism::atmosphere::era_interim_sin(), pism::ocean::extend_basal_melt_rates(), pism::extract_surface(), pism::fem::DirichletData::finish(), pism::fem::DirichletData_Scalar::fix_jacobian(), pism::fem::DirichletData_Vector::fix_jacobian(), pism::fem::DirichletData_Scalar::fix_residual(), pism::fem::DirichletData_Vector::fix_residual(), pism::fem::DirichletData_Scalar::fix_residual_homogeneous(), pism::fem::DirichletData_Vector::fix_residual_homogeneous(), pism::IceModelVec2T::ForcingField(), pism::generate_mound_topography(), pism::generate_trough_topography(), pism::inverse::gradientFD(), pism::grounding_line_flux(), pism::atmosphere::huybrechts_dewolde(), pism::hydrology::diagnostics::hydraulic_potential(), pism::ice_area(), pism::ice_area_floating(), pism::ice_area_grounded(), pism::ice_bottom_surface(), pism::ice_volume(), pism::ice_volume_not_displacing_seawater(), IceModelVec(), pism::IceModelVec2T::init_periodic_data(), pism::surface::diagnostics::integrate(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::IP_SSATaucTaoTikhonovProblemLCL(), pism::inverse::IP_SSATaucTikhonovGNSolver::IP_SSATaucTikhonovGNSolver(), pism::label_components(), pism::lapse_rate_correction(), pism::atmosphere::martin2011(), pism::atmosphere::martin_huybrechts_dewolde(), pism::max(), pism::FrontRetreat::max_timestep(), pism::max_timestep_cfl_2d(), pism::max_timestep_cfl_3d(), pism::min(), read_impl(), regrid_impl(), pism::ocean::relabel(), pism::remove_narrow_tongues(), pism::sea_level_rise_potential(), pism::set_no_model_yield_stress(), shape(), pism::staggered_to_regular(), pism::sum(), pism::sum_columns(), pism::total_grounding_line_flux(), pism::energy::total_ice_enthalpy(), pism::hydrology::wall_melt(), write_impl(), and pism::stressbalance::zero_above_ice().