PISM, A Parallel Ice Sheet Model: pism::stressbalance::PSB_deviatoric_stresses::compute_impl
compute_impl
PSB_deviatoric_stresses
compute_impl()
IceModelVec::Ptr pism::stressbalance::PSB_deviatoric_stresses::compute_impl () const protected virtual
Implements pism::Diagnostic.
Definition at line 841 of file StressBalance_diagnostics.cc.
References pism::rheology::averaged_hardness_vec(), pism::Diagnostic::compute(), pism::stressbalance::compute_2D_stresses(), pism::IceModelVec2< T >::copy_from(), pism::Diagnostic::m_grid, pism::Diagnostic::m_vars, pism::Diag< StressBalance >::model, pism::WITH_GHOSTS, and pism::WITHOUT_GHOSTS.