PISM, A Parallel Ice Sheet Model: pism::diagnostics::BMBSplit::update_impl
BMBSplit
m_kind
update_impl
update_impl()
void pism::diagnostics::BMBSplit::update_impl (double dt) inline protected virtual
Reimplemented from pism::DiagAverageRate< IceModel >.
Definition at line 175 of file diagnostics.cc.
References pism::GeometryEvolution::bottom_surface_mass_balance(), pism::Geometry::cell_type, pism::IceModel::geometry(), pism::IceModel::geometry_evolution(), pism::diagnostics::GROUNDED, pism::IceModelVec2CellType::grounded(), pism::DiagAverageRate< IceModel >::m_accumulator, pism::Diagnostic::m_config, pism::Diagnostic::m_grid, pism::DiagAverageRate< IceModel >::m_interval_length, m_kind, pism::Diag< IceModel >::model, pism::PointsWithGhosts::next(), pism::IceModelVec2CellType::ocean(), and pism::diagnostics::SHELF.