PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSATestCaseExp::initializeSSACoefficients
dhdx
exactSolution
H0
initializeSSACoefficients
L
nu0
SSATestCaseExp
tauc0
initializeSSACoefficients()
void pism::stressbalance::SSATestCaseExp::initializeSSACoefficients () protected virtual
Set up the coefficient variables as appropriate for the test case.
Implements pism::stressbalance::SSATestCase.
Definition at line 82 of file ssa_test_linear.cc.
References pism::Geometry::bed_elevation, exactSolution(), H0, pism::Geometry::ice_surface_elevation, pism::Geometry::ice_thickness, pism::stressbalance::SSATestCase::m_bc_mask, pism::stressbalance::SSATestCase::m_bc_values, pism::stressbalance::SSATestCase::m_config, pism::stressbalance::SSATestCase::m_geometry, pism::stressbalance::SSATestCase::m_grid, pism::stressbalance::SSATestCase::m_ssa, pism::stressbalance::SSATestCase::m_tauc, nu0, pism::array::Array::set(), pism::stressbalance::SSAStrengthExtension::set_min_thickness(), pism::stressbalance::SSAStrengthExtension::set_notional_strength(), pism::stressbalance::SSA::strength_extension, tauc0, and pism::array::Array::update_ghosts().