PISM, A Parallel Ice Sheet Model: pism::RegionalGeometryEvolution::compute_interface_fluxes
compute_interface_fluxes
compute_surface_and_basal_mass_balance
m_no_model_mask
RegionalGeometryEvolution
set_no_model_mask_impl
compute_interface_fluxes()
void pism::RegionalGeometryEvolution::compute_interface_fluxes (const array::CellType1 & cell_type, const array::Scalar & ice_thickness, const array::Vector & velocity, const array::Staggered & diffusive_flux, array::Staggered & output) protected virtual
Disable ice flow in "no model" areas.
Reimplemented from pism::GeometryEvolution.
Definition at line 1145 of file GeometryEvolution.cc.
References pism::array::Scalar::as_int(), pism::ParallelSection::check(), pism::GeometryEvolution::compute_interface_fluxes(), pism::ParallelSection::failed(), pism::Component::m_grid, m_no_model_mask, and n.