PISM, A Parallel Ice Sheet Model: pism::inverse::IP_L2NormFunctional2S::valueAt
dot
gradientAt
IP_L2NormFunctional2S
IP_L2NormFunctional2S
operator=
valueAt
~IP_L2NormFunctional2S
valueAt()
void pism::inverse::IP_L2NormFunctional2S::valueAt (IceModelVec2S & x, double * OUTPUT) virtual
Computes the value of the functional at the vector x.
Implements pism::inverse::IPFunctional< IceModelVec2S >.
Definition at line 27 of file IP_L2NormFunctional.cc.
References pism::IceModelVec2S::array(), pism::fem::Element2::evaluate(), pism::GlobalSum(), pism::fem::ElementIterator::lxm, pism::fem::ElementIterator::lxs, pism::fem::ElementIterator::lym, pism::fem::ElementIterator::lys, pism::inverse::IPFunctional< IceModelVec2S >::m_element, pism::inverse::IPFunctional< IceModelVec2S >::m_element_index, pism::inverse::IPFunctional< IceModelVec2S >::m_grid, pism::fem::MAX_QUADRATURE_SIZE, pism::fem::q1::n_chi, pism::fem::Element::n_pts(), pism::fem::Element2::nodal_values(), pism::fem::Element2::reset(), and pism::fem::Element::weight().