PISM, A Parallel Ice Sheet Model: pism::Diagnostic::wrap
allocate
compute
compute_impl
define
define_impl
define_state
define_state_impl
Diagnostic
init
init_impl
m_config
m_fill_value
m_grid
m_sys
m_vars
metadata
n_variables
Ptr
reset
reset_impl
to_external
to_internal
update
update_impl
wrap
write_state
write_state_impl
~Diagnostic
wrap()
template<typename T > Diagnostic::Ptr pism::Diagnostic::wrap (const T & input) static
Definition at line 160 of file Diagnostic.hh.
Referenced by pism::hydrology::EmptyingProblem::diagnostics(), pism::Isochrones::diagnostics_impl(), pism::MohrCoulombYieldStress::diagnostics_impl(), pism::OptTillphiYieldStress::diagnostics_impl(), pism::YieldStress::diagnostics_impl(), pism::ocean::Pico::diagnostics_impl(), pism::surface::DEBMSimple::diagnostics_impl(), pism::surface::TemperatureIndex::diagnostics_impl(), pism::bed::BedDef::diagnostics_impl(), pism::bed::LingleClark::diagnostics_impl(), pism::energy::BedThermalUnit::diagnostics_impl(), pism::energy::CHSystem::diagnostics_impl(), pism::energy::EnergyModel::diagnostics_impl(), pism::FractureDensity::diagnostics_impl(), pism::calving::CalvingAtThickness::diagnostics_impl(), pism::calving::EigenCalving::diagnostics_impl(), pism::calving::HayhurstCalving::diagnostics_impl(), pism::calving::vonMisesCalving::diagnostics_impl(), pism::hydrology::Hydrology::diagnostics_impl(), and pism::RegionalYieldStress::diagnostics_impl().