PISM, A Parallel Ice Sheet Model: pism::fem::Element::n_pts
add_contribution
chi
Element
Element
Element
evaluate
initialize
m_block_size
m_col
m_germs
m_grid
m_i
m_i_offset
m_invalid_dof
m_j
m_j_offset
m_n_chi
m_Nq
m_row
m_weights
mark_col_invalid
mark_row_invalid
n_chi
n_pts
ShapeFunction
weight
~Element
n_pts()
int pism::fem::Element::n_pts () const inline
Number of quadrature points.
Definition at line 80 of file Element.hh.
References m_Nq.
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_H1NormFunctional2S::assemble_form(), pism::inverse::IPGroundedIceH1NormFunctional2S::assemble_form(), pism::stressbalance::Blatter::compute_jacobian(), pism::stressbalance::SSAFEM::compute_local_function(), pism::stressbalance::SSAFEM::compute_local_jacobian(), pism::stressbalance::Blatter::compute_residual(), pism::inverse::IP_H1NormFunctional2S::dot(), pism::inverse::IPGroundedIceH1NormFunctional2S::dot(), pism::inverse::IP_L2NormFunctional2S::dot(), pism::inverse::IP_L2NormFunctional2V::dot(), pism::stressbalance::SSAFEM::driving_stress(), pism::stressbalance::SSAFEM::explicit_driving_stress(), pism::inverse::IP_H1NormFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2S::gradientAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::gradientAt(), pism::inverse::IPTotalVariationFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2V::gradientAt(), pism::stressbalance::Blatter::jacobian_f(), pism::stressbalance::SSAFEM::quad_point_values(), pism::stressbalance::Blatter::residual_f(), pism::stressbalance::Blatter::residual_source_term(), pism::stressbalance::BlatterTestCFBC::residual_source_term(), pism::stressbalance::BlatterTestHalfar::residual_source_term(), pism::stressbalance::BlatterTestXY::residual_source_term(), pism::stressbalance::BlatterTestXZ::residual_source_term(), pism::inverse::IP_H1NormFunctional2S::valueAt(), pism::inverse::IP_L2NormFunctional2S::valueAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::valueAt(), pism::inverse::IPTotalVariationFunctional2S::valueAt(), and pism::inverse::IP_L2NormFunctional2V::valueAt().