PISM, A Parallel Ice Sheet Model: pism::stressbalance::StressBalance::modifier
advective_velocity
basal_frictional_heating
compute_vertical_velocity
compute_volumetric_strain_heating
define_model_state_impl
diagnostics_impl
diffusive_flux
init
m_cfl_2d
m_cfl_3d
m_modifier
m_shallow_stress_balance
m_strain_heating
m_w
max_diffusivity
max_timestep_cfl_2d
max_timestep_cfl_3d
modifier
shallow
stdout_report
StressBalance
ts_diagnostics_impl
update
velocity_u
velocity_v
velocity_w
volumetric_strain_heating
write_model_state_impl
~StressBalance
modifier()
const SSB_Modifier * pism::stressbalance::StressBalance::modifier () const
Returns a pointer to a stress balance modifier implementation.
Definition at line 653 of file StressBalance.cc.
References m_modifier.
Referenced by pism::diagnostics::HardnessAverage::compute_impl(), pism::diagnostics::IceHardness::compute_impl(), and pism::diagnostics::IceViscosity::compute_impl().