PISM, A Parallel Ice Sheet Model: pism::fem::DirichletData_Vector::fix_residual
DirichletData_Vector
enforce
enforce_homogeneous
fix_jacobian
fix_residual
fix_residual_homogeneous
m_values
~DirichletData_Vector
fix_residual()
void pism::fem::DirichletData_Vector::fix_residual (Vector2 const *const *const x_global, Vector2 ** r_global)
Definition at line 218 of file DirichletData.cc.
References pism::IceModelVec::grid(), pism::fem::DirichletData::m_indices, m_values, pism::fem::DirichletData::m_weight, and pism::PointsWithGhosts::next().
Referenced by pism::stressbalance::SSAFEM::compute_local_function().