PISM, A Parallel Ice Sheet Model: pism::petsc::VecArray::get
get
m_array
m_v
VecArray
~VecArray
get()
double * pism::petsc::VecArray::get ()
Definition at line 54 of file Vec.cc.
References m_array.
Referenced by pism::ocean::PicoGeometry::compute_continental_shelf_mask(), pism::ocean::PicoGeometry::compute_lakes(), pism::convert_vec(), pism::IceModelVec::fletcher64(), pism::IceModelVec::fletcher64_serial(), pism::IceModelVec2T::init_periodic_data(), pism::label_components(), pism::ocean::PicoGeometry::label_tmp(), pism::IceModelVec::read_impl(), pism::IceModelVec::regrid_impl(), pism::IceModelVec2T::update(), pism::calving::IcebergRemover::update_impl(), pism::calving::IcebergRemoverFEM::update_impl(), and pism::IceModelVec::write_impl().