PISM, A Parallel Ice Sheet Model: pism::ocean::InitializationHelper::init_impl
average_water_column_pressure_impl
define_model_state_impl
init_impl
InitializationHelper
m_shelf_base_mass_flux
m_shelf_base_temperature
shelf_base_mass_flux_impl
shelf_base_temperature_impl
update_impl
write_model_state_impl
init_impl()
void pism::ocean::InitializationHelper::init_impl (const Geometry & geometry) private virtual
Reimplemented from pism::ocean::OceanModel.
Definition at line 58 of file Initialization.cc.
References pism::File::close(), pism::InputOptions::filename, pism::INIT_RESTART, pism::init_step(), pism::Component::m_config, pism::Component::m_grid, pism::ocean::OceanModel::m_input_model, pism::Component::m_log, m_shelf_base_mass_flux, m_shelf_base_temperature, pism::ocean::OceanModel::m_water_column_pressure, pism::File::nrecords(), pism::PISM_GUESS, pism::PISM_READONLY, pism::process_input_options(), pism::Component::regrid(), pism::Component::REGRID_WITHOUT_REGRID_VARS, and pism::InputOptions::type.