PISM, A Parallel Ice Sheet Model: pism::hydrology::SteadyState::init_time
bootstrap_impl
define_model_state_impl
diagnostics_impl
init_impl
init_time
initialization_message
m_bootstrap
m_emptying_problem
m_t_eps
m_t_last
m_time
m_time_bounds
m_time_name
m_update_interval
max_timestep_impl
restart_impl
SteadyState
update_impl
write_model_state_impl
~SteadyState
init_time()
void pism::hydrology::SteadyState::init_time (const std::string & input_file) protected
Read time bounds corresponding to the water input rate in the forcing file.
These times are used to compute the maximum time step the model can take while still capturing temporal variability of the forcing.
Definition at line 283 of file SteadyState.cc.
References pism::RuntimeError::formatted(), pism::is_increasing(), pism::k, pism::Component::m_grid, pism::Component::m_log, m_time, m_time_bounds, PISM_ERROR_LOCATION, pism::io::PISM_GUESS, pism::io::PISM_READONLY, pism::File::read_text_attribute(), pism::io::read_time_bounds(), pism::Component::time(), pism::io::time_dimension(), and pism::Time::units_string().
Referenced by bootstrap_impl(), and restart_impl().