PISM, A Parallel Ice Sheet Model: pism::TSDiagnostic::compute
compute
define
flush
init
m_bounds
m_buffer_size
m_config
m_current_time
m_dimension
m_grid
m_output_filename
m_requested_times
m_start
m_sys
m_time
m_time_bounds
m_time_name
m_values
m_variable
metadata
Ptr
set_units
TSDiagnostic
update
update_impl
~TSDiagnostic
compute()
virtual double pism::TSDiagnostic::compute () protected pure virtual
Compute the diagnostic. Regular (snapshot) quantity should be computed here; for rates of change, compute() should return the total change during the time step from t0 to t1. The rate itself is computed in evaluate_rate().
Implemented in pism::diagnostics::scalar::IceMassFluxAtGroundingLine, pism::diagnostics::scalar::IceMassFluxCalving, pism::diagnostics::scalar::IceMassFluxDischarge, pism::diagnostics::scalar::IceMassFluxConservationError, pism::diagnostics::scalar::IceMassFluxBasalFloating, pism::diagnostics::scalar::IceMassFluxBasalGrounded, pism::diagnostics::scalar::IceMassFluxSurface, pism::diagnostics::scalar::IceMassFluxBasal, pism::diagnostics::scalar::MaxHorizontalVelocity, pism::diagnostics::scalar::MaxDiffusivity, pism::diagnostics::scalar::TimeStepLength, pism::diagnostics::scalar::IceVolumeGlacierizedShelf, pism::diagnostics::scalar::IceVolumeGlacierizedGrounded, pism::diagnostics::scalar::IceAreaGlacierizedShelf, pism::diagnostics::scalar::IceAreaGlacierizedGrounded, pism::diagnostics::scalar::IceEnthalpy, pism::diagnostics::scalar::IceEnthalpyGlacierized, pism::diagnostics::scalar::IceAreaGlacierizedColdBase, pism::diagnostics::scalar::IceAreaGlacierizedTemperateBase, pism::diagnostics::scalar::IceVolumeCold, pism::diagnostics::scalar::IceVolumeGlacierizedCold, pism::diagnostics::scalar::IceVolumeTemperate, pism::diagnostics::scalar::IceVolumeGlacierizedTemperate, pism::diagnostics::scalar::IceMassRateOfChange, pism::diagnostics::scalar::IceMassRateOfChangeDueToFlow, pism::diagnostics::scalar::IceMassRateOfChangeGlacierized, pism::diagnostics::scalar::IceMass, pism::diagnostics::scalar::IceMassGlacierized, pism::diagnostics::scalar::IceMassNotDisplacingSeaWater, pism::diagnostics::scalar::IceAreaGlacierized, pism::diagnostics::scalar::IceVolumeRateOfChange, pism::diagnostics::scalar::IceVolumeRateOfChangeGlacierized, pism::diagnostics::scalar::SeaLevelRisePotential, pism::diagnostics::scalar::IceVolume, pism::diagnostics::scalar::IceVolumeGlacierized, pism::energy::LiquifiedIceFlux, pism::surface::diagnostics::TotalSurfaceRunoff, pism::surface::diagnostics::TotalSurfaceMelt, and pism::surface::diagnostics::TotalSurfaceAccumulation.
Referenced by pism::TSSnapshotDiagnostic::update_impl(), pism::TSRateDiagnostic::update_impl(), and pism::TSFluxDiagnostic::update_impl().