PISM, A Parallel Ice Sheet Model: pism::EnthalpyConverter::melting_temperature
c
enthalpy
enthalpy_cold
enthalpy_cts
enthalpy_liquid
enthalpy_permissive
EnthalpyConverter
is_temperate
is_temperate_relaxed
L
m_beta
m_c_i
m_c_w
m_do_cold_ice_methods
m_g
m_L
m_p_air
m_rho_i
m_T_0
m_T_melting
m_T_tolerance
melting_temperature
pressure
pressure
pressure_adjusted_temperature
Ptr
temperature
temperature_cold
validate_E_P
validate_T_omega_P
water_fraction
~EnthalpyConverter
melting_temperature()
double pism::EnthalpyConverter::melting_temperature (double P) const
Get melting temperature from pressure p.
\[ T_m(p) = T_{melting} - \beta p. \]
Definition at line 154 of file EnthalpyConverter.cc.
References m_beta, and m_T_melting.
Referenced by enthalpy(), enthalpy_cts(), enthalpy_liquid(), enthalpy_permissive(), pressure_adjusted_temperature(), temperature(), validate_T_omega_P(), and water_fraction().