PISM, A Parallel Ice Sheet Model: pism::Component::time
Component
define_model_state
define_model_state_impl
diagnostics
diagnostics_impl
grid
m_config
m_grid
m_log
m_sys
max_timestep
max_timestep_impl
profiling
regrid
RegriddingFlag
time
ts_diagnostics
ts_diagnostics_impl
write_model_state
write_model_state_impl
~Component
time()
const Time & pism::Component::time () const
Definition at line 109 of file Component.cc.
References m_grid.
Referenced by pism::surface::ForceThickness::adjust_mass_flux(), pism::energy::BTU_Verification::bootstrap(), pism::Isochrones::bootstrap(), pism::bed::LingleClark::bootstrap_impl(), pism::hydrology::SteadyState::bootstrap_impl(), pism::ocean::Cache::Cache(), pism::surface::Cache::Cache(), pism::stressbalance::SIAFD::compute_diffusivity(), pism::surface::DEBMSimple::compute_next_balance_year_start(), pism::surface::TemperatureIndex::compute_next_balance_year_start(), pism::OptTillphiYieldStress::define_model_state_impl(), pism::bed::LingleClark::define_model_state_impl(), pism::hydrology::SteadyState::define_model_state_impl(), pism::MohrCoulombYieldStress::finish_initialization(), pism::atmosphere::Given::init_impl(), pism::ocean::Cache::init_impl(), pism::ocean::Given::init_impl(), pism::ocean::GivenTH::init_impl(), pism::ocean::InitializationHelper::init_impl(), pism::ocean::Pico::init_impl(), pism::ocean::sea_level::InitializationHelper::init_impl(), pism::surface::Cache::init_impl(), pism::surface::DEBMSimple::init_impl(), pism::surface::Given::init_impl(), pism::surface::InitializationHelper::init_impl(), pism::surface::TemperatureIndex::init_impl(), pism::surface::Verification::init_impl(), pism::bed::LingleClark::init_impl(), pism::OptTillphiYieldStress::init_t_last(), pism::hydrology::SteadyState::init_time(), pism::atmosphere::YearlyCycle::init_timeseries_impl(), pism::Isochrones::initialize(), pism::energy::TemperatureModel_Verification::initTestFG(), pism::energy::TemperatureModel_Verification::initTestsKO(), pism::diagnostics::IsochroneDepths::IsochroneDepths(), pism::Isochrones::Isochrones(), pism::bed::LingleClark::LingleClark(), pism::ocean::Cache::max_timestep_impl(), pism::surface::Cache::max_timestep_impl(), pism::OptTillphiYieldStress::OptTillphiYieldStress(), pism::hydrology::SteadyState::restart_impl(), pism::hydrology::SteadyState::SteadyState(), pism::Isochrones::update(), pism::surface::Verification::update_ABCDH(), pism::surface::Verification::update_FG(), pism::ocean::Cache::update_impl(), pism::surface::Cache::update_impl(), pism::surface::DEBMSimple::update_impl(), and pism::surface::TemperatureIndex::update_impl().