PISM, A Parallel Ice Sheet Model: pism::RuntimeError::formatted
add_context
add_context
formatted
Hook
m_context
m_location
print
RuntimeError
set_hook
sm_hook
~RuntimeError
formatted()
RuntimeError pism::RuntimeError::formatted (const ErrorLocation & location, const char format[], ...) static
build a RuntimeError with a formatted message
Definition at line 47 of file error_handling.cc.
References RuntimeError().
Referenced by pism::surface::SurfaceModel::accumulation_impl(), pism::Vars::add(), pism::Vars::add_shared(), pism::atmosphere::AtmosphereModel::air_temperature_impl(), pism::IceModel::allocate_age_model(), pism::IceModel::allocate_basal_yield_stress(), pism::IceModel::allocate_isochrones(), pism::details::allocate_layer_thickness(), pism::IceModel::allocate_subglacial_hydrology(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization_transpose(), pism::GeometryEvolution::apply_mass_fluxes(), pism::stressbalance::SSAFD::assemble_matrix(), pism::ScalarForcing::average(), pism::atmosphere::AtmosphereModel::begin_pointwise_access_impl(), pism::energy::BTU_Verification::bootstrap(), pism::Isochrones::bootstrap(), pism::IceEISModel::bootstrap_2d(), pism::IceModel::bootstrap_2d(), pism::energy::bootstrap_ice_temperature(), pism::hydrology::Distributed::bootstrap_impl(), pism::energy::BTU_Full::BTU_Full(), pism::ocean::Cache::Cache(), pism::surface::Cache::Cache(), pism::calendar_from_file(), pism::array::Array::check_array_indices(), pism::hydrology::check_bounds(), pism::check_c_call(), pism::check_consistency_epsg(), pism::check_forcing_duration(), pism::io::check_grid_overlap(), pism::check_input(), pism::energy::check_input(), pism::io::check_input_grid(), pism::hydrology::Distributed::check_P_bounds(), pism::VariableMetadata::check_range(), pism::array::Array::checkCompatibility(), pism::stressbalance::SIAFD::compute_diffusivity(), pism::diagnostics::TemperateIceThicknessBasal::compute_impl(), pism::compute_nprocs(), pism::compute_ownership_ranges(), pism::stressbalance::SIAFD::compute_surface_gradient(), pism::Time::compute_times_simple(), pism::rheology::FlowLawFactory::create(), pism::stressbalance::create(), pism::create_backend(), pism::DataAccess< T >::DataAccess(), pism::units::Unit::date(), pism::surface::DEBMSimple::DEBMSimple(), pism::details::deposition_times(), pism::options::deprecated(), pism::surface::details::distance_factor_paleo(), pism::Profiling::end(), pism::atmosphere::AtmosphereModel::end_pointwise_access_impl(), pism::Geometry::ensure_consistency(), pism::epsg_to_cf(), pism::File::File(), pism::File::find_variable(), pism::options::forbidden(), pism::ForcingOptions::ForcingOptions(), pism::Grid::FromFile(), pism::Grid::FromOptions(), pism::GeometryCalculator::GeometryCalculator(), pism::Vars::get(), pism::Vars::get_2d_cell_type(), pism::Vars::get_2d_cell_type_shared(), pism::Vars::get_2d_mask(), pism::Vars::get_2d_mask_shared(), pism::Vars::get_2d_scalar(), pism::Vars::get_2d_scalar_shared(), pism::Vars::get_2d_vector(), pism::Vars::get_2d_vector_shared(), pism::Vars::get_3d_scalar(), pism::Vars::get_3d_scalar_shared(), pism::get_all_values(), pism::array::Array::get_dof(), pism::NetCDFConfig::get_flag_impl(), pism::VariableMetadata::get_number(), pism::NetCDFConfig::get_number_impl(), pism::NetCDFConfig::get_numbers_impl(), pism::ConfigJSON::get_numbers_impl(), pism::Vars::get_shared(), pism::NetCDFConfig::get_string_impl(), pism::get_value(), pism::io::NCFile::get_vara_double(), pism::io::NCFile::get_varm_double(), pism::io::ParallelIO::get_varm_double_impl(), pism::grounded_area_fraction(), pism::LonLatCalculator::Impl::Impl(), pism::units::System::Impl::Impl(), pism::units::Unit::Impl::Impl(), pism::units::Converter::Impl::Impl(), pism::Config::import_from(), pism::increment_date(), pism::calving::EigenCalving::init(), pism::calving::HayhurstCalving::init(), pism::calving::vonMisesCalving::init(), pism::Time::init_calendar(), pism::IceModel::init_calving(), pism::columnSystemCtx::init_column(), pism::energy::EnergyModel::init_enthalpy(), pism::ConfigJSON::init_from_file(), pism::ConfigJSON::init_from_string(), pism::IceModel::init_frontal_melt(), pism::surface::TemperatureIndex::init_impl(), pism::OptTillphiYieldStress::init_impl(), pism::hydrology::SteadyState::init_time(), pism::atmosphere::AtmosphereModel::init_timeseries_impl(), pism::ScalarForcing::initialize(), pism::grid::InputGridInfo::InputGridInfo(), pism::array::int_to_normtype(), pism::options::IntegerList::IntegerList(), pism::array::Array3D::interpolate(), pism::Grid::kBelowHeight(), pism::options::Keyword::Keyword(), pism::limit_advective_flux(), pism::limit_diffusive_flux(), pism::bed::LingleClark::LingleClark(), pism::bed::LingleClarkSerial::LingleClarkSerial(), pism::diagnostics::scalar::mass_change(), pism::surface::SurfaceModel::mass_flux_impl(), pism::Isochrones::max_timestep_cfl(), pism::AgeModel::max_timestep_impl(), pism::OptTillphiYieldStress::max_timestep_impl(), pism::frontalmelt::FrontalMelt::max_timestep_impl(), pism::ocean::OceanModel::max_timestep_impl(), pism::bed::LingleClark::max_timestep_impl(), pism::energy::EnergyModel::max_timestep_impl(), pism::hydrology::SteadyState::max_timestep_impl(), pism::surface::SurfaceModel::melt_impl(), pism::Diagnostic::metadata(), pism::IceModel::misc_setup(), pism::PCFactory< Model >::model(), pism::DiagAverageRate< M >::model_input(), pism::PCFactory< Model >::modifier(), pism::MohrCoulombYieldStress::MohrCoulombYieldStress(), pism::io::move_if_exists(), pism::array::Array::norm(), pism::File::open(), pism::ConstAttribute::operator double(), pism::pack_json_array(), pism::io::ParallelIO::ParallelIO(), pism::parse_date(), pism::parse_integer(), pism::Time::parse_interval_length(), pism::parse_number(), pism::Time::parse_range(), pism::atmosphere::PIK::PIK(), pism::Grid::pio_io_decomposition(), pism::Context::pio_iosys_id(), pism::atmosphere::AtmosphereModel::precip_time_series_impl(), pism::atmosphere::AtmosphereModel::precipitation_impl(), pism::options::String::process(), pism::process_extra_shortcuts(), pism::Proj::Proj(), pism::IceModel::prune_diagnostics(), pism::io::NCFile::put_vara_double(), pism::io::read_attributes(), pism::File::read_double_attribute(), pism::io::read_for_interpolation(), pism::io::read_spatial_variable(), pism::File::read_text_attribute(), pism::io::read_time_info(), pism::io::read_timeseries(), pism::reference_date_from_file(), pism::regional_grid_from_options(), pism::IceModel::regrid(), pism::array::Array::regrid_impl(), pism::ocean::relabel(), pism::io::remove_if_exists(), pism::hydrology::Routing::Routing(), pism::surface::SurfaceModel::runoff_impl(), pism::ScalarForcing::ScalarForcing(), pism::set_config_from_options(), pism::rheology::FlowLawFactory::set_default(), pism::array::set_default_value_or_stop(), pism::array::Array::set_dof(), pism::set_flag_from_option(), pism::GeometryCalculator::set_icefree_thickness(), pism::set_integer_list_from_option(), pism::array::Array::set_interpolation_type(), pism::stressbalance::SSAStrengthExtension::set_min_thickness(), pism::stressbalance::SSAStrengthExtension::set_notional_strength(), pism::set_number_list_from_option(), pism::set_parameter_from_options(), pism::VariableMetadata::set_string(), pism::set_value(), pism::ocean::OceanModel::shelf_base_mass_flux_impl(), pism::ocean::OceanModel::shelf_base_temperature_impl(), pism::stressbalance::SIAFD::SIAFD(), pism::stressbalance::BedSmoother::smoothed_thk(), pism::inverse::IP_SSATaucTikhonovGNSolver::solve(), pism::SNESProblem< DOF, U >::solve(), pism::Poisson::solve(), pism::stressbalance::SSAFEM::solve(), pism::TridiagonalSystem::solve(), pism::start_time(), pism::hydrology::SteadyState::SteadyState(), pism::IceModel::step(), pism::options::String::String(), pism::string_to_backend(), pism::grid::string_to_periodicity(), pism::grid::string_to_registration(), pism::grid::string_to_spacing(), pism::atmosphere::AtmosphereModel::temp_time_series_impl(), pism::surface::SurfaceModel::temperature_impl(), pism::stressbalance::BedSmoother::theta(), pism::units::Unit::time(), pism::Time::Time(), pism::unpack_json_array(), pism::hydrology::EmptyingProblem::update(), pism::array::Forcing::update(), pism::surface::Verification::update_ABCDH(), pism::energy::BTU_Full::update_impl(), pism::frontalmelt::FrontalMelt::update_impl(), pism::ocean::OceanModel::update_impl(), pism::surface::Verification::update_impl(), pism::energy::TemperatureModel::update_impl(), pism::hydrology::NullTransport::update_impl(), pism::GeometryEvolution::update_in_place(), pism::grid::Parameters::validate(), pism::PCFactory< Model >::validate(), pism::EnthalpyConverter::validate_E_P(), pism::validate_format_string(), pism::validate_range(), pism::EnthalpyConverter::validate_T_omega_P(), pism::array::Array::view(), pism::hydrology::wall_melt(), pism::warn_about_missing(), pism::io::ParallelIO::write_darray_impl(), pism::io::write_spatial_variable(), pism::io::write_time_bounds(), and pism::io::write_timeseries().