PISM, A Parallel Ice Sheet Model: pism::fem::Q1Element3Face::reset
chi
evaluate
m_chi
m_dx
m_dy
m_n_chi
m_normals
m_Nq
m_points
m_w
m_weights
n_pts
normal
Q1Element3Face
reset
weight
reset()
void pism::fem::Q1Element3Face::reset (int face, const double * z)
Definition at line 538 of file Element.cc.
References pism::fem::q13d::chi(), chi(), m_chi, m_dx, m_dy, m_n_chi, m_normals, m_Nq, m_points, m_w, m_weights, n, and pism::fem::QuadPoint::xi.
Referenced by pism::stressbalance::Blatter::compute_jacobian(), and pism::stressbalance::Blatter::compute_residual().