PISM, A Parallel Ice Sheet Model: pism::GeometryEvolution::top_surface_mass_balance
apply_flux_divergence
apply_mass_fluxes
area_specific_volume_change_due_to_flow
bottom_surface_mass_balance
compute_flux_divergence
compute_interface_fluxes
compute_surface_and_basal_mass_balance
conservation_error
diagnostics_impl
ensure_nonnegativity
flow_step
flux_divergence
flux_staggered
GeometryEvolution
init
init_impl
m_impl
reset
residual_redistribution_iteration
set_no_model_mask
set_no_model_mask_impl
source_term_step
thickness_change_due_to_flow
top_surface_mass_balance
update_in_place
~GeometryEvolution
top_surface_mass_balance()
const IceModelVec2S & pism::GeometryEvolution::top_surface_mass_balance () const
Definition at line 210 of file GeometryEvolution.cc.
References pism::GeometryEvolution::Impl::effective_SMB, and m_impl.
Referenced by apply_mass_fluxes(), pism::diagnostics::scalar::mass_change(), and pism::diagnostics::SurfaceFlux::update_impl().