PISM, A Parallel Ice Sheet Model: pism::ocean::PIK::mass_flux
init_impl
mass_flux
max_timestep_impl
melting_point_temperature
PIK
update_impl
~PIK
mass_flux()
void pism::ocean::PIK::mass_flux (const IceModelVec2S & ice_thickness, IceModelVec2S & result) const private
Computes mass flux in [kg m-2 s-1].
Assumes that mass flux is proportional to the shelf-base heat flux.
Definition at line 105 of file ConstantPIK.cc.
References pism::units::convert(), L, pism::Component::m_config, pism::Component::m_grid, pism::Component::m_sys, and pism::PointsWithGhosts::next().
Referenced by update_impl().