PISM, A Parallel Ice Sheet Model: pism::energy::BedThermalUnit::vertical_spacing
BedThermalUnit
ConstPtr
define_model_state_impl
depth
depth_impl
diagnostics_impl
flux_through_bottom_surface
flux_through_top_surface
FromOptions
init
init_impl
initialize_bottom_surface_flux
m_bottom_surface_flux
m_top_surface_flux
Mz
Mz_impl
Ptr
update
update_impl
vertical_spacing
vertical_spacing_impl
write_model_state_impl
~BedThermalUnit
vertical_spacing()
double pism::energy::BedThermalUnit::vertical_spacing () const
Returns the vertical spacing used by the bedrock grid.
Definition at line 164 of file BedThermalUnit.cc.
References vertical_spacing_impl().
Referenced by pism::energy::BTU_Full::bootstrap(), pism::energy::BTU_Full::BTU_Full(), and pism::energy::BTU_Full::update_flux_through_top_surface().