PISM, A Parallel Ice Sheet Model: pism::bed::Given::Given
Given
init_impl
m_topg_delta
m_topg_reference
update_impl
~Given
Given()
pism::bed::Given::Given (std::shared_ptr< const Grid > grid)
Definition at line 26 of file Given.cc.
References pism::LINEAR, pism::VariableMetadata::long_name(), pism::Component::m_config, pism::Component::m_grid, m_topg_delta, m_topg_reference, pism::array::Array::metadata(), pism::io::PISM_NETCDF3, pism::io::PISM_READONLY, pism::VariableMetadata::standard_name(), and pism::VariableMetadata::units().