PISM, A Parallel Ice Sheet Model: pism::energy::TemperatureModel::restart_impl
bootstrap_impl
column_drainage
define_model_state_impl
initialize_impl
m_ice_temperature
restart_impl
temperature
TemperatureModel
update_impl
update_impl
write_model_state_impl
restart_impl()
void pism::energy::TemperatureModel::restart_impl (const File & input_file, int record) protected virtual
Implements pism::energy::EnergyModel.
Definition at line 48 of file TemperatureModel.cc.
References pism::energy::compute_enthalpy_cold(), pism::energy::compute_temperature(), pism::File::filename(), pism::File::find_variable(), pism::VariableMetadata::get_name(), pism::energy::EnergyModel::init_enthalpy(), pism::energy::EnergyModel::m_basal_melt_rate, pism::Component::m_grid, pism::energy::EnergyModel::m_ice_enthalpy, m_ice_temperature, pism::Component::m_log, pism::array::Array::metadata(), pism::array::Array::read(), pism::Component::regrid(), and pism::Component::REGRID_WITHOUT_REGRID_VARS.