PISM, A Parallel Ice Sheet Model: pism::columnSystemCtx::reportColumnZeroPivotErrorMFile
coarse_to_fine
columnSystemCtx
dz
fine_to_coarse
init_column
init_fine_grid
ks
m_dt
m_dx
m_dy
m_dz
m_i
m_interp
m_j
m_ks
m_solver
m_u
m_u3
m_v
m_v3
m_w
m_w3
m_z
reportColumnZeroPivotErrorMFile
save_to_file
save_to_file
z
~columnSystemCtx
reportColumnZeroPivotErrorMFile()
void pism::columnSystemCtx::reportColumnZeroPivotErrorMFile (unsigned int M) protected
Write system matrix and right-hand-side into an Python script. The file name contains ZERO_PIVOT_ERROR.
Definition at line 344 of file ColumnSystem.cc.
References pism::TridiagonalSystem::ddratio(), m_i, m_j, m_solver, pism::TridiagonalSystem::norm1(), pism::TridiagonalSystem::prefix(), pism::printf(), and pism::TridiagonalSystem::save_system().
Referenced by pism::energy::enthSystemCtx::solve(), pism::AgeColumnSystem::solve(), and pism::energy::tempSystemCtx::solveThisColumn().