PISM, A Parallel Ice Sheet Model: pism::IceRegionalModel::model_state_setup
allocate_basal_yield_stress
allocate_energy_model
allocate_geometry_evolution
allocate_storage
allocate_stressbalance
bootstrap_2d
cryo_hydrologic_system
energy_model_inputs
energy_step
hydrology_step
IceRegionalModel
init_diagnostics
m_ch_system
m_ch_warming_flux
m_no_model_mask
m_thk_stored
m_usurf_stored
model_state_setup
stress_balance_inputs
yield_stress_inputs
model_state_setup()
void pism::IceRegionalModel::model_state_setup () protected virtual
Sets the starting values of model state variables.
There are two cases:
1) Initializing from a PISM output file.
2) Setting the values using command-line options only (verification and simplified geometry runs, for example) or from a bootstrapping file, using heuristics to fill in missing and 3D fields.
Calls IceModel::regrid().
This function is called after all the memory allocation is done and all the physical parameters are set.
Calling this method should be all one needs to set model state variables. Please avoid modifying them in other parts of the initialization sequence.
Also, please avoid operations that would make it unsafe to call this more than once (memory allocation is one example).
Reimplemented from pism::IceModel.
Definition at line 93 of file IceRegionalModel.cc.
References pism::IceModelVec2S::copy_from(), pism::InputOptions::filename, pism::energy::BedThermalUnit::flux_through_top_surface(), pism::Geometry::ice_surface_elevation, pism::Geometry::ice_thickness, pism::INIT_BOOTSTRAP, pism::INIT_OTHER, pism::INIT_RESTART, pism::IceModel::m_basal_melt_rate, pism::IceModel::m_btu, m_ch_system, pism::IceModel::m_config, pism::IceModel::m_ctx, pism::IceModel::m_geometry, pism::IceModel::m_geometry_evolution, pism::IceModel::m_grid, m_no_model_mask, pism::IceModel::m_surface, m_thk_stored, m_usurf_stored, pism::IceModel::model_state_setup(), pism::PISM_GUESS, pism::PISM_READONLY, pism::process_input_options(), pism::InputOptions::record, pism::IceModelVec::set(), and pism::InputOptions::type.