PISM, A Parallel Ice Sheet Model: pism::hydrology::Distributed::update_P
bootstrap_impl
check_P_bounds
define_model_state_impl
Distributed
init_impl
initialization_message
m_P
m_Pnew
max_timestep_P_diff
P_from_W_steady
restart_impl
subglacial_water_pressure
ts_diagnostics_impl
update_impl
update_P
write_model_state_impl
~Distributed
update_P()
void pism::hydrology::Distributed::update_P (double dt, const IceModelVec2CellType & cell_type, const IceModelVec2S & sliding_speed, const IceModelVec2S & surface_input_rate, const IceModelVec2S & basal_melt_rate, const IceModelVec2S & P_overburden, const IceModelVec2S & Wtill, const IceModelVec2S & Wtill_new, const IceModelVec2S & P, const IceModelVec2S & W, const IceModelVec2Stag & Ws, const IceModelVec2Stag & K, const IceModelVec2Stag & Q, IceModelVec2S & P_new) const protected
Definition at line 221 of file Distributed.cc.
References pism::c1, pism::c2, pism::clip(), pism::IceModelVec2CellType::ice_free_land(), pism::hydrology::K(), pism::k, pism::Component::m_config, pism::hydrology::Routing::m_dx, pism::hydrology::Routing::m_dy, pism::Component::m_grid, pism::hydrology::Routing::m_rg, pism::max(), n, pism::PointsWithGhosts::next(), pism::IceModelVec2CellType::ocean(), pism::IceModelVec2S::star(), pism::IceModelVec2Stag::star(), pism::hydrology::Hydrology::surface_input_rate(), and pism::Wr.
Referenced by update_impl().