PISM, A Parallel Ice Sheet Model: pism::rheology::FlowLawFactory::create
add
create
FlowLawFactory
m_config
m_EC
m_flow_laws
m_prefix
m_type_name
remove
set_default
~FlowLawFactory
create()
std::shared_ptr< FlowLaw > pism::rheology::FlowLawFactory::create ()
Definition at line 114 of file FlowLawFactory.cc.
References pism::RuntimeError::formatted(), m_config, m_EC, m_flow_laws, m_prefix, m_type_name, and PISM_ERROR_LOCATION.
Referenced by pism::stressbalance::Blatter::Blatter(), pism::stressbalance::BlatterMod::BlatterMod(), pism::stressbalance::PSB_vonmises_stress::compute_impl(), pism::stressbalance::ConstantInColumn::ConstantInColumn(), pism::stressbalance::SIAFD::SIAFD(), pism::stressbalance::SSA::SSA(), pism::calving::vonMisesCalving::vonMisesCalving(), pism::stressbalance::WeertmanSliding::WeertmanSliding(), and pism::stressbalance::ZeroSliding::ZeroSliding().