PISM, A Parallel Ice Sheet Model: pism::inverse::IPMeanSquareFunctional2S::valueAt
dot
gradientAt
IPMeanSquareFunctional2S
IPMeanSquareFunctional2S
m_normalization
m_weights
normalize
operator=
valueAt
~IPMeanSquareFunctional2S
valueAt()
void pism::inverse::IPMeanSquareFunctional2S::valueAt (IceModelVec2S & x, double * OUTPUT) virtual
Computes the value of the functional at the vector x.
Implements pism::inverse::IPFunctional< IceModelVec2S >.
Definition at line 165 of file IPMeanSquareFunctional.cc.
References pism::AccessList::add(), pism::GlobalSum(), pism::inverse::IPFunctional< IceModelVec2S >::m_grid, m_normalization, m_weights, and pism::PointsWithGhosts::next().