PISM, A Parallel Ice Sheet Model: pism::atmosphere::AtmosphereModel::init_timeseries_impl
allocate_precipitation
allocate_temperature
AtmosphereModel
AtmosphereModel
begin_pointwise_access
begin_pointwise_access_impl
define_model_state_impl
diagnostics_impl
end_pointwise_access
end_pointwise_access_impl
init
init_impl
init_timeseries
init_timeseries_impl
m_input_model
m_ts_times
max_timestep_impl
mean_annual_temp
mean_annual_temp_impl
mean_precipitation
mean_precipitation_impl
precip_time_series
precip_time_series_impl
temp_time_series
temp_time_series_impl
ts_diagnostics_impl
update
update_impl
write_model_state_impl
~AtmosphereModel
init_timeseries_impl()
void pism::atmosphere::AtmosphereModel::init_timeseries_impl (const std::vector< double > & ts) const protected virtual
Reimplemented in pism::atmosphere::YearlyCycle, pism::atmosphere::WeatherStation, pism::atmosphere::Uniform, pism::atmosphere::PrecipitationScaling, pism::atmosphere::Given, pism::atmosphere::Frac_P, pism::atmosphere::ElevationChange, pism::atmosphere::Delta_T, pism::atmosphere::Delta_P, pism::atmosphere::CosineYearlyCycle, and pism::atmosphere::Anomaly.
Definition at line 296 of file AtmosphereModel.cc.
References pism::RuntimeError::formatted(), m_input_model, m_ts_times, and PISM_ERROR_LOCATION.
Referenced by init_timeseries(), pism::atmosphere::Anomaly::init_timeseries_impl(), pism::atmosphere::Delta_P::init_timeseries_impl(), pism::atmosphere::Delta_T::init_timeseries_impl(), pism::atmosphere::ElevationChange::init_timeseries_impl(), pism::atmosphere::Frac_P::init_timeseries_impl(), and pism::atmosphere::PrecipitationScaling::init_timeseries_impl().