PISM, A Parallel Ice Sheet Model: pism::array::Array2D::copy_from
add
add
array
array
Array2D
box
copy_from
operator()
operator()
star
value_type
copy_from()
template<typename T > void pism::array::Array2D< T >::copy_from (const Array2D< T > & source) inline
Definition at line 73 of file Array2D.hh.
References pism::array::details::copy().
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization_transpose(), pism::bed::BedDef::bootstrap_impl(), pism::bed::PointwiseIsostasy::bootstrap_impl(), pism::bed::LingleClark::bootstrap_impl(), pism::energy::EnthalpyModel_Regional::bootstrap_impl(), pism::RegionalYieldStress::bootstrap_impl(), pism::stressbalance::SSAFEM::cache_inputs(), pism::ocean::PicoGeometry::compute_continental_shelf_mask(), pism::inverse::IP_SSATaucTikhonovGNSolver::compute_dlogalpha(), pism::ocean::PicoGeometry::compute_ice_rises(), pism::ocean::PicoGeometry::compute_ice_shelf_mask(), pism::stressbalance::SIAFD_thksmooth::compute_impl(), pism::stressbalance::SIAFD_diffusivity::compute_impl(), pism::stressbalance::PSB_strain_rates::compute_impl(), pism::stressbalance::PSB_deviatoric_stresses::compute_impl(), pism::ocean::PicoGeometry::compute_lakes(), pism::ocean::PicoGeometry::compute_ocean_mask(), pism::hydrology::EmptyingProblem::compute_potential(), pism::hydrology::Routing::compute_velocity(), pism::hydrology::NullTransport::diffuse_till_water(), pism::IceModel::enforce_consistency_of_geometry(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluate_objective_and_gradient(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::evaluateConstraints(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::evaluateConstraintsJacobianDesign(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::evaluateConstraintsJacobianState(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluateGNFunctional(), pism::GeometryEvolution::flow_step(), pism::IceModel::front_retreat_step(), pism::IceModel::hydrology_step(), pism::IceRegionalModel::hydrology_step(), pism::inverse::IP_SSAHardavForwardProblem::init(), pism::inverse::IP_SSATaucForwardProblem::init(), pism::stressbalance::SSAFEM::init_impl(), pism::hydrology::Distributed::init_impl(), pism::hydrology::Hydrology::init_impl(), pism::hydrology::Routing::init_impl(), pism::energy::BTU_Minimal::init_impl(), pism::bed::BedDef::init_impl(), pism::bed::LingleClark::init_impl(), pism::RegionalYieldStress::init_impl(), pism::FractureDensity::initialize(), pism::energy::EnthalpyModel::initialize_impl(), pism::energy::TemperatureModel::initialize_impl(), pism::energy::EnthalpyModel_Regional::initialize_impl(), pism::IceCompModel::initTestABCDH(), pism::IceCompModel::initTestL(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::IP_SSATaucTaoTikhonovProblemLCL(), pism::inverse::IP_SSATaucTikhonovGNSolver::linesearch(), main(), pism::surface::diagnostics::DEBMSInsolationMelt::model_input(), pism::surface::diagnostics::DEBMSTemperatureMelt::model_input(), pism::surface::diagnostics::DEBMSBackroundMelt::model_input(), pism::IceModel::model_state_setup(), pism::IceRegionalModel::model_state_setup(), pism::stressbalance::SSAFD::picard_iteration(), pism::stressbalance::SSAFD::picard_manager(), pism::stressbalance::SSAFD::picard_strategy_regularization(), pism::stressbalance::BedSmoother::preprocess_bed(), pism::diagnostics::ThicknessRateOfChange::reset_impl(), pism::GeometryEvolution::residual_redistribution_iteration(), pism::energy::EnthalpyModel_Regional::restart_impl(), pism::RegionalYieldStress::restart_impl(), pism::stressbalance::SSA::set_initial_guess(), pism::RegionalGeometryEvolution::set_no_model_mask_impl(), pism::MohrCoulombYieldStress::set_till_friction_angle(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::setInitialGuess(), pism::setInitStateF(), pism::Poisson::solve(), pism::stressbalance::SSAFD::solve(), pism::inverse::IP_SSATaucTikhonovGNSolver::solve_linearized(), pism::stressbalance::SSAFEM::solve_nocache(), pism::ocean::PicoGeometry::split_ice_shelves(), pism::IceModel::step(), pism::bed::LingleClark::step(), pism::calving::FloatKill::update(), pism::calving::EigenCalving::update(), pism::calving::vonMisesCalving::update(), pism::hydrology::EmptyingProblem::update(), pism::MPDATA2::update(), pism::UNO::update(), pism::FractureDensity::update(), pism::calving::CalvingAtThickness::update(), pism::energy::BTU_Full::update_flux_through_top_surface(), pism::FrontRetreat::update_geometry(), pism::bed::PointwiseIsostasy::update_impl(), pism::bed::Given::update_impl(), pism::atmosphere::ElevationChange::update_impl(), pism::ocean::sea_level::Delta_SL::update_impl(), pism::ocean::sea_level::InitializationHelper::update_impl(), pism::surface::InitializationHelper::update_impl(), pism::RegionalYieldStress::update_impl(), pism::hydrology::Distributed::update_impl(), pism::hydrology::Routing::update_impl(), pism::hydrology::SteadyState::update_impl(), pism::GeometryEvolution::update_in_place(), and pism::hydrology::wall_melt().