PISM, A Parallel Ice Sheet Model: pism::Grid::Ly
cell_area
com
compute_point_neighbors
ctx
dx
dy
dz_max
dz_min
FromFile
FromOptions
get_dm
get_mapping_info
Grid
Grid
interpolation_weights
kBelowHeight
Lx
Ly
Lz
m_impl
max_patch_size
Mx
My
Mz
operator=
periodicity
pio_io_decomposition
point_neighbors
points
rank
registration
report_parameters
set_mapping_info
Shallow
size
variables
variables
x
x
x0
xm
xs
y
y
y0
ym
ys
z
z
~Grid
Ly()
double pism::Grid::Ly () const
Half-width of the computational domain.
Definition at line 835 of file Grid.cc.
References pism::Grid::Impl::Ly, and m_impl.
Referenced by pism::Grid::Impl::compute_horizontal_coordinates(), pism::grid::Parameters::horizontal_extent_from_options(), pism::grid::Parameters::init_from_file(), pism::grid::InputGridInfo::InputGridInfo(), pism::grid::Parameters::Parameters(), pism::grid::InputGridInfo::report(), report_parameters(), pism::grid::InputGridInfo::reset(), Shallow(), and pism::grid::Parameters::validate().