PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSAFD::assemble_rhs
assemble_matrix
assemble_rhs
compute_hardav_staggered
compute_nuH_norm
compute_nuH_staggered
compute_nuH_staggered_cfbc
diagnostics_impl
fracture_induced_softening
init_impl
integrated_viscosity
is_marginal
m_A
m_b
m_default_pc_failure_count
m_default_pc_failure_max_count
m_hardness
m_KSP
m_nuH
m_nuH_old
m_nuh_viewer
m_nuh_viewer_size
m_scaling
m_velocity_old
m_view_nuh
m_work
pc_setup_asm
pc_setup_bjacobi
picard_iteration
picard_manager
picard_strategy_regularization
set_diagonal_matrix_entry
solve
SSAFD
update_nuH_viewers
write_system_petsc
~SSAFD
assemble_rhs()
void pism::stressbalance::SSAFD::assemble_rhs (const Inputs & inputs) protected virtual
Computes the right-hand side ("rhs") of the linear problem for the Picard iteration and finite-difference implementation of the SSA equations.
The right side of the SSA equations is just the driving stress term
\[ - \rho g H \nabla h. \]
The basal stress is put on the left side of the system. This method builds the discrete approximation of the right side. For more about the discretization of the SSA equations, see comments for assemble_matrix().
The values of the driving stress on the i,j grid come from a call to compute_driving_stress().
In the case of Dirichlet boundary conditions, the entries on the right-hand side come from known velocity values. The fields m_bc_values and m_bc_mask are used for this.
Definition at line 248 of file SSAFD.cc.
References pism::IceModelVec2< T >::add(), pism::IceModelVec2Int::as_int(), pism::average_water_column_pressure(), pism::stressbalance::Inputs::bc_mask, pism::stressbalance::Inputs::bc_values, pism::Geometry::bed_elevation, pism::stressbalance::SSA::compute_driving_stress(), pism::stressbalance::Inputs::geometry, pism::grid_edge(), pism::mask::grounded(), pism::mask::ice_free(), pism::mask::ice_free_land(), pism::mask::ice_free_ocean(), pism::Geometry::ice_surface_elevation, pism::Geometry::ice_thickness, is_marginal(), m_b, pism::Component::m_config, pism::Component::m_grid, pism::stressbalance::SSA::m_mask, m_scaling, pism::stressbalance::SSA::m_taud, pism::PointsWithGhosts::next(), pism::stressbalance::Inputs::no_model_mask, rho_ice, S(), pism::Geometry::sea_level_elevation, pism::IceModelVec::set(), pism::IceModelVec2Int::star(), pism::Vector2::u, pism::Vector2::v, and pism::stressbalance::Inputs::water_column_pressure.
Referenced by solve().