PISM, A Parallel Ice Sheet Model: pism::units::Unit::date
Converter
date
format
is_convertible
m_impl
operator=
reset
system
time
Unit
Unit
date()
DateTime pism::units::Unit::date (double T, const std::string & calendar) const
Definition at line 155 of file Units.cc.
References pism::calendar(), pism::units::DateTime::day, pism::RuntimeError::formatted(), pism::units::DateTime::hour, m_impl, pism::units::DateTime::minute, pism::units::DateTime::month, PISM_ERROR_LOCATION, pism::units::DateTime::second, utCalendar2_cal(), and pism::units::DateTime::year.
Referenced by pism::Time::calendar_year_start(), pism::Time::compute_times_monthly(), pism::Time::compute_times_yearly(), pism::Time::date(), pism::increment_date(), and pism::Time::year_fraction().