PISM, A Parallel Ice Sheet Model: pism::array::Array3D::get_column
Array3D
copy_from
duplicate
get_column
get_column
interpolate
regrid_impl
set_column
set_column
~Array3D
get_column() [1/2]
double * pism::array::Array3D::get_column (int i, int j)
Definition at line 120 of file Array3D.cc.
References pism::array::Array::check_array_indices(), and pism::array::Array::m_array.
Referenced by pism::details::allocate_layer_thickness(), pism::rheology::averaged_hardness_vec(), pism::details::base_area(), pism::energy::bootstrap_ice_temperature(), pism::stressbalance::SSAFEM::cache_inputs(), pism::columnSystemCtx::coarse_to_fine(), pism::stressbalance::PSB_wvel::compute(), pism::stressbalance::SIAFD::compute_3d_horizontal_velocity(), pism::energy::compute_cts(), pism::stressbalance::SIAFD::compute_diffusivity(), pism::energy::compute_enthalpy(), pism::energy::compute_enthalpy_cold(), pism::stressbalance::SSAFD::compute_hardav_staggered(), pism::stressbalance::SIAFD::compute_I(), pism::diagnostics::IsochroneDepths::compute_impl(), pism::diagnostics::HardnessAverage::compute_impl(), pism::diagnostics::IceHardness::compute_impl(), pism::diagnostics::IceViscosity::compute_impl(), pism::stressbalance::PSB_flux::compute_impl(), pism::stressbalance::PSB_vonmises_stress::compute_impl(), pism::energy::compute_liquid_water_fraction(), pism::IceModel::compute_original_ice_fraction(), pism::compute_strain_heating_errors(), pism::IceModel::compute_temperate_base_fraction(), pism::energy::compute_temperature(), pism::stressbalance::StressBalance::compute_vertical_velocity(), pism::stressbalance::StressBalance::compute_volumetric_strain_heating(), copy_from(), pism::count_CFL_violations(), pism::energy::cryo_hydrologic_warming_flux(), pism::enthalpy_from_temperature_cold(), pism::columnSystemCtx::fine_to_coarse(), pism::details::ice_volume(), interpolate(), pism::max_timestep_cfl_3d(), pism::details::renormalize(), pism::stressbalance::Blatter::set_initial_guess(), pism::array::sum_columns(), pism::energy::total_ice_enthalpy(), pism::stressbalance::BlatterMod::transfer(), pism::calving::vonMisesCalving::update(), pism::stressbalance::WeertmanSliding::update(), pism::AgeModel::update(), pism::energy::CHSystem::update_impl(), pism::energy::EnthalpyModel_Regional::update_impl(), and pism::stressbalance::zero_above_ice().