PISM, A Parallel Ice Sheet Model: pism::bed::LingleClark::step
bootstrap_impl
define_model_state_impl
diagnostics_impl
elastic_displacement
elastic_load_response_matrix
init_impl
LingleClark
m_elastic_displacement
m_elastic_displacement0
m_extended_grid
m_load_thickness
m_relief
m_serial_model
m_t_eps
m_t_last
m_time_name
m_total_displacement
m_update_interval
m_viscous_displacement
m_viscous_displacement0
m_work0
max_timestep_impl
relief
step
total_displacement
update_impl
viscous_displacement
write_model_state_impl
~LingleClark
step()
void pism::bed::LingleClark::step (const array::Scalar & ice_thickness, const array::Scalar & sea_level_elevation, double dt)
Finally, we need to update bed uplift and topg_last.
Definition at line 338 of file LingleClark.cc.
References pism::array::Array2D< T >::add(), pism::ParallelSection::check(), pism::bed::compute_load(), pism::bed::BedDef::compute_uplift(), pism::array::Array2D< T >::copy_from(), pism::ParallelSection::failed(), pism::array::Array::get_from_proc0(), pism::array::Array::inc_state_counter(), m_elastic_displacement, m_elastic_displacement0, pism::Component::m_grid, m_load_thickness, m_relief, m_serial_model, pism::bed::BedDef::m_topg, pism::bed::BedDef::m_topg_last, m_total_displacement, pism::bed::BedDef::m_uplift, m_viscous_displacement, m_viscous_displacement0, m_work0, PISM_CHK, and pism::array::Array::put_on_proc0().
Referenced by update_impl().