PISM, A Parallel Ice Sheet Model: pism::diagnostics::CalvingFlux::CalvingFlux
CalvingFlux
m_kind
update_impl
CalvingFlux()
pism::diagnostics::CalvingFlux::CalvingFlux (const IceModel * m, AmountKind kind) inline
Definition at line 450 of file flux_balance.hh.
References pism::DiagAverageRate< IceModel >::m_accumulator, pism::Diagnostic::m_config, pism::DiagAverageRate< IceModel >::m_factor, pism::Diagnostic::m_fill_value, pism::Diagnostic::m_sys, pism::Diagnostic::m_vars, pism::diagnostics::MASS, pism::IceModelVec::metadata(), pism::Diagnostic::set_attrs(), and pism::Diagnostic::to_internal().