PISM, A Parallel Ice Sheet Model: pism::units::Unit::format
Converter
date
format
is_convertible
m_impl
operator=
reset
system
time
Unit
Unit
format()
std::string pism::units::Unit::format () const
Definition at line 143 of file Units.cc.
References m_impl.
Referenced by pism::units::Converter::Impl::Impl(), pism::Time::init_from_file(), pism::io::read_time_bounds(), pism::start_time(), and pism::Time::units_string().