PISM, A Parallel Ice Sheet Model: pism::Config::get_number
all_doubles
all_doubles_impl
all_flags
all_flags_impl
all_strings
all_strings_impl
choices
Config
ConstPtr
doc
Doubles
filename
Flags
get_flag
get_flag_impl
get_number
get_number
get_number_impl
get_numbers
get_numbers
get_numbers_impl
get_string
get_string_impl
import_from
is_set
is_set_impl
keys
m_impl
option
parameters_set_by_user
parameters_used
Ptr
read
read
read_impl
set_flag
set_flag_impl
set_number
set_number_impl
set_numbers
set_numbers_impl
set_string
set_string_impl
Strings
type
units
UseFlag
write
write
write_impl
~Config
get_number() [2/2]
double pism::Config::get_number (const std::string & name, UseFlag flag = REMEMBER_THIS_USE) const
Definition at line 144 of file ConfigInterface.cc.
References get_number_impl(), m_impl, pism::Config::Impl::parameters_used, and REMEMBER_THIS_USE.
Referenced by pism::energy::BedrockColumn::BedrockColumn(), pism::ocean::GivenTH::Constants::Constants(), pism::energy::DrainageCalculator::DrainageCalculator(), pism::end_time(), pism::EnthalpyConverter::EnthalpyConverter(), pism::energy::enthSystemCtx::enthSystemCtx(), pism::rheology::FlowLaw::FlowLaw(), pism::frontalmelt::FrontalMeltPhysics::FrontalMeltPhysics(), pism::GeometryCalculator::GeometryCalculator(), get_number(), pism::rheology::GPBLD::GPBLD(), pism::rheology::Hooke::Hooke(), pism::IceBasalResistancePlasticLaw::IceBasalResistancePlasticLaw(), pism::IceBasalResistancePseudoPlasticLaw::IceBasalResistancePseudoPlasticLaw(), pism::IceBasalResistanceRegularizedLaw::IceBasalResistanceRegularizedLaw(), pism::rheology::IsothermalGlen::IsothermalGlen(), pism::bed::LingleClarkSerial::LingleClarkSerial(), pism::diagnostics::scalar::mass_change(), pism::atmosphere::OrographicPrecipitationSerial::OrographicPrecipitationSerial(), pism::ocean::PicoPhysics::PicoPhysics(), pism::set_config_from_options(), set_eismint2_config_defaults(), pism::set_integer_from_option(), pism::set_number_from_option(), pism::inverse::IPDesignVariableParameterization::set_scales(), pism::inverse::IPDesignVariableParamExp::set_scales(), pism::inverse::IPDesignVariableParamTruncatedIdent::set_scales(), pism::stressbalance::SSAStrengthExtension::SSAStrengthExtension(), and pism::energy::tempSystemCtx::tempSystemCtx().