PISM, A Parallel Ice Sheet Model: pism::inverse::IPDesignVariableParameterization::toDesignVariable
convertFromDesignVariable
convertToDesignVariable
fromDesignVariable
IPDesignVariableParameterization
m_d_scale
set_scales
toDesignVariable
~IPDesignVariableParameterization
toDesignVariable()
virtual void pism::inverse::IPDesignVariableParameterization::toDesignVariable (double zeta, double * value, double * derivative) pure virtual
Converts from parameterization value \(\zeta\) to \(d=g(\zeta)\).
Parameters
[in] zeta The parameter value.
[out] value The value \(g(\zeta)\).
[out] derivative The value \(g'(\zeta)\).
Implemented in pism::inverse::IPDesignVariableParamTruncatedIdent, pism::inverse::IPDesignVariableParamExp, pism::inverse::IPDesignVariableParamSquare, and pism::inverse::IPDesignVariableParamIdent.
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), and convertToDesignVariable().