PISM, A Parallel Ice Sheet Model: pism::File::find_variable
append_history
attribute_name
attribute_type
backend
close
com
define_dimension
define_variable
dimension_length
dimension_type
dimensions
enddef
File
File
filename
find_dimension
find_variable
find_variable
m_impl
nattributes
nrecords
nrecords
nvariables
open
operator=
read_dimension
read_double_attribute
read_text_attribute
read_variable
read_variable_transposed
redef
remove_attribute
set_compression_level
sync
variable_name
write_attribute
write_attribute
write_distributed_array
write_variable
~File
find_variable() [2/2]
VariableLookupData pism::File::find_variable (const std::string & short_name, const std::string & std_name) const
Find a variable using its standard name and/or short name.
Sets "result" to the short name found.
Definition at line 366 of file File.cc.
References pism::RuntimeError::add_context(), pism::VariableLookupData::exists, filename(), pism::RuntimeError::formatted(), pism::VariableLookupData::found_using_standard_name, m_impl, pism::VariableLookupData::name, pism::File::Impl::nc, nvariables(), PISM_ERROR_LOCATION, read_text_attribute(), and variable_name().
Referenced by pism::IceModel::bootstrap_2d(), pism::IceRegionalModel::bootstrap_2d(), pism::hydrology::SteadyState::bootstrap_impl(), pism::MohrCoulombYieldStress::bootstrap_impl(), pism::calendar_from_options(), pism::bed::LingleClark::define_model_state_impl(), pism::hydrology::SteadyState::define_model_state_impl(), pism::io::define_spatial_variable(), pism::io::define_time(), pism::io::define_time_bounds(), pism::io::define_timeseries(), dimension_type(), pism::TSDiagnostic::flush(), pism::IceGrid::FromFile(), pism::energy::BTUGrid::FromOptions(), pism::IceGrid::FromOptions(), pism::get_projection_info(), pism::calving::CalvingAtThickness::init(), pism::AgeModel::init(), pism::IceModelVec2T::init(), pism::energy::EnergyModel::init_enthalpy(), pism::IceModel::init_extras(), pism::stressbalance::Blatter::init_impl(), pism::stressbalance::SSA::init_impl(), pism::DiagAverageRate< M >::init_impl(), pism::ocean::GivenTH::init_impl(), pism::energy::BTU_Full::init_impl(), pism::bed::LingleClark::init_impl(), nrecords(), pism::Timeseries::read(), pism::io::read_attributes(), read_dimension(), pism::io::read_spatial_variable(), pism::io::read_time_bounds(), pism::io::read_timeseries(), pism::reference_date_from_file(), pism::regional_grid_from_options(), pism::io::regrid_spatial_variable(), pism::energy::TemperatureModel::restart_impl(), pism::hydrology::SteadyState::restart_impl(), pism::NetCDFConfig::write_impl(), pism::IceModel::write_mapping(), pism::IceModel::write_run_stats(), pism::io::write_spatial_variable(), pism::io::write_time_bounds(), and pism::io::write_timeseries().