PISM, A Parallel Ice Sheet Model: pism::array::Array3D::interpolate
Array3D
copy_from
duplicate
get_column
get_column
interpolate
regrid_impl
set_column
set_column
~Array3D
interpolate()
double pism::array::Array3D::interpolate (int i, int j, double z) const
Return value of scalar quantity at level z (m) above base of ice (by linear interpolation).
Definition at line 88 of file Array3D.cc.
References pism::array::Array::Impl::bsearch_accel, pism::array::Array::check_array_indices(), pism::fem::column(), pism::RuntimeError::formatted(), get_column(), pism::array::Array::levels(), pism::array::Array::m_array, pism::array::Array::m_impl, pism::array::Array::Impl::name, and PISM_ERROR_LOCATION.
Referenced by pism::computeSurfaceVelocityErrors(), pism::IceCompModel::computeSurfaceVelocityErrors(), pism::array::extract_surface(), and pism::Isochrones::update().