PISM, A Parallel Ice Sheet Model: pism::stressbalance::BlatterTestCFBC::residual_source_term
BlatterTestCFBC
dirichlet_node
init_2d_parameters
jacobian_basal
m_B
m_g
m_L
m_rho_i
m_rho_w
residual_basal
residual_source_term
residual_surface
u_bc
residual_source_term()
void pism::stressbalance::BlatterTestCFBC::residual_source_term (const fem::Q1Element3 & element, const double * surface, const double * bed, Vector2d * residual) private virtual
Computes the residual contribution of the "source term".
This term contains the driving stress.
Reimplemented from pism::stressbalance::Blatter.
Definition at line 58 of file BlatterTestCFBC.cc.
References pism::blatter_xz_cfbc_source(), pism::fem::Element::chi(), pism::fem::Element3::evaluate(), pism::F(), m_g, m_L, m_rho_i, m_rho_w, pism::stressbalance::Blatter::m_scaling, pism::stressbalance::Blatter::m_work, n, pism::fem::Element::n_chi(), pism::fem::q13d::n_chi, pism::fem::Element::n_pts(), pism::fem::Element::weight(), pism::fem::Q1Element3::x(), and pism::fem::Q1Element3::z().