PISM, A Parallel Ice Sheet Model: pism::ocean::sea_level::InitializationHelper::init_impl
define_model_state_impl
init_impl
InitializationHelper
sea_level_elevation_impl
update_impl
write_model_state_impl
init_impl()
void pism::ocean::sea_level::InitializationHelper::init_impl (const Geometry & geometry) private virtual
Reimplemented from pism::ocean::sea_level::SeaLevel.
Definition at line 43 of file Initialization.cc.
References pism::File::close(), pism::InputOptions::filename, pism::INIT_RESTART, pism::init_step(), pism::Component::m_config, pism::Component::m_grid, pism::ocean::sea_level::SeaLevel::m_input_model, pism::Component::m_log, pism::ocean::sea_level::SeaLevel::m_sea_level, pism::File::nrecords(), pism::PISM_GUESS, pism::PISM_READONLY, pism::process_input_options(), pism::IceModelVec::read(), pism::Component::regrid(), pism::Component::REGRID_WITHOUT_REGRID_VARS, and pism::InputOptions::type.