PISM, A Parallel Ice Sheet Model: pism::Diagnostic::compute
allocate
compute
compute_impl
define
define_impl
define_state
define_state_impl
Diagnostic
init
init_impl
m_config
m_fill_value
m_grid
m_sys
m_vars
metadata
n_variables
Ptr
reset
reset_impl
to_external
to_internal
update
update_impl
wrap
write_state
write_state_impl
~Diagnostic
compute()
std::shared_ptr< array::Array > pism::Diagnostic::compute () const
Compute a diagnostic quantity and return a pointer to a newly-allocated Array.
Definition at line 131 of file Diagnostic.cc.
References compute_impl(), pism::join(), m_grid, and m_vars.
Referenced by pism::diagnostics::TemperatureSurface::compute_impl(), pism::diagnostics::IceAreaFractionFloating::compute_impl(), pism::stressbalance::SSB_taud_mag::compute_impl(), pism::stressbalance::SSB_taub_mag::compute_impl(), pism::stressbalance::PSB_velbar::compute_impl(), pism::stressbalance::PSB_velbar_mag::compute_impl(), pism::stressbalance::PSB_flux_mag::compute_impl(), pism::stressbalance::PSB_velbase_mag::compute_impl(), pism::stressbalance::PSB_velsurf_mag::compute_impl(), pism::stressbalance::PSB_wvel::compute_impl(), pism::stressbalance::PSB_wvelsurf::compute_impl(), pism::stressbalance::PSB_wvelbase::compute_impl(), pism::stressbalance::PSB_strain_rates::compute_impl(), pism::stressbalance::PSB_deviatoric_stresses::compute_impl(), pism::stressbalance::PSB_vonmises_stress::compute_impl(), and pism::stressbalance::SSATestCaseCFBC::write_nuH().