PISM, A Parallel Ice Sheet Model: pism::calving::EigenCalving::update
diagnostics_impl
EigenCalving
init
m_K
update
~EigenCalving
update()
void pism::calving::EigenCalving::update (const IceModelVec2CellType & cell_type, const IceModelVec2V & ice_velocity)
Uses principal strain rates to apply "eigencalving" with constant K.
See equation (26) in [Winkelmannetal2011].
Definition at line 60 of file EigenCalving.cc.
References pism::stressbalance::compute_2D_principal_strain_rates(), pism::IceModelVec2S::copy_from(), pism::IceModelVec2CellType::floating_ice(), I, pism::IceModelVec2CellType::ice_free_ocean(), pism::IceModelVec2CellType::ice_margin(), J, pism::calving::StressCalving::m_calving_rate, pism::calving::StressCalving::m_cell_type, pism::Component::m_grid, m_K, pism::calving::StressCalving::m_stencil_width, pism::calving::StressCalving::m_strain_rates, pism::PointsWithGhosts::next(), pism::IceModelVec2CellType::next_to_floating_ice(), and pism::IceModelVec::update_ghosts().