PISM, A Parallel Ice Sheet Model: pism::stressbalance::BlatterTestXZ::residual_source_term
BlatterTestXZ
dirichlet_node
m_A
m_alpha
m_beta
m_g
m_H0
m_rho
m_s0
marine_boundary
residual_basal
residual_source_term
residual_surface
u_bc
residual_source_term()
void pism::stressbalance::BlatterTestXZ::residual_source_term (const fem::Q1Element3 & element, const double * surface, const double * bed, Vector2 * residual) private virtual
Computes the residual contribution of the "source term".
This term contains the driving stress.
Reimplemented from pism::stressbalance::Blatter.
Definition at line 85 of file BlatterTestXZ.cc.
References pism::blatter_xz_source(), pism::fem::Element::chi(), pism::fem::Element3::evaluate(), m_A, m_alpha, m_beta, m_g, m_H0, m_rho, m_s0, pism::stressbalance::Blatter::m_scaling, pism::stressbalance::Blatter::m_work, n, pism::fem::Element::n_chi(), pism::fem::q13d::n_chi, pism::fem::Element::n_pts(), pism::fem::Element::weight(), pism::fem::Q1Element3::x(), and pism::fem::Q1Element3::z().