PISM, A Parallel Ice Sheet Model: pism::fem::DirichletData_Vector::fix_residual_homogeneous
DirichletData_Vector
enforce
enforce_homogeneous
fix_jacobian
fix_residual
fix_residual_homogeneous
m_values
~DirichletData_Vector
fix_residual_homogeneous()
void pism::fem::DirichletData_Vector::fix_residual_homogeneous (Vector2 ** r)
Definition at line 234 of file DirichletData.cc.
References pism::IceModelVec::grid(), pism::fem::DirichletData::m_indices, pism::PointsWithGhosts::next(), pism::Vector2::u, and pism::Vector2::v.
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization_transpose(), and pism::stressbalance::SSAFEM::compute_local_function().