PISM, A Parallel Ice Sheet Model: pism::IceModelVec2Int::star
as_int
box
ConstPtr
IceModelVec2Int
Ptr
star
star()
stencils::Star< int > pism::IceModelVec2Int::star (int i, int j) const inline
Definition at line 89 of file IceModelVec_inline.hh.
References as_int(), pism::stencils::Star< T >::e, pism::stencils::Star< T >::ij, pism::stencils::Star< T >::n, pism::stencils::Star< T >::s, and pism::stencils::Star< T >::w.
Referenced by pism::Poisson::assemble_matrix(), pism::stressbalance::SSAFD::assemble_matrix(), pism::stressbalance::SSAFD::assemble_rhs(), pism::ocean::PicoGeometry::basin_neighbors(), pism::stressbalance::compute_2D_principal_strain_rates(), pism::stressbalance::compute_2D_stresses(), pism::ocean::PicoGeometry::compute_distances_cf(), pism::stressbalance::SSAFD_Regional::compute_driving_stress(), pism::stressbalance::SSA::compute_driving_stress(), pism::diagnostics::IceAreaFraction::compute_impl(), pism::diagnostics::IceViscosity::compute_impl(), pism::frontalmelt::FrontalMelt::compute_retreat_rate(), pism::hydrology::EmptyingProblem::compute_velocity(), pism::hydrology::Routing::compute_velocity(), pism::ocean::eikonal_equation(), pism::grounding_line_flux(), pism::ocean::PicoGeometry::identify_calving_front_connection(), pism::GeometryEvolution::residual_redistribution_iteration(), pism::ocean::Pico::set_ocean_input_fields(), pism::staggered_to_regular(), pism::total_grounding_line_flux(), pism::calving::HayhurstCalving::update(), pism::FrontRetreat::update_geometry(), pism::frontalmelt::DischargeGiven::update_impl(), pism::frontalmelt::DischargeRouting::update_impl(), and pism::GeometryEvolution::update_in_place().