PISM, A Parallel Ice Sheet Model: pism::calving::CalvingAtThickness::update
CalvingAtThickness
diagnostics_impl
init
m_calving_threshold
m_old_mask
threshold
update
~CalvingAtThickness
update()
void pism::calving::CalvingAtThickness::update (double t, double dt, IceModelVec2CellType & pism_mask, IceModelVec2S & ice_thickness)
Updates ice cover mask and the ice thickness according to the calving rule removing ice at the shelf front that is thinner than a given threshold.
Parameters
[in] t beginning of the time step
[in] dt length of the time step
[in,out] pism_mask ice cover mask
[in,out] ice_thickness ice thickness
Returns
0 on success
Definition at line 102 of file CalvingAtThickness.cc.
References pism::IceModelVec2S::copy_from(), pism::IceModelVec2CellType::floating_ice(), m_calving_threshold, pism::Component::m_grid, m_old_mask, pism::MASK_ICE_FREE_OCEAN, pism::PointsWithGhosts::next(), pism::IceModelVec2CellType::next_to_ice_free_ocean(), threshold(), and pism::IceModelVec::update_ghosts().