PISM, A Parallel Ice Sheet Model: pism::energy::CHSystem::CHSystem
bootstrap_impl
CHSystem
define_model_state_impl
diagnostics_impl
initialize_impl
restart_impl
update_impl
write_model_state_impl
~CHSystem
CHSystem()
pism::energy::CHSystem::CHSystem (std::shared_ptr< const Grid > grid, std::shared_ptr< const stressbalance::StressBalance > stress_balance)
Model of the energy content in the cryo-hydrologic system.
This model can be used to include the influence of cryo-hydrologic warming on the internal energy of the ice.
This model is based on
@article{PhillipsRajaramSteffan2010, author = {Phillips, T. and Rajaram, H. and Steffen, K.}, doi = {10.1029/2010GL044397}, journal = {Geophy. Res. Lett.}, number = {20}, pages = {1–5}, title = {{Cryo-hydrologic warming: A potential mechanism for rapid thermal response of ice sheets}}, volume = {37}, year = {2010} }
We assume that during the melt season the enthalpy in the cryo-hydrologic system is equal to the enthalpy of the ice with a fixed water fraction corresponding to the amount of water remaining in the system once all of the moving water drains out (0.5% by default). During the winter the CH system is allowed to cool.
Definition at line 57 of file CHSystem.cc.
References pism::energy::EnergyModel::m_ice_enthalpy, pism::array::Array::metadata(), pism::array::Array::set_name(), and pism::VariableMetadata::set_name().