PISM, A Parallel Ice Sheet Model: pism::array::CellType1::next_to_ice
box_int
CellType1
CellType1
ice_margin
next_to_floating_ice
next_to_grounded_ice
next_to_ice
next_to_ice_free_land
next_to_ice_free_ocean
star_int
next_to_ice()
bool pism::array::CellType1::next_to_ice (int i, int j) const inline
Ice-free margin (at least one of four neighbors has ice).
Definition at line 87 of file CellType.hh.
References pism::array::CellType::icy().
Referenced by pism::frontalmelt::FrontalMelt::apply(), pism::ocean::PicoGeometry::basin_neighbors(), pism::frontalmelt::FrontalMelt::compute_retreat_rate(), pism::IceModel::enforce_consistency_of_geometry(), pism::stressbalance::SSA::extrapolate_velocity(), pism::FrontRetreat::max_timestep(), pism::calving::HayhurstCalving::update(), pism::calving::vonMisesCalving::update(), pism::FrontRetreat::update_geometry(), and pism::GeometryEvolution::update_in_place().