PISM, A Parallel Ice Sheet Model: pism::inverse::IPLogRelativeFunctional::normalize
gradientAt
IPLogRelativeFunctional
m_eps
m_normalization
m_u_observed
m_weights
normalize
valueAt
~IPLogRelativeFunctional
normalize()
void pism::inverse::IPLogRelativeFunctional::normalize (double scale) virtual
Determine the normalization constant for the functional.
Sets the normalization constant \(c_N\) so that
\[ J(x)=1 \]
if \(|x| = \mathtt{scale}\) everywhere.
Definition at line 34 of file IPLogRelativeFunctional.cc.
References pism::AccessList::add(), pism::GlobalSum(), m_eps, pism::inverse::IPFunctional< IceModelVec2V >::m_grid, m_normalization, m_u_observed, m_weights, pism::PointsWithGhosts::next(), pism::Vector2::u, and pism::Vector2::v.