PISM, A Parallel Ice Sheet Model: pism::GeometryEvolution::update_in_place
apply_flux_divergence
apply_mass_fluxes
area_specific_volume_change_due_to_flow
bottom_surface_mass_balance
compute_flux_divergence
compute_interface_fluxes
compute_surface_and_basal_mass_balance
conservation_error
diagnostics_impl
ensure_nonnegativity
flow_step
flux_divergence
flux_staggered
GeometryEvolution
init
init_impl
m_impl
reset
residual_redistribution_iteration
set_no_model_mask
set_no_model_mask_impl
source_term_step
thickness_change_due_to_flow
top_surface_mass_balance
update_in_place
~GeometryEvolution
update_in_place()
void pism::GeometryEvolution::update_in_place (double dt, const IceModelVec2S & bed_topography, const IceModelVec2S & sea_level, const IceModelVec2S & flux_divergence, IceModelVec2S & ice_thickness, IceModelVec2S & area_specific_volume) protected
Update ice thickness and area_specific_volume in place.
It would be better to compute the change in ice thickness and area_specific_volume and then apply them, but it would require re-writing all the part-grid code from scratch. So, I make copies of ice thickness and area_specific_volume, use this old code, then compute differences to get changes. Compute ice thickness changes due to the flow of the ice.
Parameters
[in] dt time step, seconds
[in] bed_elevation bed elevation, meters
[in] sea_level sea level elevation
[in] ice_thickness ice thickness
[in] area_specific_volume area-specific volume (m3/m2)
[in] flux_divergence flux divergence
[out] thickness_change ice thickness change due to flow
[out] area_specific_volume_change area specific volume change due to flow
Definition at line 673 of file GeometryEvolution.cc.
References pism::IceModelVec2S::add(), pism::GeometryEvolution::Impl::cell_type, pism::ParallelSection::check(), pism::GeometryCalculator::compute(), pism::GeometryCalculator::compute_mask(), pism::IceModelVec2S::copy_from(), pism::ParallelSection::failed(), flux_divergence(), pism::RuntimeError::formatted(), pism::GeometryEvolution::Impl::gc, pism::IceModelVec2CellType::ice_free_ocean(), pism::Component::m_config, pism::Component::m_grid, m_impl, pism::Component::m_log, pism::PointsWithGhosts::next(), pism::IceModelVec2CellType::next_to_ice(), pism::part_grid_threshold_thickness(), PISM_ERROR_LOCATION, pism::GeometryEvolution::Impl::residual, residual_redistribution_iteration(), pism::IceModelVec::set(), pism::IceModelVec2S::star(), pism::IceModelVec2Int::star(), pism::sum(), pism::GeometryEvolution::Impl::surface_elevation, pism::GeometryEvolution::Impl::thickness, pism::IceModelVec::update_ghosts(), and pism::GeometryEvolution::Impl::use_part_grid.
Referenced by flow_step().