PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSATestCase::report_netcdf
exactSolution
init
initializeSSACoefficients
m_bc_mask
m_bc_values
m_com
m_config
m_ctx
m_enthalpyconverter
m_geometry
m_grid
m_ice_enthalpy
m_ssa
m_stencil_width
m_sys
m_tauc
report
report_netcdf
run
SSATestCase
write
~SSATestCase
report_netcdf()
void pism::stressbalance::SSATestCase::report_netcdf (const std::string & testname, double max_vector, double rel_vector, double max_u, double max_v, double avg_u, double avg_v) protected
Definition at line 216 of file SSATestCase.cc.
References pism::options::Bool(), pism::VariableMetadata::clear_all_doubles(), pism::VariableMetadata::clear_all_strings(), pism::File::close(), pism::io::define_timeseries(), pism::File::dimension_length(), pism::options::Option< T >::is_set(), m_ctx, m_grid, pism::PISM_DOUBLE, pism::PISM_INT, pism::PISM_NETCDF3, pism::PISM_READWRITE, pism::PISM_READWRITE_MOVE, pism::VariableMetadata::set_name(), pism::io::write_attributes(), and pism::io::write_timeseries().
Referenced by report().