PISM, A Parallel Ice Sheet Model: pism::options::Real::Real
Real
Real()
pism::options::Real::Real (std::shared_ptr< units::System > system, const std::string & option, const std::string & description, const std::string & units, double default_value)
Definition at line 189 of file options.cc.
References pism::RuntimeError::add_context(), pism::units::convert(), pism::options::DONT_ALLOW_EMPTY, pism::options::Option< T >::is_set(), pism::printf(), pism::options::Option< double >::set(), and pism::options::Option< T >::value().