PISM, A Parallel Ice Sheet Model: pism::petsc::Wrapper::rawptr
get
m_value
operator T
operator=
Ptr
rawptr
WeakPtr
Wrapper
Wrapper
rawptr()
template<typename T > T* pism::petsc::Wrapper< T >::rawptr () inline
Definition at line 40 of file Wrapper.hh.
References pism::petsc::Wrapper< T >::m_value.
Referenced by pism::IceModelVec::allocate_proc0_copy(), pism::IceModelVec2T::IceModelVec2T(), pism::inverse::IP_SSAHardavForwardProblem::IP_SSAHardavForwardProblem(), pism::inverse::IP_SSATaucForwardProblem::IP_SSATaucForwardProblem(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::IP_SSATaucTaoTikhonovProblemLCL(), pism::inverse::IP_SSATaucTikhonovGNSolver::IP_SSATaucTikhonovGNSolver(), pism::inverse::IPTwoBlockVec::IPTwoBlockVec(), pism::bed::LingleClarkSerial::LingleClarkSerial(), pism::atmosphere::OrographicPrecipitationSerial::OrographicPrecipitationSerial(), pism::Poisson::Poisson(), pism::stressbalance::Blatter::setup(), pism::SNESProblem< DOF, U >::SNESProblem(), pism::stressbalance::SSAFEM::solve_nocache(), pism::stressbalance::SSAFD::SSAFD(), pism::stressbalance::SSAFEM::SSAFEM(), pism::taoutil::TaoBasicSolver< Problem >::TaoBasicSolver(), pism::IceModelVec::vec(), and pism::stressbalance::SSAFD::write_system_petsc().