PISM, A Parallel Ice Sheet Model: pism::fem::Element2::reset
add_contribution
add_contribution
Element2
Element2
evaluate
evaluate
local_to_global
m_normals
m_side_lengths
mark_col_invalid
mark_row_invalid
n_sides
nodal_values
nodal_values
normal
reset
side_length
reset()
void pism::fem::Element2::reset (int i, int j)
Initialize the Element to element (i, j) for the purposes of inserting into global residual and Jacobian arrays.
Definition at line 188 of file Element.cc.
References pism::k, local_to_global(), pism::fem::Element::m_col, pism::fem::Element::m_grid, pism::fem::Element::m_i, pism::fem::Element::m_i_offset, pism::fem::Element::m_j, pism::fem::Element::m_j_offset, pism::fem::Element::m_n_chi, pism::fem::Element::m_row, and mark_row_invalid().
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_H1NormFunctional2S::assemble_form(), pism::inverse::IPGroundedIceH1NormFunctional2S::assemble_form(), pism::stressbalance::SSAFEM::cache_residual_cfbc(), pism::stressbalance::SSAFEM::compute_local_function(), pism::stressbalance::SSAFEM::compute_local_jacobian(), pism::stressbalance::Blatter::compute_node_type(), pism::inverse::IP_H1NormFunctional2S::dot(), pism::inverse::IPGroundedIceH1NormFunctional2S::dot(), pism::inverse::IP_L2NormFunctional2S::dot(), pism::inverse::IP_L2NormFunctional2V::dot(), pism::inverse::IP_H1NormFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2S::gradientAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::gradientAt(), pism::inverse::IPTotalVariationFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2V::gradientAt(), pism::fem::P1Element2::P1Element2(), pism::fem::Q1Element2::Q1Element2(), pism::stressbalance::Blatter::report_mesh_info(), pism::calving::IcebergRemoverFEM::update_impl(), pism::inverse::IP_H1NormFunctional2S::valueAt(), pism::inverse::IP_L2NormFunctional2S::valueAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::valueAt(), pism::inverse::IPTotalVariationFunctional2S::valueAt(), and pism::inverse::IP_L2NormFunctional2V::valueAt().