PISM, A Parallel Ice Sheet Model: pism::calving::vonMisesCalving::init
diagnostics_impl
init
m_calving_threshold
m_flow_law
threshold
update
vonMisesCalving
~vonMisesCalving
init()
void pism::calving::vonMisesCalving::init ()
Definition at line 61 of file vonMisesCalving.cc.
References pism::CRITICAL, pism::RuntimeError::formatted(), m_calving_threshold, pism::Component::m_config, pism::Component::m_grid, pism::Component::m_log, pism::calving::StressCalving::m_strain_rates, pism::max(), pism::min(), PISM_ERROR_LOCATION, pism::IceModelVec::regrid(), and pism::IceModelVec::set().