PISM, A Parallel Ice Sheet Model: pism::inverse::IP_SSATaucTikhonovGNSolver::evaluate_objective_and_gradient
apply_GN
apply_GN
assemble_GN_rhs
check_convergence
compute_dlogalpha
designSolution
DesignVec
evaluate_objective_and_gradient
evaluateGNFunctional
init
IP_SSATaucTikhonovGNSolver
linesearch
m_alpha
m_comm
m_d
m_d0
m_d_diff
m_d_diff_lin
m_dalpha_rhs
m_design_stencil_width
m_designFunctional
m_dGlobal
m_dh_dalpha
m_dh_dalphaGlobal
m_eta
m_GN_rhs
m_grad_design
m_grad_state
m_gradient
m_h
m_hGlobal
m_iter
m_iter_max
m_ksp
m_log
m_logalpha
m_mat_GN
m_ssaforward
m_state_stencil_width
m_stateFunctional
m_target_misfit
m_tikhonov_adaptive
m_tikhonov_atol
m_tikhonov_ptol
m_tikhonov_rtol
m_tmp_D1Global
m_tmp_D1Local
m_tmp_D2Global
m_tmp_D2Local
m_tmp_S1Global
m_tmp_S1Local
m_tmp_S2Global
m_tmp_S2Local
m_u_diff
m_u_obs
m_val_design
m_val_state
m_value
m_vel_scale
m_x
setInitialGuess
setTargetMisfit
solve
solve_linearized
stateSolution
StateVec
~IP_SSATaucTikhonovGNSolver
evaluate_objective_and_gradient()
TerminationReason::Ptr pism::inverse::IP_SSATaucTikhonovGNSolver::evaluate_objective_and_gradient () virtual
Definition at line 262 of file IP_SSATaucTikhonovGNSolver.cc.
References pism::IceModelVec2< T >::add(), pism::IceModelVec2S::add(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization_transpose(), pism::IceModelVec2< T >::copy_from(), pism::IceModelVec2S::copy_from(), pism::inverse::IP_SSATaucForwardProblem::linearize_at(), m_alpha, m_d, m_d0, m_d_diff, m_designFunctional, m_grad_design, m_grad_state, m_gradient, m_ssaforward, m_stateFunctional, m_tmp_S1Global, m_u_diff, m_u_obs, m_val_design, m_val_state, m_value, pism::IceModelVec::scale(), and pism::inverse::IP_SSATaucForwardProblem::solution().
Referenced by linesearch(), and solve().