PISM, A Parallel Ice Sheet Model: pism::array::Forcing::update
allocate
array3
average
begin_access
buffer_size
Constant
discard
end_access
Forcing
Forcing
init
init_interpolation
init_periodic_data
interp
interp
m_data
max_timestep
set_record
update
update
~Forcing
update() [2/2]
void pism::array::Forcing::update (unsigned int start) private
Update by reading at most buffer_size records from the file.
Definition at line 481 of file Forcing.cc.
References pism::RuntimeError::add_context(), pism::array::Forcing::Data::buffer_size, buffer_size(), pism::LocalInterpCtx::count, discard(), pism::array::Forcing::Data::filename, pism::File::find_variable(), pism::array::Forcing::Data::first, pism::RuntimeError::formatted(), pism::petsc::VecArray::get(), pism::array::Array::get_name(), pism::array::Array::grid(), pism::array::Array::Impl::grid, pism::array::Array::Impl::interpolation_type, pism::array::Array::levels(), m_data, pism::array::Array::m_impl, pism::array::Array::metadata(), pism::array::Array::Impl::metadata, pism::array::min(), pism::array::Forcing::Data::n_records, pism::array::Array::Impl::name, PISM_ERROR_LOCATION, pism::io::PISM_GUESS, pism::io::PISM_READONLY, pism::io::regrid_spatial_variable(), pism::array::Array::Impl::report_range, set_record(), pism::LocalInterpCtx::start, pism::T_AXIS, pism::array::Forcing::Data::time, and pism::array::Array::vec().