PISM, A Parallel Ice Sheet Model: pism::array::Array::update_ghosts
add
allocate_proc0_copy
Array
Array
begin_access
check_array_indices
checkCompatibility
checksum
copy_to_vec
define
dm
dump
end_access
fletcher64
fletcher64_serial
get_dof
get_from_proc0
get_from_proc0
get_name
grid
inc_state_counter
levels
m_array
m_impl
metadata
metadata
ndims
ndof
norm
operator=
print_checksum
put_on_proc0
put_on_proc0
range
read
read
read_impl
regrid
regrid
regrid_impl
scale
set
set_begin_access_use_dof
set_dof
set_interpolation_type
set_name
shape
shift
size
state_counter
stencil_width
update_ghosts
vec
view
write
write
write_impl
~Array
update_ghosts()
void pism::array::Array::update_ghosts ()
Updates ghost points.
Definition at line 693 of file Array.cc.
References dm(), pism::array::Array::Impl::ghosted, m_impl, PISM_CHK, and vec().
Referenced by pism::hydrology::Routing::advective_fluxes(), pism::inverse::IP_SSATaucTikhonovGNSolver::apply_GN(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization_transpose(), pism::rheology::averaged_hardness_vec(), pism::energy::bootstrap_ice_temperature(), pism::stressbalance::SIAFD::compute_3d_horizontal_velocity(), pism::stressbalance::Blatter::compute_averaged_velocity(), pism::hydrology::Routing::compute_conductivity(), pism::ocean::PicoGeometry::compute_distances_cf(), pism::ocean::PicoGeometry::compute_distances_gl(), pism::inverse::IP_SSATaucTikhonovGNSolver::compute_dlogalpha(), pism::energy::compute_enthalpy(), pism::energy::compute_enthalpy_cold(), pism::hydrology::EmptyingProblem::compute_mask(), pism::stressbalance::Blatter::compute_node_type(), pism::compute_node_types(), pism::stressbalance::SSAFD::compute_nuH_staggered(), pism::stressbalance::SSAFD::compute_nuH_staggered_cfbc(), pism::hydrology::EmptyingProblem::compute_raw_potential(), pism::energy::compute_temperature(), pism::hydrology::EmptyingProblem::compute_velocity(), pism::inverse::IPDesignVariableParameterization::convertFromDesignVariable(), pism::inverse::IPDesignVariableParameterization::convertToDesignVariable(), pism::array::Array3D::copy_from(), pism::array::Staggered::copy_from(), pism::ocean::eikonal_equation(), pism::Geometry::ensure_consistency(), pism::enthalpy_from_temperature_cold(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluateGNFunctional(), pism::ocean::extend_basal_melt_rates(), pism::stressbalance::SSA::extrapolate_velocity(), pism::GeometryEvolution::flow_step(), pism::inverse::gradientFD(), pism::ice_bottom_surface(), pism::IceModel::identify_open_ocean(), pism::energy::TemperatureModel_Verification::initialize_impl(), pism::stressbalance::SSATestCaseCFBC::initializeSSACoefficients(), pism::stressbalance::SSATestCaseConst::initializeSSACoefficients(), pism::stressbalance::SSATestCaseExp::initializeSSACoefficients(), pism::stressbalance::SSATestCasePlug::initializeSSACoefficients(), pism::stressbalance::SSATestCaseI::initializeSSACoefficients(), pism::stressbalance::SSATestCaseJ::initializeSSACoefficients(), pism::IceCompModel::initTestABCDH(), pism::IceCompModel::initTestFG(), pism::IceCompModel::initTestL(), read_impl(), regrid_impl(), pism::IceCompModel::reset_thickness_test_A(), pism::GeometryEvolution::residual_redistribution_iteration(), pism::set_no_model_strip(), pism::setInitStateF(), pism::stressbalance::SSAFD::solve(), pism::stressbalance::SSAFEM::solve_nocache(), pism::stressbalance::SIAFD::surface_gradient_haseloff(), pism::IceCompModel::test_V_init(), pism::MohrCoulombYieldStress::till_friction_angle(), pism::stressbalance::BlatterMod::transfer(), pism::calving::FloatKill::update(), pism::calving::HayhurstCalving::update(), pism::ocean::PicoGeometry::update(), pism::stressbalance::ConstantInColumn::update(), pism::hydrology::EmptyingProblem::update(), pism::MPDATA2::update(), pism::UNO::update(), pism::calving::CalvingAtThickness::update(), pism::FrontRetreat::update_geometry(), pism::calving::IcebergRemover::update_impl(), pism::calving::IcebergRemoverFEM::update_impl(), pism::frontalmelt::DischargeGiven::update_impl(), pism::frontalmelt::DischargeRouting::update_impl(), pism::MohrCoulombYieldStress::update_impl(), pism::hydrology::Distributed::update_impl(), pism::hydrology::Routing::update_impl(), pism::GeometryEvolution::update_in_place(), and pism::hydrology::Routing::water_thickness_staggered().