PISM, A Parallel Ice Sheet Model: pism::energy::BTU_Full::BTU_Full
bootstrap
BTU_Full
define_model_state_impl
depth_impl
init_impl
m_bootstrapping_needed
m_column
m_D
m_k
m_Lbz
m_Mbz
m_temp
max_timestep_impl
Mz_impl
temperature
update_flux_through_top_surface
update_impl
update_impl
vertical_spacing_impl
write_model_state_impl
~BTU_Full
BTU_Full()
pism::energy::BTU_Full::BTU_Full (std::shared_ptr< const Grid > g, const BTUGrid & vertical_grid)
Definition at line 32 of file BTU_Full.cc.
References pism::RuntimeError::formatted(), pism::Component::grid(), pism::k, m_column, pism::Component::m_config, m_D, pism::Component::m_grid, m_k, m_Lbz, m_Mbz, m_temp, pism::energy::BedThermalUnit::Mz(), PISM_ERROR_LOCATION, rho, pism::energy::BedThermalUnit::vertical_spacing(), and pism::array::WITHOUT_GHOSTS.