PISM, A Parallel Ice Sheet Model: pism::rheology::FlowLawFactory::FlowLawFactory
add
create
FlowLawFactory
m_config
m_EC
m_flow_laws
m_prefix
m_type_name
remove
set_default
~FlowLawFactory
FlowLawFactory()
pism::rheology::FlowLawFactory::FlowLawFactory (const std::string & prefix, Config::ConstPtr conf, EnthalpyConverter::Ptr my_EC)
Definition at line 71 of file FlowLawFactory.cc.
References add(), pism::rheology::create_arr(), pism::rheology::create_arrwarm(), pism::rheology::create_goldsby_kohlstedt(), pism::rheology::create_gpbld(), pism::rheology::create_hooke(), pism::rheology::create_isothermal_glen(), pism::rheology::create_pb(), ICE_ARR, ICE_ARRWARM, ICE_GOLDSBY_KOHLSTEDT, ICE_GPBLD, ICE_HOOKE, ICE_ISOTHERMAL_GLEN, ICE_PB, m_config, m_flow_laws, m_prefix, and set_default().