PISM, A Parallel Ice Sheet Model: pism::Component::regrid
Component
define_model_state
define_model_state_impl
diagnostics
diagnostics_impl
grid
m_config
m_grid
m_log
m_sys
max_timestep
max_timestep_impl
regrid
RegriddingFlag
ts_diagnostics
ts_diagnostics_impl
write_model_state
write_model_state_impl
~Component
regrid()
void pism::Component::regrid (const std::string & module_name, IceModelVec & variable, RegriddingFlag flag = NO_REGRID_WITHOUT_REGRID_VARS) protected virtual
Regrid a variable by processing -regrid_file and -regrid_vars.
Parameters
[in] module_name Module name, used to annotate options when run with -help.
[out] variable pointer to an IceModelVec; variable has to have metadata set for this to work.
[in] flag Regridding flag. If set to REGRID_WITHOUT_REGRID_VARS, regrid this variable by default, if -regrid_vars was not set. Otherwise a variable is only regridded if both -regrid_file and -regrid_vars are set and the name of the variable is found in the set of names given with -regrid_vars.
Definition at line 151 of file Component.cc.
References pism::CRITICAL, pism::VariableMetadata::get_string(), m_config, m_log, pism::member(), pism::IceModelVec::metadata(), pism::IceModelVec::regrid(), REGRID_WITHOUT_REGRID_VARS, and pism::set_split().
Referenced by pism::hydrology::Distributed::bootstrap_impl(), pism::hydrology::Hydrology::bootstrap_impl(), pism::hydrology::Routing::bootstrap_impl(), pism::hydrology::SteadyState::bootstrap_impl(), pism::energy::EnthalpyModel::bootstrap_impl(), pism::energy::TemperatureModel::bootstrap_impl(), pism::ConstantYieldStress::bootstrap_impl(), pism::MohrCoulombYieldStress::finish_initialization(), pism::AgeModel::init(), pism::ocean::InitializationHelper::init_impl(), pism::ocean::sea_level::InitializationHelper::init_impl(), pism::surface::InitializationHelper::init_impl(), pism::surface::TemperatureIndex::init_impl(), pism::energy::BedThermalUnit::init_impl(), pism::energy::BTU_Full::init_impl(), pism::bed::BedDef::init_impl(), pism::bed::LingleClark::init_impl(), pism::ConstantYieldStress::init_impl(), pism::energy::EnthalpyModel::initialize_impl(), pism::energy::TemperatureModel::initialize_impl(), pism::FractureDensity::restart(), pism::ConstantYieldStress::restart_impl(), pism::energy::EnthalpyModel::restart_impl(), pism::energy::TemperatureModel::restart_impl(), pism::hydrology::Distributed::restart_impl(), pism::hydrology::Hydrology::restart_impl(), pism::hydrology::Routing::restart_impl(), pism::hydrology::SteadyState::restart_impl(), and pism::RegionalYieldStress::restart_impl().