PISM, A Parallel Ice Sheet Model: pism::IceBasalResistancePlasticLaw::drag
drag
drag_with_derivative
IceBasalResistancePlasticLaw
m_plastic_regularize
print_info
~IceBasalResistancePlasticLaw
drag()
double pism::IceBasalResistancePlasticLaw::drag (double tauc, double vx, double vy) const virtual
Compute the drag coefficient for the basal shear stress.
Reimplemented in pism::IceBasalResistanceRegularizedLaw, and pism::IceBasalResistancePseudoPlasticLaw.
Definition at line 47 of file basal_resistance.cc.
References m_plastic_regularize, and pism::square().
Referenced by pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::stressbalance::SSAFD::assemble_matrix(), pism::stressbalance::ShallowStressBalance::compute_basal_frictional_heating(), pism::stressbalance::SSB_beta::compute_impl(), pism::stressbalance::SSB_taub::compute_impl(), and pism::stressbalance::Blatter::residual_basal().