PISM, A Parallel Ice Sheet Model: pism::icebin::IBSurfaceModel::update_impl
accumulation_impl
define_model_state_impl
deltah
enthxfer
IBSurfaceModel
ice_top_bc_temp
ice_top_bc_wc
init_impl
liquid_water_fraction_impl
m_input_file
mass_flux_impl
massxfer
max_timestep_impl
melt_impl
runoff_impl
temperature_impl
update_impl
write_model_state_impl
update_impl()
void pism::icebin::IBSurfaceModel::update_impl (const Geometry & geometry, double my_t, double my_dt) protected virtual
Reimplemented from pism::surface::SurfaceModel.
Definition at line 70 of file IBSurfaceModel.cc.
References pism::surface::SurfaceModel::dummy_accumulation(), pism::surface::SurfaceModel::dummy_melt(), pism::surface::SurfaceModel::dummy_runoff(), pism::surface::SurfaceModel::m_accumulation, pism::surface::SurfaceModel::m_melt, pism::surface::SurfaceModel::m_runoff, and massxfer.