PISM, A Parallel Ice Sheet Model: pism::fem::Q1Element3Face::chi
chi
evaluate
m_chi
m_dx
m_dy
m_n_chi
m_normals
m_Nq
m_points
m_w
m_weights
n_pts
normal
Q1Element3Face
reset
weight
chi()
const double& pism::fem::Q1Element3Face::chi (unsigned int q, unsigned int k) const inline
Definition at line 412 of file Element.hh.
References pism::k, m_chi, m_n_chi, and m_Nq.
Referenced by pism::stressbalance::Blatter::jacobian_basal(), reset(), pism::stressbalance::Blatter::residual_basal(), pism::stressbalance::BlatterTestCFBC::residual_basal(), pism::stressbalance::BlatterTestHalfar::residual_basal(), pism::stressbalance::BlatterTestXZ::residual_basal(), pism::stressbalance::Blatter::residual_lateral(), pism::stressbalance::BlatterTestHalfar::residual_lateral(), pism::stressbalance::BlatterTestvanderVeen::residual_lateral(), pism::stressbalance::BlatterTestCFBC::residual_surface(), pism::stressbalance::BlatterTestHalfar::residual_surface(), pism::stressbalance::BlatterTestvanderVeen::residual_surface(), and pism::stressbalance::BlatterTestXZ::residual_surface().