PISM, A Parallel Ice Sheet Model: pism::surface::InitializationHelper::InitializationHelper
accumulation_impl
define_model_state_impl
init_impl
InitializationHelper
layer_mass_impl
layer_thickness_impl
liquid_water_fraction_impl
m_mass_flux
m_temperature
m_variables
mass_flux_impl
melt_impl
runoff_impl
temperature_impl
update_impl
write_model_state_impl
InitializationHelper()
pism::surface::InitializationHelper::InitializationHelper (std::shared_ptr< const Grid > g, std::shared_ptr< SurfaceModel > in)
Definition at line 29 of file Initialization.cc.
References pism::surface::SurfaceModel::allocate_accumulation(), pism::surface::SurfaceModel::allocate_layer_mass(), pism::surface::SurfaceModel::allocate_layer_thickness(), pism::surface::SurfaceModel::allocate_liquid_water_fraction(), pism::surface::SurfaceModel::allocate_melt(), pism::surface::SurfaceModel::allocate_runoff(), pism::Component::grid(), pism::VariableMetadata::long_name(), pism::surface::SurfaceModel::m_accumulation, pism::surface::SurfaceModel::m_layer_mass, pism::surface::SurfaceModel::m_layer_thickness, pism::surface::SurfaceModel::m_liquid_water_fraction, m_mass_flux, pism::surface::SurfaceModel::m_melt, pism::surface::SurfaceModel::m_runoff, m_temperature, m_variables, pism::array::Array::metadata(), PISM_ERROR_LOCATION, pism::VariableMetadata::set_time_independent(), and pism::VariableMetadata::units().