PISM, A Parallel Ice Sheet Model: pism::Isochrones::restart
bootstrap
define_model_state_impl
diagnostics_impl
initialize
Isochrones
layer_thicknesses
m_layer_thickness
m_stress_balance
m_tmp
m_top_layer_index
max_timestep_cfl
max_timestep_deposition_times
max_timestep_impl
restart
top_layer_deposition_time
update
write_model_state_impl
~Isochrones
restart()
void pism::Isochrones::restart (const File & input_file, int record)
Re-start the model from a PISM output file.
Definition at line 531 of file Isochrones.cc.
References initialize(), pism::details::layer_thickness_variable_name, pism::Component::m_config, pism::Component::m_grid, pism::Component::m_sys, pism::File::nrecords(), pism::io::PISM_GUESS, pism::io::PISM_READONLY, and pism::details::regridp().