PISM, A Parallel Ice Sheet Model: pism::ocean::PicoGeometry::PicoGeometry
basin_mask
basin_neighbors
box_mask
compute_box_mask
compute_continental_shelf_mask
compute_distances_cf
compute_distances_gl
compute_ice_rises
compute_ice_shelf_mask
compute_lakes
compute_ocean_mask
continental_shelf_mask
ice_rise_mask
ice_shelf_mask
IceRiseMask
identify_calving_front_connection
init
m_basin_mask
m_basin_neighbors
m_boxes
m_continental_shelf
m_distance_cf
m_distance_gl
m_ice_rises
m_ice_shelves
m_lake_mask
m_n_basins
m_ocean_mask
m_tmp
m_tmp_p0
PicoGeometry
relabel_by_size
split_ice_shelves
update
~PicoGeometry
PicoGeometry()
pism::ocean::PicoGeometry::PicoGeometry (std::shared_ptr< const Grid > grid)
Definition at line 33 of file PicoGeometry.cc.
References pism::array::Array::allocate_proc0_copy(), CONTINENTAL, FLOATING, pism::VariableMetadata::long_name(), m_basin_mask, m_boxes, m_continental_shelf, m_distance_cf, m_distance_gl, m_ice_rises, m_ice_shelves, m_lake_mask, m_n_basins, m_ocean_mask, m_tmp, m_tmp_p0, pism::array::Array::metadata(), pism::NEAREST, OCEAN, RISE, and pism::array::Array::set_interpolation_type().