PISM, A Parallel Ice Sheet Model: pism::ocean::PIK::update_impl
init_impl
mass_flux
max_timestep_impl
melting_point_temperature
PIK
update_impl
~PIK
update_impl()
void pism::ocean::PIK::update_impl (const Geometry & geometry, double my_t, double my_dt) private virtual
Reimplemented from pism::ocean::OceanModel.
Definition at line 59 of file ConstantPIK.cc.
References pism::ocean::OceanModel::compute_average_water_column_pressure(), pism::g, pism::Geometry::ice_thickness, pism::Component::m_config, pism::ocean::CompleteOceanModel::m_shelf_base_mass_flux, pism::ocean::CompleteOceanModel::m_shelf_base_temperature, pism::ocean::OceanModel::m_water_column_pressure, mass_flux(), and melting_point_temperature().