PISM, A Parallel Ice Sheet Model: pism::IceModelVec2S::star
add
add
array
array
box
ConstPtr
copy_from
IceModelVec2S
operator()
operator()
Ptr
star
star()
stencils::Star< double > pism::IceModelVec2S::star (int i, int j) const inline
Definition at line 42 of file IceModelVec_inline.hh.
References pism::stencils::Star< T >::e, pism::stencils::Star< T >::ij, pism::stencils::Star< T >::n, pism::stencils::Star< T >::s, and pism::stencils::Star< T >::w.
Referenced by pism::stressbalance::SSAFD::assemble_matrix(), pism::stressbalance::SSAFD_Regional::compute_driving_stress(), pism::stressbalance::SSA::compute_driving_stress(), pism::diagnostics::IceAreaFraction::compute_impl(), pism::stressbalance::BlatterMod::compute_max_diffusivity(), pism::hydrology::EmptyingProblem::compute_potential(), pism::hydrology::diagnostics::compute_sinks(), pism::hydrology::NullTransport::diffuse_till_water(), pism::GeometryEvolution::residual_redistribution_iteration(), pism::hydrology::EmptyingProblem::update(), pism::calving::HayhurstCalving::update(), pism::FractureDensity::update(), pism::FrontRetreat::update_geometry(), pism::GeometryEvolution::update_in_place(), pism::hydrology::Distributed::update_P(), and pism::hydrology::Routing::W_change_due_to_flow().