PISM, A Parallel Ice Sheet Model: pism::array::Forcing::Forcing
allocate
array3
average
begin_access
buffer_size
Constant
discard
end_access
Forcing
Forcing
init
init_interpolation
init_periodic_data
interp
interp
m_data
max_timestep
set_record
update
update
~Forcing
Forcing() [1/2]
pism::array::Forcing::Forcing (std::shared_ptr< const Grid > grid, const File & file, const std::string & short_name, const std::string & standard_name, unsigned int max_buffer_size, bool periodic, InterpolationType interpolation_type = PIECEWISE_CONSTANT)
Allocate an instance that will be used to load and use a forcing field from a file.
Checks the number of records in a file and allocates storage accordingly.
If periodic is true, allocate enough storage to hold all the records, otherwise allocate storage for at most max_buffer_size records.
Parameters
[in] grid computational grid
[in] file input file
[in] short_name variable name in file
[in] standard_name standard name (if available); leave blank to ignore
[in] max_buffer_size maximum buffer size for non-periodic fields
[in] periodic true if this forcing field should be interpreted as periodic
[in] interpolation_type type of temporal interpolation (LINEAR or PIECEWISE_CONSTANT)
Definition at line 112 of file Forcing.cc.
References allocate(), buffer_size(), pism::array::Array::grid(), pism::LINEAR, pism::array::max(), pism::array::min(), and pism::File::nrecords().
Referenced by Constant().