PISM, A Parallel Ice Sheet Model: pism::calving::IcebergRemover::update_impl
IcebergRemover
m_iceberg_mask
m_mask_p0
update
update_impl
~IcebergRemover
update_impl()
void pism::calving::IcebergRemover::update_impl (const array::Scalar & bc_mask, array::CellType1 & cell_type, array::Scalar & ice_thickness) protected virtual
Reimplemented in pism::calving::IcebergRemoverFEM.
Definition at line 50 of file IcebergRemover.cc.
References pism::ParallelSection::check(), pism::ParallelSection::failed(), pism::array::CellType::floating_ice(), pism::petsc::VecArray::get(), pism::array::Array::get_from_proc0(), pism::array::CellType::grounded_ice(), pism::array::CellType::icy(), label_connected_components(), pism::Component::m_grid, m_iceberg_mask, m_mask_p0, pism::MASK_ICE_FREE_OCEAN, pism::array::Array::put_on_proc0(), pism::array::Array::set(), and pism::array::Array::update_ghosts().
Referenced by update().