PISM, A Parallel Ice Sheet Model: pism::array::Array2D::array
add
add
array
array
Array2D
box
copy_from
operator()
operator()
star
value_type
array() [1/2]
template<typename T > T** pism::array::Array2D< T >::array () inline
Definition at line 43 of file Array2D.hh.
References pism::array::Array::m_array.
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization_transpose(), pism::inverse::IP_SSAHardavForwardProblem::assemble_jacobian_state(), pism::inverse::IP_SSATaucForwardProblem::assemble_jacobian_state(), pism::inverse::IP_SSAHardavForwardProblem::assemble_residual(), pism::inverse::IP_SSATaucForwardProblem::assemble_residual(), pism::stressbalance::SSAFEM::cache_residual_cfbc(), pism::fem::DirichletData::constrain(), pism::inverse::IP_H1NormFunctional2S::dot(), pism::inverse::IPGroundedIceH1NormFunctional2S::dot(), pism::inverse::IP_L2NormFunctional2S::dot(), pism::inverse::IP_L2NormFunctional2V::dot(), pism::fem::DirichletData_Scalar::enforce(), pism::fem::DirichletData_Vector::enforce(), pism::fem::DirichletData_Scalar::enforce_homogeneous(), pism::fem::DirichletData_Vector::enforce_homogeneous(), pism::inverse::IP_H1NormFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2S::gradientAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::gradientAt(), pism::inverse::IPTotalVariationFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2V::gradientAt(), pism::calving::IcebergRemoverFEM::update_impl(), pism::inverse::IP_H1NormFunctional2S::valueAt(), pism::inverse::IP_L2NormFunctional2S::valueAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::valueAt(), pism::inverse::IPTotalVariationFunctional2S::valueAt(), and pism::inverse::IP_L2NormFunctional2V::valueAt().