PISM, A Parallel Ice Sheet Model: pism::bed::PointwiseIsostasy::bootstrap_impl
bootstrap_impl
init_impl
m_load_last
max_timestep_impl
PointwiseIsostasy
update_impl
~PointwiseIsostasy
bootstrap_impl()
void pism::bed::PointwiseIsostasy::bootstrap_impl (const IceModelVec2S & bed_elevation, const IceModelVec2S & bed_uplift, const IceModelVec2S & ice_thickness, const IceModelVec2S & sea_level_elevation) protected virtual
Reimplemented from pism::bed::BedDef.
Definition at line 53 of file PointwiseIsostasy.cc.
References pism::bed::BedDef::bed_elevation(), pism::bed::BedDef::bootstrap_impl(), pism::bed::compute_load(), pism::IceModelVec2S::copy_from(), m_load_last, and pism::bed::BedDef::m_topg_last.