PISM, A Parallel Ice Sheet Model: pism::energy::TemperatureModel_Verification::initTestFG
initialize_impl
initTestFG
initTestsKO
m_bedrock_is_ice
m_testname
TemperatureModel_Verification
initTestFG()
void pism::energy::TemperatureModel_Verification::initTestFG () private
Definition at line 77 of file TemperatureModel_Verification.cc.
References pism::energy::ApforG, pism::exactFG(), pism::energy::LforFG, pism::Component::m_grid, pism::energy::TemperatureModel::m_ice_temperature, m_testname, pism::PointsWithGhosts::next(), pism::radius(), pism::IceModelVec3::set_column(), pism::energy::ST, pism::TestFGParameters::T, and pism::energy::Tmin.
Referenced by initialize_impl().