PISM, A Parallel Ice Sheet Model: pism::surface::ElevationChange::update_impl
accumulation_impl
ElevationChange
init_impl
m_mass_flux
m_reference_surface
m_smb_exp_factor
m_smb_lapse_rate
m_smb_method
m_temp_lapse_rate
m_temperature
mass_flux_impl
melt_impl
Method
runoff_impl
temperature_impl
update_impl
~ElevationChange
update_impl()
void pism::surface::ElevationChange::update_impl (const Geometry & geometry, double t, double dt) protected virtual
Reimplemented from pism::surface::SurfaceModel.
Definition at line 98 of file ElevationChange.cc.
References pism::surface::SurfaceModel::dummy_accumulation(), pism::surface::SurfaceModel::dummy_melt(), pism::surface::SurfaceModel::dummy_runoff(), pism::Geometry::ice_surface_elevation, pism::lapse_rate_correction(), pism::surface::SurfaceModel::m_accumulation, pism::Component::m_grid, pism::surface::SurfaceModel::m_input_model, m_mass_flux, pism::surface::SurfaceModel::m_melt, m_reference_surface, pism::surface::SurfaceModel::m_runoff, m_smb_exp_factor, m_smb_lapse_rate, m_smb_method, m_temp_lapse_rate, m_temperature, SCALE, and SHIFT.