PISM, A Parallel Ice Sheet Model: pism::bed::Given::update_impl
Given
init_impl
m_topg_delta
m_topg_reference
update_impl
~Given
update_impl()
void pism::bed::Given::update_impl (const array::Scalar & ice_thickness, const array::Scalar & sea_level_elevation, double t, double dt) protected virtual
Implements pism::bed::BedDef.
Definition at line 75 of file Given.cc.
References pism::array::Array2D< T >::add(), pism::bed::BedDef::compute_uplift(), pism::array::Array2D< T >::copy_from(), pism::bed::BedDef::m_topg, m_topg_delta, pism::bed::BedDef::m_topg_last, m_topg_reference, and pism::bed::BedDef::m_uplift.