PISM, A Parallel Ice Sheet Model: pism::calving::IcebergRemover::update_impl
IcebergRemover
m_iceberg_mask
m_mask_p0
update
update_impl
~IcebergRemover
update_impl()
void pism::calving::IcebergRemover::update_impl (const IceModelVec2Int & bc_mask, IceModelVec2CellType & pism_mask, IceModelVec2S & ice_thickness) protected virtual
Reimplemented in pism::calving::IcebergRemoverFEM.
Definition at line 51 of file IcebergRemover.cc.
References pism::ParallelSection::check(), pism::ParallelSection::failed(), pism::IceModelVec2CellType::floating_ice(), pism::petsc::VecArray::get(), pism::IceModelVec::get_from_proc0(), pism::IceModelVec2CellType::grounded_ice(), pism::IceModelVec2CellType::icy(), label_connected_components(), pism::Component::m_grid, m_iceberg_mask, m_mask_p0, pism::MASK_ICE_FREE_OCEAN, pism::PointsWithGhosts::next(), pism::IceModelVec::put_on_proc0(), pism::IceModelVec::set(), and pism::IceModelVec::update_ghosts().
Referenced by update().