PISM, A Parallel Ice Sheet Model: pism::IceModelVec2::copy_from
add
add
array
array
box
copy_from
IceModelVec2
operator()
operator()
star
value_type
copy_from()
template<typename T > void pism::IceModelVec2< T >::copy_from (const IceModelVec2< T > & source) inline
Definition at line 97 of file IceModelVec2.hh.
References pism::vec::copy().
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization_transpose(), pism::stressbalance::SSAFEM::cache_inputs(), pism::stressbalance::PSB_strain_rates::compute_impl(), pism::stressbalance::PSB_deviatoric_stresses::compute_impl(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluate_objective_and_gradient(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::evaluateConstraints(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::evaluateConstraintsJacobianDesign(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::evaluateConstraintsJacobianState(), pism::GeometryEvolution::flow_step(), pism::stressbalance::SSAFEM::init_impl(), pism::stressbalance::SSAFD::picard_iteration(), pism::stressbalance::SSAFD::picard_manager(), pism::stressbalance::SSAFD::picard_strategy_regularization(), pism::stressbalance::SSA::set_initial_guess(), pism::stressbalance::SSAFD::solve(), pism::stressbalance::SSAFEM::solve_nocache(), pism::FractureDensity::update(), and pism::hydrology::SteadyState::update_impl().