PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSA::update
compute_driving_stress
define_model_state_impl
diagnostics_impl
driving_stress
extrapolate_velocity
init_impl
m_da
m_event_ssa
m_mask
m_stdout_ssa
m_taud
m_velocity_global
set_initial_guess
solve
SSA
stdout_report
strength_extension
update
write_model_state_impl
~SSA
update()
void pism::stressbalance::SSA::update (const Inputs & inputs, bool full_update) virtual
Update the SSA solution.
Implements pism::stressbalance::ShallowStressBalance.
Reimplemented in pism::stressbalance::SSAFD_Regional.
Definition at line 152 of file SSA.cc.
References pism::stressbalance::Inputs::basal_yield_stress, pism::Geometry::bed_elevation, pism::stressbalance::ShallowStressBalance::compute_basal_frictional_heating(), pism::GeometryCalculator::compute_mask(), pism::stressbalance::Inputs::geometry, pism::Geometry::ice_thickness, pism::stressbalance::ShallowStressBalance::m_basal_frictional_heating, pism::Component::m_config, m_mask, pism::stressbalance::ShallowStressBalance::m_velocity, pism::Geometry::sea_level_elevation, pism::GeometryCalculator::set_icefree_thickness(), and solve().
Referenced by pism::stressbalance::SSATestCase::run(), and pism::stressbalance::SSAFD_Regional::update().