PISM, A Parallel Ice Sheet Model: pism::IceModelVec2S::add
add
add
array
array
box
ConstPtr
copy_from
IceModelVec2S
operator()
operator()
Ptr
star
add() [1/2]
void pism::IceModelVec2S::add (double alpha, const IceModelVec2S & x)
Definition at line 232 of file iceModelVec2.cc.
References pism::vec::add().
Referenced by pism::GeometryEvolution::apply_flux_divergence(), pism::inverse::IP_SSATaucTikhonovGNSolver::apply_GN(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::bed::BedDef::apply_topg_offset(), pism::inverse::IP_SSATaucTikhonovGNSolver::assemble_GN_rhs(), pism::stressbalance::SSAFD::assemble_matrix(), pism::bed::LingleClark::bootstrap_impl(), pism::stressbalance::SSAFEM::cache_inputs(), pism::IceModel::combine_basal_melt_rate(), pism::hydrology::Routing::compute_conductivity(), pism::inverse::IP_SSATaucTikhonovGNSolver::compute_dlogalpha(), pism::diagnostics::ThicknessRateOfChange::compute_impl(), pism::diagnostics::IceAreaFraction::compute_impl(), pism::diagnostics::IceMass::compute_impl(), pism::hydrology::EmptyingProblem::compute_mask(), pism::bed::BedDef::compute_uplift(), pism::inverse::IPMeanSquareFunctional2S::dot(), pism::icebin::IBIceModel::energy_step(), pism::hydrology::Hydrology::enforce_bounds(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluate_objective_and_gradient(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluateGNFunctional(), pism::GeometryEvolution::flow_step(), pism::IceModel::front_retreat_step(), pism::inverse::IPMeanSquareFunctional2S::gradientAt(), pism::ice_volume(), pism::bed::LingleClark::init_impl(), pism::diagnostics::scalar::mass_change(), pism::IceModel::max_timestep(), pism::bed::LingleClark::step(), pism::hydrology::EmptyingProblem::update(), pism::IceModel::update_fracture_density(), pism::surface::TemperatureIndex::update_impl(), pism::bed::Given::update_impl(), pism::MohrCoulombYieldStress::update_impl(), pism::hydrology::diagnostics::SubglacialWaterFlux::update_impl(), pism::DiagAverageRate< M >::update_impl(), pism::hydrology::NullTransport::update_impl(), pism::GeometryEvolution::update_in_place(), pism::hydrology::Routing::update_W(), and pism::hydrology::wall_melt().