PISM, A Parallel Ice Sheet Model: pism::hydrology::Distributed::update_P
bootstrap_impl
check_P_bounds
define_model_state_impl
Distributed
init_impl
initialization_message
m_P
m_Pnew
max_timestep_P_diff
P_from_W_steady
restart_impl
subglacial_water_pressure
ts_diagnostics_impl
update_impl
update_P
write_model_state_impl
~Distributed
update_P()
void pism::hydrology::Distributed::update_P (double dt, const array::CellType & cell_type, const array::Scalar & sliding_speed, const array::Scalar & surface_input_rate, const array::Scalar & basal_melt_rate, const array::Scalar & P_overburden, const array::Scalar & Wtill, const array::Scalar & Wtill_new, const array::Scalar & P, const array::Scalar1 & W, const array::Staggered1 & Ws, const array::Staggered1 & K, const array::Staggered1 & Q, array::Scalar & P_new) const protected
Definition at line 213 of file Distributed.cc.
References pism::c1, pism::c2, pism::clip(), pism::array::CellType::ice_free_land(), pism::hydrology::K(), pism::k, pism::Component::m_config, pism::hydrology::Routing::m_dx, pism::hydrology::Routing::m_dy, pism::Component::m_grid, pism::hydrology::Routing::m_rg, pism::array::max(), n, pism::array::CellType::ocean(), pism::array::Array2D< T >::star(), pism::array::Staggered1::star(), pism::hydrology::Hydrology::surface_input_rate(), and pism::Wr.
Referenced by update_impl().