PISM, A Parallel Ice Sheet Model: pism::IceGrid::Mz
cell_area
com
compute_interp_weights
compute_point_neighbors
compute_point_neighbors
compute_vertical_levels
ConstPtr
ctx
dx
dy
dz_max
dz_min
FromFile
FromFile
FromOptions
get_dm
get_mapping_info
IceGrid
IceGrid
kBelowHeight
Lx
Ly
Lz
m_impl
max_dm_dof
max_stencil_width
Mx
My
Mz
operator=
periodicity
pio_io_decomposition
Ptr
rank
registration
report_parameters
set_mapping_info
Shallow
size
variables
variables
x
x
x0
xm
xs
y
y
y0
ym
ys
z
z
~IceGrid
Mz()
unsigned int pism::IceGrid::Mz () const
Number of vertical levels.
Definition at line 948 of file IceGrid.cc.
References m_impl, and pism::IceGrid::Impl::z.
Referenced by pism::compute_strain_heating_errors(), pism::enthalpy_from_temperature_cold(), pism::GridParameters::init_from_config(), report_parameters(), and pism::GridParameters::vertical_grid_from_options().