PISM, A Parallel Ice Sheet Model: pism::array::Array3D::regrid_impl
Array3D
copy_from
duplicate
get_column
get_column
interpolate
regrid_impl
set_column
set_column
~Array3D
regrid_impl()
void pism::array::Array3D::regrid_impl (const File & file, io::Default default_value) virtual
Gets an Array from a file file, interpolating onto the current grid.
Stops if the variable was not found and critical == true.
Reimplemented from pism::array::Array.
Definition at line 250 of file Array3D.cc.
References pism::io::check_input_grid(), pism::array::Array::dm(), pism::File::filename(), pism::File::find_variable(), pism::petsc::VecArray::get(), pism::array::Array::Impl::ghosted, pism::array::global_to_local(), pism::array::Array::grid(), pism::array::Array::Impl::interpolation_type, pism::array::Array::levels(), pism::array::Array::m_impl, pism::array::Array::metadata(), PISM_CHK, pism::io::regrid_spatial_variable(), pism::grid::InputGridInfo::report(), pism::array::set_default_value_or_stop(), and pism::array::Array::vec().