PISM, A Parallel Ice Sheet Model: pism::Geometry::Geometry
bed_elevation
cell_grounded_fraction
cell_type
dump
ensure_consistency
Geometry
ice_area_specific_volume
ice_surface_elevation
ice_thickness
latitude
longitude
sea_level_elevation
Geometry()
pism::Geometry::Geometry (const std::shared_ptr< const Grid > & grid)
Definition at line 34 of file Geometry.cc.
References bed_elevation, cell_grounded_fraction, cell_type, ensure_consistency(), ice_area_specific_volume, ice_surface_elevation, ice_thickness, latitude, pism::VariableMetadata::long_name(), longitude, pism::MASK_FLOATING, pism::MASK_GROUNDED, pism::MASK_ICE_FREE_BEDROCK, pism::MASK_ICE_FREE_OCEAN, pism::array::Array::metadata(), pism::io::PISM_INT, sea_level_elevation, pism::array::Array::set(), pism::VariableMetadata::set_output_type(), pism::VariableMetadata::set_time_independent(), pism::VariableMetadata::standard_name(), and pism::VariableMetadata::units().