PISM, A Parallel Ice Sheet Model: pism::hydrology::EmptyingProblem::update
adjustment
compute_mask
compute_potential
compute_raw_potential
compute_velocity
diagnostics
effective_water_velocity
EmptyingProblem
flux
m_adjustment
m_bottom_surface
m_domain_mask
m_dx
m_dy
m_eps_gradient
m_potential
m_Q
m_q_sg
m_Qsum
m_sinks
m_speed
m_tau
m_tmp
m_Vstag
m_W
potential
remaining_water_thickness
sinks
update
~EmptyingProblem
update()
void pism::hydrology::EmptyingProblem::update (const Geometry & geometry, const IceModelVec2Int * no_model_mask, const IceModelVec2S & water_input_rate, bool recompute_potential = true)
Compute steady state water flux.
Parameters
[in] geometry ice geometry
[in] no_model_mask no model mask
[in] water_input_rate water input rate in m/s
Definition at line 174 of file EmptyingProblem.cc.
References pism::IceModelVec2S::add(), pism::Geometry::cell_type, compute_mask(), compute_potential(), compute_raw_potential(), pism::hydrology::diagnostics::compute_sinks(), compute_velocity(), pism::IceModelVec2S::copy_from(), pism::hydrology::diagnostics::effective_water_velocity(), pism::RuntimeError::formatted(), pism::GlobalSum(), pism::ice_bottom_surface(), pism::Geometry::ice_thickness, pism::IceModelVec2CellType::icy(), m_adjustment, m_bottom_surface, pism::Component::m_config, m_domain_mask, m_dx, m_dy, pism::Component::m_grid, pism::Component::m_log, m_potential, m_Q, m_q_sg, m_Qsum, m_sinks, m_speed, m_tau, m_tmp, m_Vstag, m_W, pism::PointsWithGhosts::next(), PISM_ERROR_LOCATION, pism::IceModelVec::scale(), pism::IceModelVec::set(), pism::staggered_to_regular(), pism::IceModelVec2S::star(), pism::IceModelVec2Stag::star(), and pism::IceModelVec::update_ghosts().