PISM, A Parallel Ice Sheet Model: pism::MaxTimestep::finite
description
finite
infinite
m_description
m_finite
m_value
MaxTimestep
MaxTimestep
MaxTimestep
MaxTimestep
value
finite()
bool pism::MaxTimestep::finite () const
Convert to bool to check if a time step restriction is "active".
Definition at line 47 of file MaxTimestep.cc.
References m_finite.
Referenced by pism::init_step(), pism::ocean::Cache::max_timestep_impl(), pism::surface::Cache::max_timestep_impl(), pism::operator<(), and pism::operator==().