PISM, A Parallel Ice Sheet Model: pism::IceModelVec2Int::as_int
as_int
box
ConstPtr
IceModelVec2Int
Ptr
star
as_int()
int pism::IceModelVec2Int::as_int (int i, int j) const inline
Definition at line 81 of file IceModelVec_inline.hh.
References pism::IceModelVec::check_array_indices(), and pism::IceModelVec::m_array.
Referenced by pism::stressbalance::SSAFD::assemble_matrix(), pism::stressbalance::SSAFD::assemble_rhs(), pism::Poisson::assemble_rhs(), pism::ocean::Pico::beckmann_goosse(), box(), pism::ocean::Pico::compute_box_area(), pism::ocean::Pico::compute_box_average(), pism::ocean::PicoGeometry::compute_box_mask(), pism::ocean::PicoGeometry::compute_continental_shelf_mask(), pism::ocean::PicoGeometry::compute_distances_cf(), pism::ocean::PicoGeometry::compute_distances_gl(), pism::ocean::PicoGeometry::compute_ice_shelf_mask(), pism::RegionalGeometryEvolution::compute_interface_fluxes(), pism::hydrology::EmptyingProblem::compute_mask(), pism::ocean::Pico::compute_ocean_input_per_basin(), pism::GeometryEvolution::compute_surface_and_basal_mass_balance(), pism::ocean::eikonal_equation(), pism::IceModelVec2CellType::floating_ice(), pism::IceModelVec2CellType::grounded(), pism::IceModelVec2CellType::grounded_ice(), pism::IceModelVec2CellType::ice_free(), pism::IceModelVec2CellType::ice_free_land(), pism::IceModelVec2CellType::ice_free_ocean(), pism::IceModelVec2CellType::icy(), pism::ocean::PicoGeometry::identify_calving_front_connection(), pism::IceModel::model_state_setup(), pism::fem::Element2::nodal_values(), pism::IceModelVec2CellType::ocean(), pism::ocean::Pico::process_box1(), pism::ocean::Pico::process_other_boxes(), pism::ocean::relabel(), pism::ocean::Pico::set_ocean_input_fields(), pism::ocean::PicoGeometry::split_ice_shelves(), star(), pism::FrontRetreat::update_geometry(), and pism::energy::TemperatureModel::update_impl().