PISM, A Parallel Ice Sheet Model: pism::TerminationReason::reason
description
done
failed
get_description
get_nested_description
has_root_cause
m_reason
m_root_cause
nested_description
operator=
Ptr
reason
root_cause
set_root_cause
sm_indent
succeeded
TerminationReason
TerminationReason
TerminationReason
~TerminationReason
reason()
virtual int pism::TerminationReason::reason () inline virtual
Definition at line 46 of file TerminationReason.hh.
References m_reason.
Referenced by done(), failed(), and succeeded().