PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSATestCaseJ::initializeSSACoefficients
exactSolution
initializeSSACoefficients
SSATestCaseJ
initializeSSACoefficients()
void pism::stressbalance::SSATestCaseJ::initializeSSACoefficients () protected virtual
Set up the coefficient variables as appropriate for the test case.
Implements pism::stressbalance::SSATestCase.
Definition at line 64 of file ssa_testj.cc.
References pism::Geometry::bed_elevation, pism::Geometry::cell_type, pism::units::convert(), exactJ(), TestJParameters::H, H0, pism::Geometry::ice_surface_elevation, pism::Geometry::ice_thickness, pism::stressbalance::SSATestCase::m_bc_mask, pism::stressbalance::SSATestCase::m_bc_values, pism::stressbalance::SSATestCase::m_config, pism::stressbalance::SSATestCase::m_enthalpyconverter, pism::stressbalance::SSATestCase::m_geometry, pism::stressbalance::SSATestCase::m_grid, pism::stressbalance::SSATestCase::m_ice_enthalpy, pism::stressbalance::SSATestCase::m_ssa, pism::stressbalance::SSATestCase::m_sys, pism::stressbalance::SSATestCase::m_tauc, pism::MASK_FLOATING, pism::PointsWithGhosts::next(), pism::IceModelVec::set(), pism::stressbalance::SSAStrengthExtension::set_min_thickness(), pism::stressbalance::SSAStrengthExtension::set_notional_strength(), pism::stressbalance::SSA::strength_extension, TestJParameters::u, pism::IceModelVec::update_ghosts(), and TestJParameters::v.