PISM, A Parallel Ice Sheet Model: pism::SpatialVariableMetadata::get_x
get_levels
get_x
get_x
get_y
get_y
get_z
get_z
init_internal
m_x
m_y
m_z
m_zlevels
set_levels
SpatialVariableMetadata
SpatialVariableMetadata
~SpatialVariableMetadata
get_x() [1/2]
VariableMetadata & pism::SpatialVariableMetadata::get_x ()
Definition at line 236 of file VariableMetadata.cc.
References m_x.
Referenced by pism::io::define_dimensions(), pism::io::define_spatial_variable(), and pism::io::write_dimensions().