PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSA::compute_driving_stress
compute_driving_stress
define_model_state_impl
diagnostics_impl
driving_stress
extrapolate_velocity
init_impl
m_da
m_event_ssa
m_mask
m_stdout_ssa
m_taud
m_velocity_global
set_initial_guess
solve
SSA
stdout_report
strength_extension
update
write_model_state_impl
~SSA
compute_driving_stress()
void pism::stressbalance::SSA::compute_driving_stress (const array::Scalar & ice_thickness, const array::Scalar1 & surface_elevation, const array::CellType1 & cell_type, const array::Scalar1 * no_model_mask, array::Vector & result) const protected virtual
Compute the gravitational driving stress.
Computes the gravitational driving stress at the base of the ice:
\[ \tau_d = - \rho g H \nabla h \]
Reimplemented in pism::stressbalance::SSAFD_Regional.
Definition at line 232 of file SSA.cc.
References pism::array::Array2D< T >::add(), pism::stencils::Star< T >::c, pism::array::diff_x_p(), pism::array::diff_y_p(), pism::stencils::Star< T >::e, pism::mask::floating_ice(), pism::mask::ice_free_ocean(), pism::Component::m_config, pism::stressbalance::ShallowStressBalance::m_EC, pism::Component::m_grid, pism::stencils::Star< T >::n, pism::stencils::Star< T >::s, pism::array::Array2D< T >::star(), pism::array::Scalar1::star_int(), pism::stencils::Star< T >::w, and pism::stressbalance::weight().
Referenced by pism::stressbalance::SSAFD::assemble_rhs(), and pism::stressbalance::SSAFD_Regional::compute_driving_stress().