PISM, A Parallel Ice Sheet Model: pism::Poisson::assemble_rhs
assemble_matrix
assemble_rhs
m_A
m_b
m_da
m_grid
m_KSP
m_log
m_mask
m_x
Poisson
solution
solve
assemble_rhs()
void pism::Poisson::assemble_rhs (double rhs, const IceModelVec2Int & mask, const IceModelVec2S & bc, IceModelVec2S & b) private
Definition at line 257 of file Poisson.cc.
References pism::IceModelVec2Int::as_int(), m_grid, and pism::PointsWithGhosts::next().
Referenced by solve().