PISM, A Parallel Ice Sheet Model: pism::options::Keyword::Keyword
Keyword
Keyword()
pism::options::Keyword::Keyword (const std::string & option, const std::string & description, const std::string & choices, const std::string & default_value)
Definition at line 95 of file options.cc.
References pism::options::DONT_ALLOW_EMPTY, pism::RuntimeError::formatted(), pism::options::Option< T >::is_set(), n, PISM_ERROR_LOCATION, pism::options::Option< std::string >::set(), and pism::set_split().