PISM, A Parallel Ice Sheet Model: pism::frontalmelt::DischargeRouting::update_impl
DischargeRouting
frontal_melt_rate_impl
init_impl
initialize
m_frontal_melt_rate
m_theta_ocean
max_timestep_impl
update_impl
~DischargeRouting
update_impl()
void pism::frontalmelt::DischargeRouting::update_impl (const FrontalMeltInputs & inputs, double t, double dt) private virtual
Reimplemented from pism::frontalmelt::FrontalMelt.
Definition at line 76 of file DischargeRouting.cc.
References pism::frontalmelt::FrontalMelt::apply(), pism::Geometry::bed_elevation, pism::Geometry::cell_type, pism::East, pism::frontalmelt::FrontalMeltPhysics::frontal_melt_from_undercutting(), pism::FrontalMeltInputs::geometry, pism::mask::grounded_ice(), pism::IceModelVec2CellType::ice_free(), pism::Geometry::ice_thickness, pism::IceModelVec2CellType::icy(), pism::mask::icy(), pism::Component::m_config, m_frontal_melt_rate, pism::Component::m_grid, pism::frontalmelt::FrontalMelt::m_include_floating_ice, m_theta_ocean, pism::max(), n, pism::PointsWithGhosts::next(), pism::North, pism::Geometry::sea_level_elevation, pism::South, pism::IceModelVec2Int::star(), pism::FrontalMeltInputs::subglacial_water_flux, and pism::West.