PISM, A Parallel Ice Sheet Model: pism::hydrology::Distributed::update_impl
bootstrap_impl
check_P_bounds
define_model_state_impl
Distributed
init_impl
initialization_message
m_P
m_Pnew
max_timestep_P_diff
P_from_W_steady
restart_impl
subglacial_water_pressure
ts_diagnostics_impl
update_impl
update_P
write_model_state_impl
~Distributed
update_impl()
void pism::hydrology::Distributed::update_impl (double t, double dt, const Inputs & inputs) protected virtual
Update the model state variables W,P by running the subglacial hydrology model.
Runs the hydrology model from time t to time t + dt. Here [t,dt] is generally on the order of months to years. This hydrology model will take its own shorter time steps, perhaps hours to weeks.
Reimplemented from pism::hydrology::Routing.
Definition at line 300 of file Distributed.cc.
References pism::array::Array::add(), pism::hydrology::Routing::advective_fluxes(), pism::Geometry::cell_type, pism::hydrology::check_bounds(), check_P_bounds(), pism::hydrology::Routing::compute_conductivity(), pism::hydrology::Routing::compute_velocity(), pism::units::convert(), pism::array::Array2D< T >::copy_from(), pism::hydrology::Hydrology::enforce_bounds(), pism::hydrology::Inputs::geometry, pism::ice_bottom_surface(), pism::hydrology::Inputs::ice_sliding_speed, pism::hydrology::Hydrology::m_basal_melt_rate, pism::hydrology::Routing::m_bottom_surface, pism::Component::m_config, pism::hydrology::Hydrology::m_conservation_error_change, pism::hydrology::Hydrology::m_grounded_margin_change, pism::hydrology::Hydrology::m_grounding_line_change, pism::hydrology::Routing::m_Kstag, pism::Component::m_log, pism::hydrology::Hydrology::m_no_model_mask_change, m_P, m_Pnew, pism::hydrology::Hydrology::m_Pover, pism::hydrology::Hydrology::m_Q, pism::hydrology::Routing::m_Qstag, pism::hydrology::Routing::m_Qstag_average, pism::hydrology::Hydrology::m_surface_input_rate, pism::Component::m_sys, pism::hydrology::Routing::m_Vstag, pism::hydrology::Hydrology::m_W, pism::hydrology::Routing::m_Wnew, pism::hydrology::Routing::m_Wstag, pism::hydrology::Hydrology::m_Wtill, pism::hydrology::Routing::m_Wtillnew, max_timestep_P_diff(), pism::hydrology::Routing::max_timestep_W_cfl(), pism::hydrology::Routing::max_timestep_W_diff(), pism::array::min(), pism::hydrology::Inputs::no_model_mask, pism::array::Array::scale(), pism::array::Array::set(), pism::array::staggered_to_regular(), subglacial_water_pressure(), pism::array::Array::update_ghosts(), update_P(), pism::hydrology::Routing::update_W(), pism::hydrology::Routing::update_Wtill(), and pism::hydrology::Routing::water_thickness_staggered().