PISM, A Parallel Ice Sheet Model: pism::bed::BedDef::bootstrap_impl
apply_topg_offset
bed_elevation
BedDef
bootstrap
bootstrap_impl
compute_uplift
define_model_state_impl
diagnostics_impl
init
init_impl
m_topg
m_topg_last
m_uplift
m_wide_stencil
update
update_impl
uplift
write_model_state_impl
~BedDef
bootstrap_impl()
void pism::bed::BedDef::bootstrap_impl (const array::Scalar & bed_elevation, const array::Scalar & bed_uplift, const array::Scalar & ice_thickness, const array::Scalar & sea_level_elevation) protected virtual
Reimplemented in pism::bed::LingleClark, and pism::bed::PointwiseIsostasy.
Definition at line 88 of file BedDef.cc.
References bed_elevation(), pism::array::Array2D< T >::copy_from(), m_topg, and m_uplift.
Referenced by bootstrap(), and pism::bed::PointwiseIsostasy::bootstrap_impl().