PISM, A Parallel Ice Sheet Model: pism::FrontRetreat::max_timestep
compute_modified_mask
FrontRetreat
m_cell_type
m_tmp
max_timestep
update_geometry
~FrontRetreat
max_timestep()
MaxTimestep pism::FrontRetreat::max_timestep (const array::CellType1 & cell_type, const array::Scalar & bc_mask, const array::Scalar & retreat_rate) const
Compute the maximum time step length provided a horizontal retreat rate.
Definition at line 71 of file FrontRetreat.cc.
References C, pism::units::convert(), pism::GlobalMax(), pism::GlobalSum(), pism::array::Array::grid(), pism::Component::grid(), pism::array::CellType::ice_free_ocean(), pism::Component::m_log, pism::Component::m_sys, pism::array::max(), and pism::array::CellType1::next_to_ice().