PISM, A Parallel Ice Sheet Model: pism::inverse::IPGroundedIceH1NormFunctional2S::dot
assemble_form
dot
gradientAt
IPGroundedIceH1NormFunctional2S
IPGroundedIceH1NormFunctional2S
m_cH1
m_cL2
m_dirichletIndices
m_ice_mask
operator=
valueAt
~IPGroundedIceH1NormFunctional2S
dot()
void pism::inverse::IPGroundedIceH1NormFunctional2S::dot (array::Scalar & a, array::Scalar & b, double * OUTPUT) virtual
Computes the inner product \(Q(a, b)\).
Implements pism::inverse::IPInnerProductFunctional< array::Scalar >.
Definition at line 81 of file IPGroundedIceH1NormFunctional.cc.
References pism::array::Array2D< T >::array(), pism::fem::DirichletData_Scalar::enforce_homogeneous(), pism::fem::Element2::evaluate(), pism::GlobalSum(), pism::array::CellType::grounded_ice(), pism::fem::ElementIterator::lxm, pism::fem::ElementIterator::lxs, pism::fem::ElementIterator::lym, pism::fem::ElementIterator::lys, m_cH1, m_cL2, m_dirichletIndices, pism::inverse::IPFunctional< array::Scalar >::m_element, pism::inverse::IPFunctional< array::Scalar >::m_element_index, pism::inverse::IPFunctional< array::Scalar >::m_grid, m_ice_mask, pism::fem::MAX_QUADRATURE_SIZE, pism::fem::q1::n_chi, pism::fem::Element::n_pts(), pism::fem::Element2::nodal_values(), pism::fem::Element2::reset(), and pism::fem::Element::weight().