PISM, A Parallel Ice Sheet Model: pism::surface::Cache::Cache
accumulation_impl
Cache
init_impl
layer_mass_impl
layer_thickness_impl
liquid_water_fraction_impl
m_mass_flux
m_next_update_time
m_temperature
m_update_interval_years
mass_flux_impl
max_timestep_impl
melt_impl
runoff_impl
temperature_impl
update_impl
~Cache
Cache()
pism::surface::Cache::Cache (std::shared_ptr< const Grid > g, std::shared_ptr< SurfaceModel > in)
Definition at line 33 of file Cache.cc.
References pism::surface::SurfaceModel::allocate_accumulation(), pism::surface::SurfaceModel::allocate_layer_mass(), pism::surface::SurfaceModel::allocate_layer_thickness(), pism::surface::SurfaceModel::allocate_liquid_water_fraction(), pism::surface::SurfaceModel::allocate_mass_flux(), pism::surface::SurfaceModel::allocate_melt(), pism::surface::SurfaceModel::allocate_runoff(), pism::surface::SurfaceModel::allocate_temperature(), pism::Time::convert_time_interval(), pism::Time::current(), pism::RuntimeError::formatted(), pism::Component::grid(), pism::surface::SurfaceModel::m_accumulation, pism::Component::m_config, pism::surface::SurfaceModel::m_layer_mass, pism::surface::SurfaceModel::m_layer_thickness, pism::surface::SurfaceModel::m_liquid_water_fraction, m_mass_flux, pism::surface::SurfaceModel::m_melt, m_next_update_time, pism::surface::SurfaceModel::m_runoff, m_temperature, m_update_interval_years, PISM_ERROR_LOCATION, and pism::Component::time().