PISM, A Parallel Ice Sheet Model: pism::inverse::IPDesignVariableParameterization::convertToDesignVariable
convertFromDesignVariable
convertToDesignVariable
fromDesignVariable
IPDesignVariableParameterization
m_d_scale
set_scales
toDesignVariable
~IPDesignVariableParameterization
convertToDesignVariable()
void pism::inverse::IPDesignVariableParameterization::convertToDesignVariable (IceModelVec2S & zeta, IceModelVec2S & d, bool communicate = true) virtual
Transforms a vector of \(\zeta\) values to a vector of \(d\) values.
Definition at line 50 of file IPDesignVariableParameterization.cc.
References pism::ParallelSection::check(), pism::IceGrid::com, pism::ParallelSection::failed(), pism::IceModelVec::grid(), pism::PointsWithGhosts::next(), PISM_CHK, toDesignVariable(), and pism::IceModelVec::update_ghosts().
Referenced by pism::inverse::IP_SSAHardavForwardProblem::set_design(), and pism::inverse::IP_SSATaucForwardProblem::set_design().