PISM, A Parallel Ice Sheet Model: pism::energy::BTU_Verification::bootstrap
bootstrap
BTU_Verification
initialize_bottom_surface_flux
m_bedrock_is_ice
m_testname
~BTU_Verification
bootstrap()
void pism::energy::BTU_Verification::bootstrap (const array::Scalar & bedrock_top_temperature) protected virtual
Reimplemented from pism::energy::BTU_Full.
Definition at line 44 of file BTU_Verification.cc.
References pism::ParallelSection::check(), pism::Time::current(), TestKParameters::error_code, exactK(), exactO(), pism::ParallelSection::failed(), pism::RuntimeError::formatted(), pism::k, m_bedrock_is_ice, pism::Component::m_grid, pism::energy::BTU_Full::m_Mbz, pism::energy::BTU_Full::m_temp, m_testname, PISM_ERROR_LOCATION, TestKParameters::T, pism::energy::BTU_Full::temperature(), pism::Component::time(), and TestOParameters::TT.