PISM, A Parallel Ice Sheet Model: pism::IceModelVec2Int::box
as_int
box
ConstPtr
IceModelVec2Int
Ptr
star
box()
stencils::Box< int > pism::IceModelVec2Int::box (int i, int j) const inline
Definition at line 101 of file IceModelVec_inline.hh.
References as_int(), and S().
Referenced by pism::stressbalance::SSAFD::assemble_matrix(), pism::stressbalance::SIAFD_Regional::compute_surface_gradient(), pism::ocean::extend_basal_melt_rates(), and pism::stressbalance::SSAFD::is_marginal().