PISM, A Parallel Ice Sheet Model: pism::energy::BedrockColumn::solve
BedrockColumn
m_D
m_dz
m_k
m_M
m_system
solve
solve
~BedrockColumn
solve() [1/2]
void pism::energy::BedrockColumn::solve (double dt, double Q_bottom, double T_top, const double * T_old, double * T_new)
Advance the heat equation in time.
Parameters
[in] dt time step length
[in] Q_bottom heat flux into the column through the bottom surface
[in] T_top temperature at the top surface
[in] T_old current temperature in the column
[out] T_new output
Note: T_old and T_new may point to the same location.
Definition at line 54 of file BedrockColumn.cc.
References pism::TridiagonalSystem::D(), G, pism::k, pism::TridiagonalSystem::L(), m_D, m_dz, m_k, m_M, m_system, pism::TridiagonalSystem::RHS(), pism::TridiagonalSystem::solve(), and pism::TridiagonalSystem::U().
Referenced by solve().