PISM, A Parallel Ice Sheet Model: pism::surface::diagnostics::Accumulation::Accumulation
Accumulation
m_accumulation_mass
m_kind
model_input
Accumulation()
pism::surface::diagnostics::Accumulation::Accumulation (const TemperatureIndex * m, AmountKind kind) inline
Definition at line 634 of file TemperatureIndex.cc.
References pism::DiagAverageRate< TemperatureIndex >::m_accumulator, pism::Diagnostic::m_fill_value, pism::Diagnostic::m_sys, pism::Diagnostic::m_vars, pism::surface::diagnostics::MASS, pism::IceModelVec::metadata(), pism::Diagnostic::set_attrs(), pism::VariableMetadata::set_string(), and pism::Diagnostic::to_internal().