PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSAFEM::PointwiseNuHAndBeta
cache_inputs
cache_residual_cfbc
compute_local_function
compute_local_jacobian
driving_stress
explicit_driving_stress
function_callback
init_impl
jacobian_callback
m_alpha
m_bc_mask
m_bc_values
m_beta_ice_free_bedrock
m_boundary_integral
m_callback_data
m_coefficients
m_dirichletScale
m_driving_stress_x
m_driving_stress_y
m_element_index
m_epsilon_ssa
m_gc
m_node_type
m_q1_element
m_rho_g
m_snes
monitor_function
monitor_jacobian
PointwiseNuHAndBeta
quad_point_values
solve
solve_nocache
solve_with_reason
SSAFEM
~SSAFEM
PointwiseNuHAndBeta()
void pism::stressbalance::SSAFEM::PointwiseNuHAndBeta (double thickness, double hardness, int mask, double tauc, const Vector2 & U, const Vector2 & U_x, const Vector2 & U_y, double * nuH, double * dnuH, double * beta, double * dbeta) protected
Compute the "(regularized effective viscosity) x (ice thickness)" and effective viscous bed strength from the current solution, at a single quadrature point.
Parameters
[in] thickness ice thickness
[in] hardness ice hardness
[in] mask cell type mask
[in] tauc basal yield stress
[in] U the value of the solution
[in] U_x x-derivatives of velocity components
[in] U_y y-derivatives of velocity components
[out] nuH product of the ice viscosity and thickness \(\nu H \)
[out] dnuH derivative of \(\nu H \) with respect to the second invariant \(\gamma \). Set to NULL if not desired.
[out] beta basal drag coefficient \(\beta \)
[out] dbeta derivative of \(\beta \) with respect to the second invariant \(\gamma \). Set to NULL if not desired.
Definition at line 497 of file SSAFEM.cc.
References pism::IceBasalResistancePlasticLaw::drag_with_derivative(), pism::stressbalance::SSAStrengthExtension::get_notional_strength(), pism::mask::grounded_ice(), pism::mask::ice_free_land(), pism::stressbalance::ShallowStressBalance::m_basal_sliding_law, m_beta_ice_free_bedrock, m_epsilon_ssa, pism::stressbalance::ShallowStressBalance::m_flow_law, pism::secondInvariant_2D(), pism::stressbalance::SSA::strength_extension, pism::Vector2::u, and pism::Vector2::v.
Referenced by compute_local_function(), and compute_local_jacobian().