PISM, A Parallel Ice Sheet Model: pism::GeometryEvolution::flow_step
apply_flux_divergence
apply_mass_fluxes
area_specific_volume_change_due_to_flow
bottom_surface_mass_balance
compute_flux_divergence
compute_interface_fluxes
compute_surface_and_basal_mass_balance
conservation_error
diagnostics_impl
ensure_nonnegativity
flow_step
flux_divergence
flux_staggered
GeometryEvolution
init
init_impl
m_impl
reset
residual_redistribution_iteration
set_no_model_mask
set_no_model_mask_impl
source_term_step
thickness_change_due_to_flow
top_surface_mass_balance
update_in_place
~GeometryEvolution
flow_step()
void pism::GeometryEvolution::flow_step (const Geometry & geometry, double dt, const IceModelVec2V & advective_velocity, const IceModelVec2Stag & diffusive_flux, const IceModelVec2Int & thickness_bc_mask)
Parameters
[in] geometry ice geometry
[in] dt time step, seconds
[in] advective_velocity advective (SSA) velocity
[in] diffusive_flux diffusive (SIA) flux
[in] velocity_bc_values advective velocity Dirichlet B.C. values
[in] thickness_bc_mask ice thickness Dirichlet B.C. mask
Results are stored in internal fields accessible using getters.
Definition at line 240 of file GeometryEvolution.cc.
References pism::IceModelVec2S::add(), pism::GeometryEvolution::Impl::area_specific_volume, pism::Geometry::bed_elevation, pism::GeometryEvolution::Impl::bed_elevation, pism::Profiling::begin(), pism::GeometryEvolution::Impl::cell_type, pism::GeometryCalculator::compute(), compute_flux_divergence(), compute_interface_fluxes(), pism::GeometryEvolution::Impl::conservation_error, pism::IceModelVec2< T >::copy_from(), pism::IceModelVec2S::copy_from(), pism::Profiling::end(), ensure_nonnegativity(), pism::GeometryEvolution::Impl::flux_divergence, pism::GeometryEvolution::Impl::flux_staggered, pism::GeometryEvolution::Impl::gc, pism::Geometry::ice_area_specific_volume, pism::GeometryEvolution::Impl::ice_area_specific_volume_change, pism::Geometry::ice_thickness, pism::GeometryEvolution::Impl::ice_thickness, pism::GeometryEvolution::Impl::input_velocity, m_impl, pism::GeometryEvolution::Impl::profile, pism::GeometryEvolution::Impl::sea_level, pism::Geometry::sea_level_elevation, pism::GeometryEvolution::Impl::surface_elevation, pism::GeometryEvolution::Impl::thickness_change, pism::IceModelVec::update_ghosts(), and update_in_place().