PISM, A Parallel Ice Sheet Model: pism::FrontRetreat::max_timestep
compute_modified_mask
FrontRetreat
m_cell_type
m_tmp
max_timestep
update_geometry
~FrontRetreat
max_timestep()
MaxTimestep pism::FrontRetreat::max_timestep (const IceModelVec2CellType & cell_type, const IceModelVec2Int & bc_mask, const IceModelVec2S & retreat_rate) const
Compute the maximum time step length provided a horizontal retreat rate.
Definition at line 74 of file FrontRetreat.cc.
References C, pism::units::convert(), pism::GlobalMax(), pism::GlobalSum(), pism::Component::grid(), pism::IceModelVec::grid(), pism::IceModelVec2CellType::ice_free_ocean(), pism::Component::m_log, pism::Component::m_sys, pism::max(), pism::PointsWithGhosts::next(), and pism::IceModelVec2CellType::next_to_ice().