PISM, A Parallel Ice Sheet Model: pism::calving::vonMisesCalving::vonMisesCalving
diagnostics_impl
init
m_calving_threshold
m_flow_law
threshold
update
vonMisesCalving
~vonMisesCalving
vonMisesCalving()
pism::calving::vonMisesCalving::vonMisesCalving (IceGrid::ConstPtr grid, std::shared_ptr< const rheology::FlowLaw > flow_law)
Definition at line 35 of file vonMisesCalving.cc.
References pism::rheology::FlowLawFactory::create(), pism::Component::grid(), pism::calving::StressCalving::m_calving_rate, m_calving_threshold, pism::Component::m_config, m_flow_law, pism::IceModelVec::metadata(), pism::IceModelVec::set_attrs(), pism::VariableMetadata::set_name(), and pism::IceModelVec::set_time_independent().