PISM, A Parallel Ice Sheet Model: pism::stressbalance::SIAFD::update
bed_smoother
compute_3d_horizontal_velocity
compute_diffusive_flux
compute_diffusivity
compute_I
compute_surface_gradient
diagnostics_impl
diffusivity
init
interglacial
m_bed_smoother
m_D
m_delta_0
m_delta_1
m_e_factor
m_e_factor_interglacial
m_eemian_end
m_eemian_start
m_event_sia
m_h_x
m_h_y
m_holocene_start
m_seconds_per_year
m_stencil_width
m_work_2d_0
m_work_2d_1
m_work_3d_0
m_work_3d_1
SIAFD
surface_gradient_eta
surface_gradient_haseloff
surface_gradient_mahaffy
surface_gradient_x
surface_gradient_y
update
~SIAFD
update()
void pism::stressbalance::SIAFD::update (const IceModelVec2V & sliding_velocity, const Inputs & inputs, bool full_update) virtual
Do the update; if full_update == false skip the update of 3D velocities and strain heating.
Implements pism::stressbalance::SSB_Modifier.
Definition at line 125 of file SIAFD.cc.
References pism::stressbalance::Inputs::age, pism::Geometry::bed_elevation, pism::Profiling::begin(), compute_3d_horizontal_velocity(), compute_diffusive_flux(), compute_diffusivity(), compute_surface_gradient(), pism::Profiling::end(), pism::stressbalance::Inputs::enthalpy, pism::stressbalance::Inputs::geometry, m_bed_smoother, m_D, pism::stressbalance::SSB_Modifier::m_diffusive_flux, pism::Component::m_grid, m_h_x, m_h_y, pism::stressbalance::SSB_Modifier::m_u, pism::stressbalance::SSB_Modifier::m_v, pism::stressbalance::Inputs::new_bed_elevation, and pism::stressbalance::BedSmoother::preprocess_bed().