PISM, A Parallel Ice Sheet Model: pism::VariableMetadata::get_name
check_range
clear_all_doubles
clear_all_strings
DoubleAttrs
get_all_doubles
get_all_strings
get_n_spatial_dimensions
get_name
get_number
get_numbers
get_output_type
get_string
get_time_independent
has_attribute
has_attributes
m_doubles
m_n_spatial_dims
m_output_type
m_short_name
m_strings
m_time_independent
m_unit_system
report_range
report_to_stdout
set_name
set_number
set_numbers
set_output_type
set_string
set_time_independent
StringAttrs
unit_system
VariableMetadata
~VariableMetadata
get_name()
std::string pism::VariableMetadata::get_name () const
Definition at line 306 of file VariableMetadata.cc.
References m_short_name.
Referenced by pism::Vars::add_shared(), pism::IceModelVec3::allocate_copy(), pism::IceRegionalModel::bootstrap_2d(), pism::hydrology::SteadyState::bootstrap_impl(), pism::MohrCoulombYieldStress::bootstrap_impl(), check_range(), pism::io::define_dimension(), pism::io::define_dimensions(), pism::io::define_spatial_variable(), pism::io::define_time_bounds(), pism::io::define_timeseries(), pism::TSDiagnostic::flush(), get_number(), get_string(), pism::TSDiagnostic::init(), pism::DefaultConfig::init(), pism::energy::EnergyModel::init_enthalpy(), pism::DiagAverageRate< M >::init_impl(), pism::Timeseries::name(), pism::Timeseries::read(), pism::NetCDFConfig::read_impl(), pism::io::read_spatial_variable(), pism::io::read_time_bounds(), pism::io::read_timeseries(), pism::energy::EnergyModel::regrid_enthalpy(), pism::io::regrid_spatial_variable(), pism::Timeseries::report_range(), report_range(), pism::energy::TemperatureModel::restart_impl(), pism::set_contains(), pism::io::write_attributes(), pism::io::write_dimensions(), pism::NetCDFConfig::write_impl(), pism::IceModel::write_mapping(), pism::IceModel::write_run_stats(), pism::io::write_spatial_variable(), pism::io::write_time_bounds(), and pism::io::write_timeseries().