PISM, A Parallel Ice Sheet Model: pism::ocean::PicoGeometry::init
basin_mask
box_mask
compute_box_mask
compute_continental_shelf_mask
compute_distances_cf
compute_distances_gl
compute_ice_rises
compute_ice_shelf_mask
compute_lakes
compute_ocean_mask
continental_shelf_mask
get_basin_neighbors
ice_rise_mask
ice_shelf_mask
IceRiseMask
identify_calving_front_connection
init
label_tmp
m_basin_mask
m_boxes
m_continental_shelf
m_distance_cf
m_distance_gl
m_ice_rises
m_ice_shelves
m_lake_mask
m_n_basin_neighbors
m_n_basins
m_ocean_mask
m_tmp
m_tmp_p0
PicoGeometry
relabel_by_size
split_ice_shelves
update
~PicoGeometry
init()
void pism::ocean::PicoGeometry::init (const IceModelVec2CellType & cell_type)
Definition at line 78 of file PicoGeometry.cc.
References pism::CRITICAL, pism::ForcingOptions::filename, get_basin_neighbors(), m_basin_mask, pism::Component::m_grid, m_n_basin_neighbors, m_n_basins, pism::IceModelVec2S::max(), and pism::IceModelVec::regrid().
Referenced by pism::ocean::Pico::init_impl().