PISM, A Parallel Ice Sheet Model: pism::array::CellType::ice_free
CellType
CellType
floating_ice
grounded
grounded_ice
ice_free
ice_free_land
ice_free_ocean
icy
ocean
ice_free()
bool pism::array::CellType::ice_free (int i, int j) const inline
Definition at line 54 of file CellType.hh.
References pism::array::Scalar::as_int(), and pism::mask::ice_free().
Referenced by pism::bedrock_surface_temperature(), pism::stressbalance::compute_2D_principal_strain_rates(), pism::stressbalance::compute_2D_stresses(), pism::stressbalance::StressBalance::compute_vertical_velocity(), pism::stressbalance::SSA::extrapolate_velocity(), pism::array::CellType1::ice_margin(), pism::MohrCoulombYieldStress::till_friction_angle(), pism::calving::HayhurstCalving::update(), and pism::FractureDensity::update().