PISM, A Parallel Ice Sheet Model: pism::array::Array::check_array_indices
add
allocate_proc0_copy
Array
Array
begin_access
check_array_indices
checkCompatibility
checksum
copy_to_vec
define
dm
dump
end_access
fletcher64
fletcher64_serial
get_dof
get_from_proc0
get_from_proc0
get_name
grid
inc_state_counter
levels
m_array
m_impl
metadata
metadata
ndims
ndof
norm
operator=
print_checksum
put_on_proc0
put_on_proc0
range
read
read
read_impl
regrid
regrid
regrid_impl
scale
set
set_begin_access_use_dof
set_dof
set_interpolation_type
set_name
shape
shift
size
state_counter
stencil_width
update_ghosts
vec
view
write
write
write_impl
~Array
check_array_indices()
void pism::array::Array::check_array_indices (int i, int j, unsigned int k) const protected
Check array indices and warn if they are out of range.
Definition at line 714 of file Array.cc.
References pism::array::Array::Impl::da_stencil_width, pism::array::Array::Impl::dof, pism::RuntimeError::formatted(), pism::array::Array::Impl::ghosted, grid(), pism::array::Array::Impl::grid, pism::k, m_array, m_impl, pism::array::max(), pism::array::Array::Impl::name, PISM_ERROR_LOCATION, and pism::array::Array::Impl::zlevels.
Referenced by pism::array::Array3D::get_column(), pism::array::Array3D::interpolate(), pism::array::Array2D< T >::operator()(), and pism::array::Array3D::set_column().