PISM, A Parallel Ice Sheet Model: pism::ocean::GivenTH::init_impl
GivenTH
init_impl
m_salinity_ocean
m_theta_ocean
max_timestep_impl
pointwise_update
subshelf_salinity
subshelf_salinity_diffusion_only
subshelf_salinity_freeze_on
subshelf_salinity_melt
update_impl
~GivenTH
init_impl()
void pism::ocean::GivenTH::init_impl (const Geometry & geometry) private virtual
Reimplemented from pism::ocean::OceanModel.
Definition at line 96 of file GivenTH.cc.
References pism::ocean::OceanModel::compute_average_water_column_pressure(), pism::IceModelVec2T::Constant(), pism::ForcingOptions::filename, pism::File::find_variable(), pism::g, pism::Component::m_config, pism::Component::m_grid, pism::Component::m_log, m_salinity_ocean, m_theta_ocean, pism::ocean::OceanModel::m_water_column_pressure, pism::ForcingOptions::periodic, pism::PISM_GUESS, pism::PISM_READONLY, and pism::ocean::OceanModel::update().