PISM, A Parallel Ice Sheet Model: pism::fem::DirichletData_Vector::fix_jacobian
DirichletData_Vector
enforce
enforce_homogeneous
fix_jacobian
fix_residual
fix_residual_homogeneous
m_values
~DirichletData_Vector
fix_jacobian()
void pism::fem::DirichletData_Vector::fix_jacobian (Mat J)
Definition at line 249 of file DirichletData.cc.
References pism::ParallelSection::check(), pism::Grid::com, pism::ParallelSection::failed(), pism::array::Array::grid(), J, pism::fem::DirichletData::m_indices, pism::fem::DirichletData::m_weight, pism::PointsWithGhosts::next(), PISM_CHK, pism::Grid::points(), and pism::fem::row().
Referenced by pism::stressbalance::SSAFEM::compute_local_jacobian().