PISM, A Parallel Ice Sheet Model: pism::energy::EnthalpyModel::restart_impl
bootstrap_impl
define_model_state_impl
EnthalpyModel
initialize_impl
restart_impl
update_impl
update_impl
write_model_state_impl
restart_impl()
void pism::energy::EnthalpyModel::restart_impl (const File & input_file, int record) protected virtual
Implements pism::energy::EnergyModel.
Reimplemented in pism::energy::EnthalpyModel_Regional, and pism::energy::DummyEnergyModel.
Definition at line 40 of file EnthalpyModel.cc.
References pism::File::filename(), pism::energy::EnergyModel::init_enthalpy(), pism::energy::EnergyModel::m_basal_melt_rate, pism::Component::m_log, pism::IceModelVec::read(), pism::Component::regrid(), pism::energy::EnergyModel::regrid_enthalpy(), and pism::Component::REGRID_WITHOUT_REGRID_VARS.
Referenced by pism::energy::DummyEnergyModel::restart_impl(), and pism::energy::EnthalpyModel_Regional::restart_impl().