PISM, A Parallel Ice Sheet Model: pism::GeometryEvolution::compute_flux_divergence
apply_flux_divergence
apply_mass_fluxes
area_specific_volume_change_due_to_flow
bottom_surface_mass_balance
compute_flux_divergence
compute_interface_fluxes
compute_surface_and_basal_mass_balance
conservation_error
diagnostics_impl
ensure_nonnegativity
flow_step
flux_divergence
flux_staggered
GeometryEvolution
init
init_impl
m_impl
reset
residual_redistribution_iteration
set_no_model_mask
set_no_model_mask_impl
source_term_step
thickness_change_due_to_flow
top_surface_mass_balance
update_in_place
~GeometryEvolution
compute_flux_divergence()
void pism::GeometryEvolution::compute_flux_divergence (double dt, const array::Staggered1 & flux, const array::Scalar & thickness_bc_mask, array::Scalar & conservation_error, array::Scalar & output) protected virtual
Compute flux divergence using cell interface fluxes on the staggered grid.
The flux divergence at ice thickness Dirichlet B.C. locations is set to zero.
Definition at line 649 of file GeometryEvolution.cc.
References pism::ParallelSection::check(), conservation_error(), pism::ParallelSection::failed(), pism::Component::m_grid, and pism::array::Staggered1::star().
Referenced by flow_step().