PISM, A Parallel Ice Sheet Model: pism::ScalarForcing::ScalarForcing
average
initialize
integral
m_acc
m_period
m_period_start
m_spline
m_times
m_values
operator=
ScalarForcing
ScalarForcing
ScalarForcing
value
~ScalarForcing
ScalarForcing() [1/3]
pism::ScalarForcing::ScalarForcing (const Context & ctx, const std::string & option_prefix, const std::string & variable_name, const std::string & units, const std::string & glaciological_units, const std::string & long_name)
Definition at line 185 of file ScalarForcing.cc.
References pism::Context::config(), pism::RuntimeError::formatted(), initialize(), and PISM_ERROR_LOCATION.