PISM, A Parallel Ice Sheet Model: pism::IceModelVec2S::array
add
add
array
array
box
ConstPtr
copy_from
IceModelVec2S
operator()
operator()
Ptr
star
array() [1/2]
double ** pism::IceModelVec2S::array ()
Definition at line 65 of file iceModelVec2.cc.
References pism::IceModelVec::m_array.
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::IceModelVec2T::average(), pism::stressbalance::SSAFEM::cache_residual_cfbc(), pism::fem::DirichletData::constrain(), pism::inverse::IP_H1NormFunctional2S::dot(), pism::inverse::IPGroundedIceH1NormFunctional2S::dot(), pism::inverse::IP_L2NormFunctional2S::dot(), pism::fem::DirichletData_Scalar::enforce(), pism::fem::DirichletData_Vector::enforce(), pism::fem::DirichletData_Scalar::enforce_homogeneous(), pism::fem::DirichletData_Vector::enforce_homogeneous(), pism::inverse::IP_H1NormFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2S::gradientAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::gradientAt(), pism::inverse::IPTotalVariationFunctional2S::gradientAt(), pism::IceModelVec2T::init_periodic_data(), pism::IceModelVec2T::interp(), pism::IceModelVec2T::set_record(), pism::calving::IcebergRemoverFEM::update_impl(), pism::inverse::IP_H1NormFunctional2S::valueAt(), pism::inverse::IP_L2NormFunctional2S::valueAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::valueAt(), and pism::inverse::IPTotalVariationFunctional2S::valueAt().