PISM, A Parallel Ice Sheet Model: pism::surface::Factory::create
add_surface_model
create
Factory
InputModel
m_input
m_surface_models
surface_model
~Factory
create()
std::shared_ptr< SurfaceModel > pism::surface::Factory::create (const std::string & type) virtual
Creates a boundary model.
Reimplemented from pism::PCFactory< SurfaceModel >.
Definition at line 58 of file Factory.cc.
References m_input, pism::PCFactory< SurfaceModel >::modifier(), pism::split(), and surface_model().
Referenced by pism::IceModel::allocate_couplers().