PISM, A Parallel Ice Sheet Model: pism::IceModelVec3::get_column
allocate_copy
ConstPtr
copy_from
extract_surface
extract_surface
get_column
get_column
get_column_vector
IceModelVec3
IceModelVec3
interpolate
legal_level
operator()
operator()
Ptr
set_column
set_column
set_column
sum_columns
To3DScalar
~IceModelVec3
get_column() [1/2]
double * pism::IceModelVec3::get_column (int i, int j)
Definition at line 223 of file iceModelVec3.cc.
References pism::IceModelVec::check_array_indices(), and pism::IceModelVec::m_array.
Referenced by pism::icebin::IBIceModel::accumulateFluxes_massContExplicitStep(), pism::rheology::averaged_hardness_vec(), pism::energy::bootstrap_ice_temperature(), pism::stressbalance::SSAFEM::cache_inputs(), pism::columnSystemCtx::coarse_to_fine(), pism::stressbalance::PSB_wvel::compute(), pism::stressbalance::SIAFD::compute_3d_horizontal_velocity(), pism::energy::compute_cts(), pism::stressbalance::SIAFD::compute_diffusivity(), pism::icebin::IBIceModel::compute_enth2(), pism::energy::compute_enthalpy(), pism::energy::compute_enthalpy_cold(), pism::stressbalance::SSAFD::compute_hardav_staggered(), pism::stressbalance::SIAFD::compute_I(), pism::diagnostics::HardnessAverage::compute_impl(), pism::diagnostics::Temperature::compute_impl(), pism::diagnostics::TemperaturePA::compute_impl(), pism::diagnostics::TemperaturePABasal::compute_impl(), pism::diagnostics::TemperateIceThickness::compute_impl(), pism::diagnostics::TemperateIceThicknessBasal::compute_impl(), pism::diagnostics::IceHardness::compute_impl(), pism::diagnostics::IceViscosity::compute_impl(), pism::stressbalance::PSB_flux::compute_impl(), pism::stressbalance::PSB_vonmises_stress::compute_impl(), pism::energy::compute_liquid_water_fraction(), pism::IceModel::compute_original_ice_fraction(), pism::compute_strain_heating_errors(), pism::IceCompModel::compute_strain_heating_errors(), pism::IceModel::compute_temperate_base_fraction(), pism::energy::compute_temperature(), pism::stressbalance::StressBalance::compute_vertical_velocity(), pism::stressbalance::StressBalance::compute_volumetric_strain_heating(), pism::IceCompModel::computeBasalTemperatureErrors(), pism::IceCompModel::computeIceBedrockTemperatureErrors(), pism::IceCompModel::computeTemperatureErrors(), pism::icebin::IBIceModel::construct_surface_temp(), copy_from(), pism::count_CFL_violations(), pism::energy::cryo_hydrologic_warming_flux(), pism::enthalpy_from_temperature_cold(), pism::columnSystemCtx::fine_to_coarse(), get_column_vector(), pism::IceModel::ice_area_cold(), pism::IceModel::ice_area_temperate(), pism::IceModel::ice_volume_cold(), pism::IceModel::ice_volume_temperate(), pism::max_timestep_cfl_3d(), pism::icebin::IBIceModel::prepare_initial_outputs(), set_column(), pism::stressbalance::Blatter::set_initial_guess(), sum_columns(), pism::energy::total_ice_enthalpy(), pism::stressbalance::BlatterMod::transfer(), pism::calving::vonMisesCalving::update(), pism::AgeModel::update(), pism::energy::CHSystem::update_impl(), pism::energy::EnthalpyModel_Regional::update_impl(), and pism::stressbalance::zero_above_ice().