PISM, A Parallel Ice Sheet Model: pism::stressbalance::BlatterMod::update
BlatterMod
compute_max_diffusivity
init
m_solver
transfer
update
~BlatterMod
update()
void pism::stressbalance::BlatterMod::update (const IceModelVec2V & sliding_velocity, const Inputs & inputs, bool full_update) virtual
Post-process ice velocity computed by the Blatter solver.
transfers velocity from the sigma grid onto PISM's vertical grid
estimates the maximum diffusivity used to compute the time step restriction
Implements pism::stressbalance::SSB_Modifier.
Definition at line 53 of file BlatterMod.cc.
References compute_max_diffusivity(), pism::stressbalance::Inputs::geometry, pism::Geometry::ice_surface_elevation, pism::Geometry::ice_thickness, pism::stressbalance::SSB_Modifier::m_diffusive_flux, m_solver, pism::IceModelVec::set(), and transfer().