PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSATestCasePlug::initializeSSACoefficients
B0
dhdx
dimensionless
exactSolution
glen_n
H0
initializeSSACoefficients
L
SSATestCasePlug
tauc0
initializeSSACoefficients()
void pism::stressbalance::SSATestCasePlug::initializeSSACoefficients () protected virtual
Set up the coefficient variables as appropriate for the test case.
Implements pism::stressbalance::SSATestCase.
Definition at line 96 of file ssa_test_plug.cc.
References pism::Geometry::bed_elevation, dhdx, exactSolution(), H0, pism::Geometry::ice_surface_elevation, pism::Geometry::ice_thickness, pism::stressbalance::SSATestCase::m_bc_mask, pism::stressbalance::SSATestCase::m_bc_values, pism::stressbalance::SSATestCase::m_config, pism::stressbalance::SSATestCase::m_geometry, pism::stressbalance::SSATestCase::m_grid, pism::stressbalance::SSATestCase::m_ssa, pism::stressbalance::SSATestCase::m_tauc, pism::PointsWithGhosts::next(), pism::IceModelVec::set(), pism::stressbalance::SSAStrengthExtension::set_min_thickness(), pism::stressbalance::SSA::strength_extension, tauc0, and pism::IceModelVec::update_ghosts().