PISM, A Parallel Ice Sheet Model: pism::inverse::IP_SSAHardavForwardProblem::assemble_jacobian_state
apply_jacobian_design
apply_jacobian_design
apply_jacobian_design
apply_jacobian_design_transpose
apply_jacobian_design_transpose
apply_jacobian_design_transpose
apply_linearization
apply_linearization_transpose
assemble_jacobian_state
assemble_residual
assemble_residual
design_param
DesignVec
DesignVecGhosted
get_da
init
IP_SSAHardavForwardProblem
linearize_at
m_design_param
m_du_global
m_du_local
m_dzeta_local
m_element
m_element_index
m_fixed_design_locations
m_hardav
m_J_state
m_ksp
m_reason
m_rebuild_J_state
m_stencil_width
m_velocity_shared
m_zeta
set_design
set_design_fixed_locations
solution
StateVec
StateVec1
~IP_SSAHardavForwardProblem
assemble_jacobian_state()
void pism::inverse::IP_SSAHardavForwardProblem::assemble_jacobian_state (array::Vector & u, Mat J) virtual
Assembles the state Jacobian matrix.
Definition at line 180 of file IP_SSAHardavForwardProblem.cc.
References pism::array::Array2D< T >::array(), and pism::stressbalance::SSAFEM::compute_local_jacobian().
Referenced by apply_linearization(), and apply_linearization_transpose().