PISM, A Parallel Ice Sheet Model: pism::diagnostics::TemperateIceThickness::compute_impl
compute_impl
TemperateIceThickness
compute_impl()
IceModelVec::Ptr pism::diagnostics::TemperateIceThickness::compute_impl () const protected virtual
Implements pism::Diagnostic.
Definition at line 801 of file diagnostics.cc.
References pism::Geometry::cell_type, pism::ParallelSection::check(), pism::IceModel::ctx(), pism::IceModel::energy_balance_model(), pism::energy::EnergyModel::enthalpy(), pism::ParallelSection::failed(), pism::IceModel::geometry(), pism::IceModelVec3::get_column(), pism::Geometry::ice_thickness, pism::IceModelVec2CellType::icy(), pism::k, pism::Diagnostic::m_fill_value, pism::Diagnostic::m_grid, pism::Diagnostic::m_vars, pism::Diag< IceModel >::model, pism::PointsWithGhosts::next(), and pism::WITHOUT_GHOSTS.