PISM, A Parallel Ice Sheet Model: pism::FrontRetreat::update_geometry
compute_modified_mask
FrontRetreat
m_cell_type
m_tmp
max_timestep
update_geometry
~FrontRetreat
update_geometry()
void pism::FrontRetreat::update_geometry (double dt, const Geometry & geometry, const array::Scalar1 & bc_mask, const array::Scalar & retreat_rate, array::Scalar & Href, array::Scalar1 & ice_thickness)
Update ice geometry by applying a horizontal retreat rate.
This code applies a horizontal retreat rate at "partially-filled" cells that are next to icy cells.
Models providing the "retreat rate" should set this field to zero in areas where a particular parameterization does not apply. (For example: some calving models apply at shelf calving fronts, others may apply at grounded termini but not at ice shelves, etc).
Definition at line 143 of file FrontRetreat.cc.
References pism::array::Scalar::as_int(), pism::Geometry::bed_elevation, pism::Geometry::cell_type, compute_modified_mask(), pism::array::Array2D< T >::copy_from(), pism::East, pism::array::CellType::floating_ice(), pism::mask::floating_ice(), pism::array::CellType::grounded_ice(), pism::mask::grounded_ice(), pism::array::CellType::ice_free_ocean(), pism::Geometry::ice_surface_elevation, m_cell_type, pism::Component::m_config, pism::Component::m_grid, m_tmp, pism::array::CellType1::next_to_ice(), pism::North, pism::part_grid_threshold_thickness(), pism::Geometry::sea_level_elevation, pism::array::Array::set(), pism::South, pism::array::Array2D< T >::star(), pism::array::CellType1::star_int(), pism::array::Scalar1::star_int(), pism::array::Array::update_ghosts(), and pism::West.