PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSAFD_Regional::compute_driving_stress
compute_driving_stress
init
m_h_stored
m_H_stored
m_no_model_mask
SSAFD_Regional
update
~SSAFD_Regional
compute_driving_stress()
void pism::stressbalance::SSAFD_Regional::compute_driving_stress (const IceModelVec2S & ice_thickness, const IceModelVec2S & surface_elevation, const IceModelVec2CellType & cell_type, const IceModelVec2Int * no_model_mask, IceModelVec2V & result) const virtual
Compute the gravitational driving stress.
Computes the gravitational driving stress at the base of the ice:
\[ \tau_d = - \rho g H \nabla h \]
Reimplemented from pism::stressbalance::SSA.
Definition at line 69 of file SSAFD_Regional.cc.
References pism::stressbalance::SSA::compute_driving_stress(), pism::stressbalance::ShallowStressBalance::m_EC, pism::Component::m_grid, m_h_stored, m_H_stored, pism::PointsWithGhosts::next(), pism::IceModelVec2S::star(), pism::IceModelVec2Int::star(), and pism::stressbalance::weight().