PISM, A Parallel Ice Sheet Model: pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose
apply_jacobian_design
apply_jacobian_design
apply_jacobian_design
apply_jacobian_design_transpose
apply_jacobian_design_transpose
apply_jacobian_design_transpose
apply_linearization
apply_linearization_transpose
assemble_jacobian_state
assemble_residual
assemble_residual
design_param
DesignVec
DesignVecGhosted
get_da
init
IP_SSAHardavForwardProblem
linearize_at
m_design_param
m_du_global
m_du_local
m_dzeta_local
m_element
m_element_index
m_fixed_design_locations
m_hardav
m_J_state
m_ksp
m_reason
m_rebuild_J_state
m_stencil_width
m_velocity_shared
m_zeta
set_design
set_design_fixed_locations
solution
StateVec
StateVec1
~IP_SSAHardavForwardProblem
apply_jacobian_design_transpose() [2/3]
void pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose (array::Vector & u, array::Vector & du, double ** dzeta_a) virtual
Applies the transpose of the design Jacobian matrix to a perturbation of the state variable.
The matrix depends on the current value of the design variable \(\zeta\) and the current value of the state variable \(u\). The specification of \(\zeta\) is done earlier with set_design or linearize_at. The value of \(u\) is specified explicitly as an argument to this method.
Parameters
[in] u Current state variable value.
[in] du Perturbation of the state variable. Prefers vectors with ghosts; will copy to a ghosted vector if need be.
[out] dzeta_a Computed corresponding perturbation of the design variable. The array dzeta_a should be extracted first from a Vec or an array::Array.
Typically this method is called via one of its overloads.
Definition at line 411 of file IP_SSAHardavForwardProblem.cc.
References pism::array::Array2D< T >::add(), pism::fem::Element2::add_contribution(), pism::array::Array2D< T >::array(), pism::ParallelSection::check(), pism::fem::Element::chi(), pism::array::Array2D< T >::copy_from(), pism::fem::DirichletData_Vector::enforce(), pism::fem::DirichletData_Vector::enforce_homogeneous(), pism::fem::Element2::evaluate(), pism::ParallelSection::failed(), pism::fem::DirichletData_Scalar::fix_residual_homogeneous(), pism::stressbalance::SSAStrengthExtension::get_min_thickness(), pism::k, pism::stressbalance::SSAFEM::m_bc_mask, pism::stressbalance::SSAFEM::m_bc_values, pism::stressbalance::SSAFEM::m_coefficients, m_design_param, pism::stressbalance::SSAFEM::m_dirichletScale, m_du_local, m_element, m_element_index, m_fixed_design_locations, pism::stressbalance::ShallowStressBalance::m_flow_law, pism::Component::m_grid, m_zeta, pism::fem::MAX_QUADRATURE_SIZE, pism::fem::q1::n_chi, pism::fem::Element::n_pts(), pism::fem::Element2::nodal_values(), pism::stressbalance::SSAFEM::quad_point_values(), pism::fem::Element2::reset(), pism::secondInvariant_2D(), pism::array::Array::stencil_width(), pism::stressbalance::SSA::strength_extension, pism::inverse::IPDesignVariableParameterization::toDesignVariable(), pism::Vector2d::u, pism::Vector2d::v, pism::fem::Germ::val, pism::fem::Element::weight(), pism::fem::ElementIterator::xm, pism::fem::ElementIterator::xs, pism::fem::ElementIterator::ym, and pism::fem::ElementIterator::ys.