PISM, A Parallel Ice Sheet Model: pism::inverse::IP_L2NormFunctional2V::dot
dot
gradientAt
IP_L2NormFunctional2V
IP_L2NormFunctional2V
operator=
valueAt
~IP_L2NormFunctional2V
dot()
void pism::inverse::IP_L2NormFunctional2V::dot (array::Vector & a, array::Vector & b, double * OUTPUT) virtual
Computes the inner product \(Q(a, b)\).
Implements pism::inverse::IPInnerProductFunctional< array::Vector >.
Definition at line 196 of file IP_L2NormFunctional.cc.
References pism::array::Array2D< T >::array(), pism::fem::Element2::evaluate(), pism::GlobalSum(), pism::fem::ElementIterator::lxm, pism::fem::ElementIterator::lxs, pism::fem::ElementIterator::lym, pism::fem::ElementIterator::lys, pism::inverse::IPFunctional< array::Vector >::m_element, pism::inverse::IPFunctional< array::Vector >::m_element_index, pism::inverse::IPFunctional< array::Vector >::m_grid, pism::fem::MAX_QUADRATURE_SIZE, pism::fem::q1::n_chi, pism::fem::Element::n_pts(), pism::fem::Element2::nodal_values(), pism::fem::Element2::reset(), pism::Vector2d::u, pism::Vector2d::v, and pism::fem::Element::weight().