PISM, A Parallel Ice Sheet Model: pism::atmosphere::Frac_P::Frac_P
begin_pointwise_access_impl
end_pointwise_access_impl
Frac_P
init_impl
init_timeseries_impl
m_1d_scaling
m_2d_scaling
m_precipitation
m_scaling_values
precip_time_series_impl
precipitation_impl
update_impl
~Frac_P
Frac_P()
pism::atmosphere::Frac_P::Frac_P (std::shared_ptr< const Grid > g, std::shared_ptr< AtmosphereModel > in)
Definition at line 30 of file Frac_P.cc.
References pism::atmosphere::AtmosphereModel::allocate_precipitation(), pism::File::dimensions(), pism::ForcingOptions::filename, pism::Component::grid(), m_1d_scaling, m_2d_scaling, pism::Component::m_config, pism::Component::m_grid, m_precipitation, pism::ForcingOptions::periodic, pism::io::PISM_GUESS, and pism::io::PISM_READONLY.