PISM, A Parallel Ice Sheet Model: pism::GeometryCalculator::set_icefree_thickness
compute
compute
compute_mask
compute_surface
GeometryCalculator
m_alpha
m_icefree_thickness
mask
set_icefree_thickness
surface
set_icefree_thickness()
void pism::GeometryCalculator::set_icefree_thickness (double threshold) inline
Definition at line 81 of file Mask.hh.
References pism::RuntimeError::formatted(), m_icefree_thickness, and PISM_ERROR_LOCATION.
Referenced by pism::diagnostics::IceMarginPressureDifference::compute_impl(), pism::Geometry::ensure_consistency(), pism::GeometryEvolution::Impl::Impl(), and pism::stressbalance::SSA::update().