PISM, A Parallel Ice Sheet Model: pism::surface::ISMIP6::ISMIP6
accumulation_impl
init_impl
ISMIP6
m_mass_flux
m_mass_flux_anomaly
m_mass_flux_gradient
m_mass_flux_reference
m_surface_reference
m_temperature
m_temperature_anomaly
m_temperature_gradient
m_temperature_reference
mass_flux_impl
max_timestep_impl
melt_impl
runoff_impl
temperature_impl
update_impl
~ISMIP6
ISMIP6()
pism::surface::ISMIP6::ISMIP6 (std::shared_ptr< const Grid > g, std::shared_ptr< atmosphere::AtmosphereModel > input)
Definition at line 30 of file ISMIP6Climate.cc.
References pism::surface::SurfaceModel::allocate_mass_flux(), pism::surface::SurfaceModel::allocate_temperature(), pism::ForcingOptions::filename, pism::VariableMetadata::long_name(), pism::Component::m_config, pism::Component::m_grid, m_mass_flux, m_mass_flux_anomaly, m_mass_flux_gradient, m_mass_flux_reference, m_surface_reference, m_temperature, m_temperature_anomaly, m_temperature_gradient, m_temperature_reference, pism::array::Array::metadata(), pism::VariableMetadata::output_units(), pism::ForcingOptions::periodic, pism::io::PISM_NETCDF3, pism::io::PISM_READONLY, pism::VariableMetadata::set_time_independent(), pism::VariableMetadata::standard_name(), and pism::VariableMetadata::units().