PISM, A Parallel Ice Sheet Model: pism::surface::NoGLRetreat::NoGLRetreat
accumulation_impl
diagnostics_impl
init_impl
m_mass_flux
m_min_ice_thickness
m_smb_adjustment
mass_flux_impl
melt_impl
NoGLRetreat
runoff_impl
smb_adjustment
update_impl
~NoGLRetreat
NoGLRetreat()
pism::surface::NoGLRetreat::NoGLRetreat (IceGrid::ConstPtr g, std::shared_ptr< SurfaceModel > input)
Definition at line 29 of file NoGLRetreat.cc.
References pism::surface::SurfaceModel::allocate_accumulation(), pism::surface::SurfaceModel::allocate_mass_flux(), pism::surface::SurfaceModel::allocate_melt(), pism::surface::SurfaceModel::allocate_runoff(), pism::Component::grid(), pism::surface::SurfaceModel::m_accumulation, m_mass_flux, pism::surface::SurfaceModel::m_melt, pism::surface::SurfaceModel::m_runoff, m_smb_adjustment, and pism::IceModelVec::metadata().