PISM, A Parallel Ice Sheet Model: pism::calving::IcebergRemoverFEM::update_impl
IcebergRemoverFEM
m_mask
update_impl
update_impl()
void pism::calving::IcebergRemoverFEM::update_impl (const IceModelVec2Int & bc_mask, IceModelVec2CellType & pism_mask, IceModelVec2S & ice_thickness) private virtual
Remove "icebergs" using the finite element notion of connectivity: two elements are connected if they share a boundary.
Loop over elements and create a mask that will be used to determine connectivity between elements.
an element is a "grounded ice element" if all nodes are icy and are either grounded or belong to the set of Dirichlet nodes
an element is "floating ice" if all nodes are icy and at least one node is "floating ice"
all other elements are ice-free
Label connected components, identifying "icebergs".
Once "iceberg" elements are labeled we need to remove nodes that belong to icebergs but do not belong to any elements connected to grounded ice.
Create a mask filled with zeros. Loop over elements and add 1 to nodes of all "iceberg" elements. Add -1 to all nodes of "grounded" elements.
Now loop over all nodes and remove nodes with positive mask values.
Reimplemented from pism::calving::IcebergRemover.
Definition at line 66 of file IcebergRemoverFEM.cc.
References pism::fem::Element2::add_contribution(), pism::IceModelVec2S::array(), pism::ParallelSection::check(), pism::ParallelSection::failed(), pism::petsc::VecArray::get(), pism::IceModelVec::get_from_proc0(), pism::mask::grounded(), pism::mask::icy(), label_connected_components(), pism::Component::m_grid, pism::calving::IcebergRemover::m_iceberg_mask, m_mask, pism::calving::IcebergRemover::m_mask_p0, pism::MASK_ICE_FREE_OCEAN, n, pism::fem::q1::n_chi, pism::PointsWithGhosts::next(), pism::fem::Element2::nodal_values(), pism::IceModelVec::put_on_proc0(), pism::fem::Element2::reset(), pism::IceModelVec::set(), pism::IceModelVec::stencil_width(), and pism::IceModelVec::update_ghosts().