PISM, A Parallel Ice Sheet Model: pism::ocean::sea_level::SeaLevel::SeaLevel
define_model_state_impl
diagnostics_impl
elevation
init
init_impl
m_input_model
m_sea_level
max_timestep_impl
SeaLevel
SeaLevel
ts_diagnostics_impl
update
update_impl
write_model_state_impl
~SeaLevel
SeaLevel() [1/2]
pism::ocean::sea_level::SeaLevel::SeaLevel (std::shared_ptr< const Grid > g, std::shared_ptr< SeaLevel > input)
Definition at line 31 of file SeaLevel.cc.
References pism::VariableMetadata::long_name(), m_sea_level, pism::array::Array::metadata(), and pism::VariableMetadata::units().