PISM, A Parallel Ice Sheet Model: pism::VariableMetadata::set_string
check_range
clear_all_doubles
clear_all_strings
DoubleAttrs
get_all_doubles
get_all_strings
get_n_spatial_dimensions
get_name
get_number
get_numbers
get_output_type
get_string
get_time_independent
has_attribute
has_attributes
m_doubles
m_n_spatial_dims
m_output_type
m_short_name
m_strings
m_time_independent
m_unit_system
report_range
report_to_stdout
set_name
set_number
set_numbers
set_output_type
set_string
set_time_independent
StringAttrs
unit_system
VariableMetadata
~VariableMetadata
set_string()
void pism::VariableMetadata::set_string (const std::string & name, const std::string & value)
Set a string attribute.
Definition at line 340 of file VariableMetadata.cc.
References pism::units::are_convertible(), pism::RuntimeError::formatted(), get_string(), m_strings, m_unit_system, PISM_ERROR_LOCATION, and set_name().
Referenced by pism::surface::diagnostics::Accumulation::Accumulation(), pism::IceModel::allocate_storage(), pism::IceRegionalModel::allocate_storage(), pism::diagnostics::BasalFlux::BasalFlux(), pism::energy::BedThermalUnit::BedThermalUnit(), pism::diagnostics::BMBSplit::BMBSplit(), pism::IceModel::bootstrap_2d(), pism::diagnostics::CalvingFlux::CalvingFlux(), pism::energy::CHSystem::CHSystem(), pism::IceModel::compute_lat_lon(), pism::hydrology::diagnostics::ConservationErrorFlux::ConservationErrorFlux(), pism::diagnostics::ConservationErrorFlux::ConservationErrorFlux(), pism::io::define_time(), pism::DiagAverageRate< M >::DiagAverageRate(), pism::diagnostics::DischargeFlux::DischargeFlux(), pism::hydrology::diagnostics::DomainBoundaryFlux::DomainBoundaryFlux(), pism::energy::EnergyModel::EnergyModel(), pism::epsg_to_cf(), pism::FractureDensity::FractureDensity(), pism::frontalmelt::diagnostics::FrontalMeltRate::FrontalMeltRate(), pism::frontalmelt::diagnostics::FrontalMeltRetreatRate::FrontalMeltRetreatRate(), pism::Geometry::Geometry(), pism::hydrology::diagnostics::GroundedMarginFlux::GroundedMarginFlux(), pism::hydrology::diagnostics::GroundingLineFlux::GroundingLineFlux(), pism::diagnostics::GroundingLineFlux::GroundingLineFlux(), pism::diagnostics::scalar::IceAreaGlacierized::IceAreaGlacierized(), pism::diagnostics::scalar::IceAreaGlacierizedColdBase::IceAreaGlacierizedColdBase(), pism::diagnostics::scalar::IceAreaGlacierizedGrounded::IceAreaGlacierizedGrounded(), pism::diagnostics::scalar::IceAreaGlacierizedShelf::IceAreaGlacierizedShelf(), pism::diagnostics::scalar::IceAreaGlacierizedTemperateBase::IceAreaGlacierizedTemperateBase(), pism::diagnostics::scalar::IceEnthalpy::IceEnthalpy(), pism::diagnostics::scalar::IceEnthalpyGlacierized::IceEnthalpyGlacierized(), pism::diagnostics::scalar::IceMass::IceMass(), pism::diagnostics::scalar::IceMassFluxAtGroundingLine::IceMassFluxAtGroundingLine(), pism::diagnostics::scalar::IceMassFluxBasal::IceMassFluxBasal(), pism::diagnostics::scalar::IceMassFluxBasalFloating::IceMassFluxBasalFloating(), pism::diagnostics::scalar::IceMassFluxBasalGrounded::IceMassFluxBasalGrounded(), pism::diagnostics::scalar::IceMassFluxCalving::IceMassFluxCalving(), pism::diagnostics::scalar::IceMassFluxConservationError::IceMassFluxConservationError(), pism::diagnostics::scalar::IceMassFluxDischarge::IceMassFluxDischarge(), pism::diagnostics::scalar::IceMassFluxSurface::IceMassFluxSurface(), pism::diagnostics::scalar::IceMassGlacierized::IceMassGlacierized(), pism::diagnostics::scalar::IceMassNotDisplacingSeaWater::IceMassNotDisplacingSeaWater(), pism::diagnostics::scalar::IceMassRateOfChange::IceMassRateOfChange(), pism::diagnostics::scalar::IceMassRateOfChangeDueToFlow::IceMassRateOfChangeDueToFlow(), pism::diagnostics::scalar::IceMassRateOfChangeGlacierized::IceMassRateOfChangeGlacierized(), pism::IceModel::IceModel(), pism::diagnostics::scalar::IceVolume::IceVolume(), pism::diagnostics::scalar::IceVolumeCold::IceVolumeCold(), pism::diagnostics::scalar::IceVolumeGlacierized::IceVolumeGlacierized(), pism::diagnostics::scalar::IceVolumeGlacierizedCold::IceVolumeGlacierizedCold(), pism::diagnostics::scalar::IceVolumeGlacierizedGrounded::IceVolumeGlacierizedGrounded(), pism::diagnostics::scalar::IceVolumeGlacierizedShelf::IceVolumeGlacierizedShelf(), pism::diagnostics::scalar::IceVolumeGlacierizedTemperate::IceVolumeGlacierizedTemperate(), pism::diagnostics::scalar::IceVolumeRateOfChange::IceVolumeRateOfChange(), pism::diagnostics::scalar::IceVolumeRateOfChangeGlacierized::IceVolumeRateOfChangeGlacierized(), pism::diagnostics::scalar::IceVolumeTemperate::IceVolumeTemperate(), pism::IceModelVec2T::init(), pism::Time_Calendar::init_from_file(), pism::Time_Calendar::init_from_input_file(), pism::SpatialVariableMetadata::init_internal(), pism::hydrology::SteadyState::init_time(), pism::ocean::sea_level::InitializationHelper::InitializationHelper(), pism::energy::LiquifiedIceFlux::LiquifiedIceFlux(), pism::diagnostics::scalar::MaxDiffusivity::MaxDiffusivity(), pism::diagnostics::scalar::MaxHorizontalVelocity::MaxHorizontalVelocity(), pism::IceModel::model_state_setup(), pism::ocean::PicoGeometry::PicoGeometry(), pism::IceModel::prepend_history(), pism::IceModel::process_options(), pism::Timeseries::read(), pism::io::read_attributes(), pism::stressbalance::SSATestCase::report_netcdf(), pism::hydrology::Routing::Routing(), pism::diagnostics::scalar::SeaLevelRisePotential::SeaLevelRisePotential(), pism::IceModelVec::set_attrs(), pism::NetCDFConfig::set_flag_impl(), pism::NetCDFConfig::set_string_impl(), pism::TSDiagnostic::set_units(), pism::stressbalance::SSA::SSA(), pism::stressbalance::SSATestCase::SSATestCase(), pism::hydrology::diagnostics::SubglacialWaterFlux::SubglacialWaterFlux(), pism::diagnostics::SurfaceFlux::SurfaceFlux(), pism::surface::diagnostics::SurfaceMelt::SurfaceMelt(), pism::surface::diagnostics::SurfaceRunoff::SurfaceRunoff(), pism::surface::TemperatureIndex::TemperatureIndex(), pism::diagnostics::TendencyOfIceAmountDueToFlow::TendencyOfIceAmountDueToFlow(), pism::hydrology::diagnostics::TendencyOfWaterMass::TendencyOfWaterMass(), pism::hydrology::diagnostics::TendencyOfWaterMassDueToFlow::TendencyOfWaterMassDueToFlow(), pism::diagnostics::scalar::TimeStepLength::TimeStepLength(), pism::hydrology::diagnostics::TotalInputRate::TotalInputRate(), pism::surface::diagnostics::TotalSurfaceAccumulation::TotalSurfaceAccumulation(), pism::surface::diagnostics::TotalSurfaceMelt::TotalSurfaceMelt(), pism::surface::diagnostics::TotalSurfaceRunoff::TotalSurfaceRunoff(), pism::TSDiagnostic::TSDiagnostic(), pism::hydrology::diagnostics::WaterInputFlux::WaterInputFlux(), pism::atmosphere::WeatherStation::WeatherStation(), pism::write(), pism::IceModel::write_metadata(), and pism::atmosphere::YearlyCycle::YearlyCycle().