PISM, A Parallel Ice Sheet Model: pism::IceModelVec::get_name
AccessList
add
allocate_proc0_copy
begin_access
check_array_indices
checkCompatibility
checksum
ConstPtr
copy_from
copy_from_vec
copy_to_vec
define
dm
dump
end_access
fletcher64
get_dof
get_from_proc0
get_from_proc0
get_name
grid
IceModelVec
IceModelVec
inc_state_counter
levels
m_array
m_impl
metadata
metadata
ndims
ndof
norm
norm_all
operator=
print_checksum
Ptr
put_on_proc0
put_on_proc0
range
read
read
read_attributes
read_impl
regrid
regrid
regrid_impl
scale
set
set_attrs
set_begin_access_use_dof
set_dof
set_name
set_time_independent
shape
shift
size
state_counter
stencil_width
update_ghosts
update_ghosts
vec
write
write
write_impl
~IceModelVec
get_name()
const std::string & pism::IceModelVec::get_name () const
Get the name of an IceModelVec object.
This is the name used to refer to this object in PISM (e.g. via the Vars class), not the name of the corresponding NetCDF variable. (The problem is that one IceModelVec instance may correspond to several NetCDF variables. Use metadata(...).get_name() to get the name of NetCDF variables an IceModelVec is saved to.)
Definition at line 375 of file iceModelVec.cc.
References m_impl, and pism::IceModelVec::Impl::name.
Referenced by pism::Vars::add(), pism::IceModelVec2S::allocate_copy(), pism::IceModelVec3::allocate_copy(), pism::IceModelVec2V::allocate_copy(), pism::DiagAverageRate< M >::DiagAverageRate(), pism::DiagAverageRate< M >::init_impl(), read_attributes(), regrid(), and pism::set_contains().