PISM, A Parallel Ice Sheet Model: pism::atmosphere::YearlyCycle::init_impl
air_temperature_impl
begin_pointwise_access_impl
define_model_state_impl
diagnostics_impl
end_pointwise_access_impl
init_impl
init_internal
init_timeseries_impl
m_air_temp_mean_annual
m_air_temp_mean_summer
m_cosine_cycle
m_precipitation
m_reference
m_snow_temp_summer_day
mean_summer_temp
precip_time_series_impl
precipitation_impl
temp_time_series_impl
update_impl
write_model_state_impl
YearlyCycle
~YearlyCycle
init_impl()
void pism::atmosphere::YearlyCycle::init_impl (const Geometry & geometry) protected virtual
Reads in the precipitation data from the input file.
Implements pism::atmosphere::AtmosphereModel.
Reimplemented in pism::atmosphere::SeaRISEGreenland, pism::atmosphere::PIK, and pism::atmosphere::CosineYearlyCycle.
Definition at line 65 of file YearlyCycle.cc.
References pism::InputOptions::filename, pism::INIT_BOOTSTRAP, init_internal(), pism::Component::m_config, pism::Component::m_grid, pism::process_input_options(), pism::InputOptions::record, and pism::InputOptions::type.
Referenced by pism::atmosphere::PIK::init_impl(), and pism::atmosphere::SeaRISEGreenland::init_impl().