PISM, A Parallel Ice Sheet Model: pism::PointsWithGhosts::next
i
j
m_done
m_i
m_i_first
m_i_last
m_j
m_j_first
m_j_last
next
operator bool
PointsWithGhosts
next()
void pism::PointsWithGhosts::next () inline
Definition at line 381 of file IceGrid.hh.
References m_done, m_i, m_i_first, m_i_last, m_j, m_j_first, and m_j_last.
Referenced by pism::IceModelVec2S::absmax(), pism::IceModelVec2Stag::absmaxcomponents(), pism::add_2d(), pism::surface::ForceThickness::adjust_mass_flux(), pism::hydrology::Routing::advective_fluxes(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::GeometryEvolution::apply_mass_fluxes(), pism::Poisson::assemble_matrix(), pism::stressbalance::SSAFD::assemble_matrix(), pism::stressbalance::SSAFD::assemble_rhs(), pism::Poisson::assemble_rhs(), pism::IceModelVec2T::average(), pism::rheology::averaged_hardness_vec(), pism::ocean::Pico::beckmann_goosse(), pism::bedrock_surface_temperature(), pism::energy::BTU_Full::bootstrap(), pism::energy::BTU_Verification::bootstrap(), pism::IceRegionalModel::bootstrap_2d(), pism::energy::bootstrap_ice_temperature(), pism::stressbalance::SSAFEM::cache_inputs(), pism::hydrology::check_bounds(), pism::check_maximum_ice_thickness(), pism::check_minimum_ice_thickness(), pism::hydrology::Distributed::check_P_bounds(), pism::IceModel::combine_basal_melt_rate(), pism::diagnostics::scalar::IceMassRateOfChangeDueToFlow::compute(), pism::diagnostics::scalar::IceVolumeGlacierizedGrounded::compute(), pism::diagnostics::scalar::IceVolumeGlacierizedShelf::compute(), pism::diagnostics::scalar::IceMassFluxDischarge::compute(), pism::diagnostics::scalar::IceMassFluxCalving::compute(), pism::stressbalance::PSB_wvel::compute(), pism::stressbalance::compute_2D_principal_strain_rates(), pism::stressbalance::compute_2D_stresses(), pism::stressbalance::SIAFD::compute_3d_horizontal_velocity(), pism::ocean::OceanModel::compute_average_water_column_pressure(), pism::stressbalance::Blatter::compute_averaged_velocity(), pism::stressbalance::ShallowStressBalance::compute_basal_frictional_heating(), pism::hydrology::Hydrology::compute_basal_melt_rate(), pism::ocean::Pico::compute_box_area(), pism::ocean::Pico::compute_box_average(), pism::ocean::PicoGeometry::compute_box_mask(), pism::hydrology::Routing::compute_conductivity(), pism::ocean::PicoGeometry::compute_continental_shelf_mask(), pism::energy::compute_cts(), pism::stressbalance::SIAFD::compute_diffusive_flux(), pism::stressbalance::SIAFD::compute_diffusivity(), pism::ocean::PicoGeometry::compute_distances_cf(), pism::ocean::PicoGeometry::compute_distances_gl(), pism::stressbalance::SSAFD_Regional::compute_driving_stress(), pism::stressbalance::SSA::compute_driving_stress(), pism::energy::compute_enthalpy(), pism::energy::compute_enthalpy_cold(), pism::GeometryEvolution::compute_flux_divergence(), pism::IceModel::compute_geometry_change(), pism::compute_grounded_cell_fraction(), pism::stressbalance::SSAFD::compute_hardav_staggered(), pism::stressbalance::SIAFD::compute_I(), pism::ocean::PicoGeometry::compute_ice_rises(), pism::ocean::PicoGeometry::compute_ice_shelf_mask(), pism::atmosphere::diagnostics::AirTemperatureSnapshot::compute_impl(), pism::energy::diagnostics::Enthalpy::compute_impl(), pism::diagnostics::FluxStaggered::compute_impl(), pism::hydrology::diagnostics::RelativeBasalWaterPressure::compute_impl(), pism::hydrology::diagnostics::EffectiveBasalWaterPressure::compute_impl(), pism::diagnostics::IceMarginPressureDifference::compute_impl(), pism::diagnostics::HardnessAverage::compute_impl(), pism::diagnostics::Rank::compute_impl(), pism::diagnostics::Temperature::compute_impl(), pism::diagnostics::TemperaturePA::compute_impl(), pism::diagnostics::TemperaturePABasal::compute_impl(), pism::diagnostics::IceEnthalpySurface::compute_impl(), pism::diagnostics::TemperatureBasal::compute_impl(), pism::diagnostics::TemperatureSurface::compute_impl(), pism::diagnostics::TemperateIceThickness::compute_impl(), pism::diagnostics::TemperateIceThicknessBasal::compute_impl(), pism::diagnostics::IceAreaFraction::compute_impl(), pism::diagnostics::IceAreaFractionGrounded::compute_impl(), pism::diagnostics::HeightAboveFloatation::compute_impl(), pism::diagnostics::IceMass::compute_impl(), pism::diagnostics::BedTopographySeaLevelAdjusted::compute_impl(), pism::diagnostics::IceHardness::compute_impl(), pism::diagnostics::IceViscosity::compute_impl(), pism::diagnostics::TendencyOfIceAmount::compute_impl(), pism::stressbalance::SSB_beta::compute_impl(), pism::stressbalance::SSB_taud::compute_impl(), pism::stressbalance::SSB_taub::compute_impl(), pism::stressbalance::PSB_velbar::compute_impl(), pism::stressbalance::PSB_flux::compute_impl(), pism::stressbalance::PSB_flux_mag::compute_impl(), pism::stressbalance::PSB_velbase_mag::compute_impl(), pism::stressbalance::PSB_velsurf_mag::compute_impl(), pism::stressbalance::PSB_velsurf::compute_impl(), pism::stressbalance::PSB_wvelsurf::compute_impl(), pism::stressbalance::PSB_wvelbase::compute_impl(), pism::stressbalance::PSB_velbase::compute_impl(), pism::stressbalance::PSB_pressure::compute_impl(), pism::stressbalance::PSB_tauxz::compute_impl(), pism::stressbalance::PSB_tauyz::compute_impl(), pism::stressbalance::PSB_vonmises_stress::compute_impl(), pism::GeometryEvolution::compute_interface_fluxes(), pism::RegionalGeometryEvolution::compute_interface_fluxes(), pism::ocean::PicoGeometry::compute_lakes(), pism::energy::compute_liquid_water_fraction(), pism::bed::compute_load(), pism::stressbalance::SSAFEM::compute_local_function(), pism::hydrology::EmptyingProblem::compute_mask(), pism::GeometryCalculator::compute_mask(), pism::surface::Elevation::compute_mass_flux(), pism::stressbalance::BlatterMod::compute_max_diffusivity(), pism::FrontRetreat::compute_modified_mask(), pism::compute_node_types(), pism::stressbalance::SSAFD::compute_nuH_staggered(), pism::stressbalance::SSAFD::compute_nuH_staggered_cfbc(), pism::ocean::Pico::compute_ocean_input_per_basin(), pism::ocean::PicoGeometry::compute_ocean_mask(), pism::IceModel::compute_original_ice_fraction(), pism::hydrology::Hydrology::compute_overburden_pressure(), pism::hydrology::EmptyingProblem::compute_potential(), pism::hydrology::EmptyingProblem::compute_raw_potential(), pism::frontalmelt::FrontalMelt::compute_retreat_rate(), pism::hydrology::diagnostics::compute_sinks(), pism::compute_strain_heating_errors(), pism::IceCompModel::compute_strain_heating_errors(), pism::GeometryCalculator::compute_surface(), pism::GeometryEvolution::compute_surface_and_basal_mass_balance(), pism::RegionalGeometryEvolution::compute_surface_and_basal_mass_balance(), pism::stressbalance::SIAFD_Regional::compute_surface_gradient(), pism::hydrology::Hydrology::compute_surface_input_rate(), pism::IceModel::compute_temperate_base_fraction(), pism::surface::Elevation::compute_temperature(), pism::energy::compute_temperature(), pism::hydrology::EmptyingProblem::compute_velocity(), pism::hydrology::Routing::compute_velocity(), pism::stressbalance::StressBalance::compute_vertical_velocity(), pism::stressbalance::StressBalance::compute_volumetric_strain_heating(), pism::IceCompModel::computeBasalMeltRateErrors(), pism::IceCompModel::computeBasalTemperatureErrors(), pism::IceCompModel::computeGeometryErrors(), pism::IceCompModel::computeIceBedrockTemperatureErrors(), pism::computeSurfaceVelocityErrors(), pism::IceCompModel::computeSurfaceVelocityErrors(), pism::IceCompModel::computeTemperatureErrors(), pism::inverse::IPDesignVariableParameterization::convertFromDesignVariable(), pism::inverse::IPDesignVariableParameterization::convertToDesignVariable(), pism::copy_2d(), pism::stressbalance::Blatter::copy_solution(), pism::stressbalance::copy_staggered_vec(), pism::count_CFL_violations(), pism::energy::cryo_hydrologic_warming_flux(), pism::hydrology::NullTransport::diffuse_till_water(), pism::IceModelVec2T::discard(), pism::inverse::IPMeanSquareFunctional2S::dot(), pism::inverse::IPMeanSquareFunctional2V::dot(), pism::surface::SurfaceModel::dummy_accumulation(), pism::surface::SurfaceModel::dummy_runoff(), pism::hydrology::diagnostics::effective_water_velocity(), pism::ocean::eikonal_equation(), pism::hydrology::Hydrology::enforce_bounds(), pism::IceModel::enforce_consistency_of_geometry(), pism::Geometry::ensure_consistency(), pism::GeometryEvolution::ensure_nonnegativity(), pism::enthalpy_from_temperature_cold(), pism::atmosphere::era_interim(), pism::atmosphere::era_interim_lon(), pism::atmosphere::era_interim_sin(), pism::ocean::extend_basal_melt_rates(), pism::IceModelVec3::extract_surface(), pism::fem::DirichletData_Scalar::fix_jacobian(), pism::fem::DirichletData_Vector::fix_jacobian(), pism::fem::DirichletData_Scalar::fix_residual(), pism::fem::DirichletData_Vector::fix_residual(), pism::fem::DirichletData_Scalar::fix_residual_homogeneous(), pism::fem::DirichletData_Vector::fix_residual_homogeneous(), pism::stressbalance::SSAFD::fracture_induced_softening(), pism::generate_mound_topography(), pism::generate_trough_topography(), pism::stressbalance::Blatter::get_basal_velocity(), pism::ocean::PicoGeometry::get_basin_neighbors(), pism::IceModelVec::get_dof(), pism::IceModelVec2T::get_record(), pism::IceCompModel::getCompSourcesTestFG(), pism::inverse::IPMeanSquareFunctional2S::gradientAt(), pism::inverse::IPLogRatioFunctional::gradientAt(), pism::inverse::IPLogRelativeFunctional::gradientAt(), pism::inverse::IPMeanSquareFunctional2V::gradientAt(), pism::inverse::gradientFD(), pism::grounding_line_flux(), pism::atmosphere::huybrechts_dewolde(), pism::hydrology::diagnostics::hydraulic_potential(), pism::ice_area(), pism::IceModel::ice_area_cold(), pism::ice_area_floating(), pism::ice_area_grounded(), pism::IceModel::ice_area_temperate(), pism::ice_bottom_surface(), pism::ice_volume(), pism::IceModel::ice_volume_cold(), pism::ice_volume_not_displacing_seawater(), pism::IceModel::ice_volume_temperate(), pism::ocean::PicoGeometry::identify_calving_front_connection(), pism::stressbalance::Blatter::init_2d_parameters(), pism::stressbalance::BlatterTestCFBC::init_2d_parameters(), pism::stressbalance::Blatter::init_ice_hardness(), pism::surface::EISMINTII::initialize_using_formulas(), pism::stressbalance::SSATestCaseCFBC::initializeSSACoefficients(), pism::stressbalance::SSATestCaseConst::initializeSSACoefficients(), pism::stressbalance::SSATestCaseExp::initializeSSACoefficients(), pism::stressbalance::SSATestCasePlug::initializeSSACoefficients(), pism::stressbalance::SSATestCaseI::initializeSSACoefficients(), pism::stressbalance::SSATestCaseJ::initializeSSACoefficients(), pism::IceCompModel::initTestABCDH(), pism::IceCompModel::initTestFG(), pism::energy::TemperatureModel_Verification::initTestFG(), pism::IceCompModel::initTestL(), pism::energy::TemperatureModel_Verification::initTestsKO(), pism::surface::diagnostics::integrate(), pism::lapse_rate_correction(), main(), pism::atmosphere::martin2011(), pism::atmosphere::martin_huybrechts_dewolde(), pism::IceModelVec2S::mask_by(), pism::diagnostics::scalar::mass_change(), pism::ocean::PIK::mass_flux(), pism::IceModelVec2S::max(), pism::FrontRetreat::max_timestep(), pism::max_timestep_cfl_2d(), pism::max_timestep_cfl_3d(), pism::ocean::Constant::melting_point_temperature(), pism::ocean::PIK::melting_point_temperature(), pism::IceModelVec2S::min(), pism::surface::diagnostics::SurfaceMelt::model_input(), pism::surface::diagnostics::SurfaceRunoff::model_input(), pism::surface::diagnostics::Accumulation::model_input(), pism::stressbalance::SSAFEM::monitor_function(), pism::inverse::IPLogRatioFunctional::normalize(), pism::inverse::IPLogRelativeFunctional::normalize(), pism::inverse::IPMeanSquareFunctional2S::normalize(), pism::inverse::IPMeanSquareFunctional2V::normalize(), pism::hydrology::Distributed::P_from_W_steady(), pism::stressbalance::SSAFD::picard_manager(), pism::ocean::Pico::process_box1(), pism::ocean::Pico::process_other_boxes(), pism::io::regrid(), pism::ocean::relabel(), pism::remove_narrow_tongues(), pism::stressbalance::SSATestCase::report(), pism::diagnostics::TendencyOfIceAmount::reset_impl(), pism::IceCompModel::reset_thickness_test_A(), pism::GeometryEvolution::residual_redistribution_iteration(), pism::inverse::IP_SSAHardavForwardProblem::set_design(), pism::inverse::IP_SSATaucForwardProblem::set_design(), pism::IceModelVec::set_dof(), pism::stressbalance::Blatter::set_initial_guess(), pism::set_no_model_strip(), pism::set_no_model_yield_stress(), pism::ocean::Pico::set_ocean_input_fields(), pism::IceModelVec2T::set_record(), pism::IceModelVec2S::set_to_magnitude(), pism::setInitStateF(), pism::stressbalance::BedSmoother::smoothed_thk(), pism::ocean::PicoGeometry::split_ice_shelves(), pism::staggered_to_regular(), pism::IceModelVec2S::sum(), pism::IceModelVec3::sum_columns(), pism::stressbalance::SIAFD::surface_gradient_eta(), pism::stressbalance::SIAFD::surface_gradient_haseloff(), pism::stressbalance::SIAFD::surface_gradient_mahaffy(), pism::IceCompModel::test_V_init(), pism::stressbalance::BedSmoother::theta(), pism::MohrCoulombYieldStress::till_friction_angle(), pism::total_grounding_line_flux(), pism::energy::total_ice_enthalpy(), pism::stressbalance::BlatterMod::transfer(), pism::hydrology::EmptyingProblem::update(), pism::calving::HayhurstCalving::update(), pism::calving::vonMisesCalving::update(), pism::calving::EigenCalving::update(), pism::stressbalance::ConstantInColumn::update(), pism::stressbalance::WeertmanSliding::update(), pism::FractureDensity::update(), pism::AgeModel::update(), pism::hydrology::Hydrology::update(), pism::calving::CalvingAtThickness::update(), pism::PrescribedRetreat::update(), pism::calving::FloatKill::update(), pism::surface::Verification::update_ABCDH(), pism::surface::Verification::update_FG(), pism::energy::BTU_Full::update_flux_through_top_surface(), pism::IceModel::update_fracture_density(), pism::FrontRetreat::update_geometry(), pism::frontalmelt::Constant::update_impl(), pism::frontalmelt::DischargeGiven::update_impl(), pism::frontalmelt::DischargeRouting::update_impl(), pism::frontalmelt::Given::update_impl(), pism::atmosphere::ElevationChange::update_impl(), pism::atmosphere::Frac_P::update_impl(), pism::atmosphere::SeaRISEGreenland::update_impl(), pism::ocean::Delta_MBP::update_impl(), pism::ocean::Frac_MBP::update_impl(), pism::ocean::GivenTH::update_impl(), pism::surface::PIK::update_impl(), pism::surface::ElevationChange::update_impl(), pism::surface::ISMIP6::update_impl(), pism::surface::TemperatureIndex::update_impl(), pism::calving::IcebergRemover::update_impl(), pism::calving::IcebergRemoverFEM::update_impl(), pism::energy::BTU_Full::update_impl(), pism::bed::PointwiseIsostasy::update_impl(), pism::MohrCoulombYieldStress::update_impl(), pism::diagnostics::BMBSplit::update_impl(), pism::diagnostics::TendencyOfIceAmountDueToFlow::update_impl(), pism::diagnostics::SurfaceFlux::update_impl(), pism::diagnostics::BasalFlux::update_impl(), pism::diagnostics::ConservationErrorFlux::update_impl(), pism::diagnostics::DischargeFlux::update_impl(), pism::diagnostics::CalvingFlux::update_impl(), pism::energy::CHSystem::update_impl(), pism::energy::EnthalpyModel::update_impl(), pism::energy::TemperatureModel::update_impl(), pism::hydrology::NullTransport::update_impl(), pism::energy::EnthalpyModel_Regional::update_impl(), pism::GeometryEvolution::update_in_place(), pism::surface::Verification::update_L(), pism::stressbalance::SSAFD::update_nuH_viewers(), pism::hydrology::Distributed::update_P(), pism::surface::FaustoGrevePDDObject::update_temp_mj(), pism::hydrology::Routing::update_W(), pism::hydrology::Routing::update_Wtill(), pism::inverse::IPMeanSquareFunctional2S::valueAt(), pism::inverse::IPLogRatioFunctional::valueAt(), pism::inverse::IPLogRelativeFunctional::valueAt(), pism::inverse::IPMeanSquareFunctional2V::valueAt(), pism::hydrology::Routing::W_change_due_to_flow(), pism::hydrology::wall_melt(), pism::hydrology::Routing::water_thickness_staggered(), pism::stressbalance::SSATestCase::write(), and pism::stressbalance::zero_above_ice().