PISM, A Parallel Ice Sheet Model: pism::RuntimeError::add_context
add_context
add_context
formatted
Hook
m_context
m_location
print
RuntimeError
set_hook
sm_hook
~RuntimeError
add_context() [2/2]
void pism::RuntimeError::add_context (const std::string & message)
Add a message providing some context. This way we can (sort of) get a stack trace even though C++ exceptions do not provide one.
Definition at line 66 of file error_handling.cc.
References m_context.
Referenced by add_context(), pism::File::append_history(), pism::io::append_time(), pism::File::attribute_name(), pism::File::attribute_type(), pism::File::close(), pism::io::define_dimension(), pism::File::define_dimension(), pism::io::define_time(), pism::File::define_variable(), pism::File::dimension_length(), pism::File::dimension_type(), pism::File::dimensions(), pism::File::enddef(), pism::File::find_dimension(), pism::File::find_variable(), pism::IceGrid::FromFile(), pism::Config::get_number(), pism::Config::get_numbers(), pism::get_projection_info(), pism::IceGrid::IceGrid(), pism::IceModelVec2T::init(), pism::IceModel::init_extras(), pism::Time::init_from_file(), pism::IceModel::init_snapshots(), pism::IceModel::init_timeseries(), pism::ScalarForcing::initialize(), pism::options::Integer::Integer(), pism::File::nattributes(), pism::File::nrecords(), pism::File::nvariables(), pism::File::open(), pism::parse_date(), pism::Time::parse_interval_length(), pism::Time::parse_list(), pism::io::read_attributes(), pism::File::read_dimension(), pism::io::read_distributed_array(), pism::File::read_double_attribute(), pism::File::read_text_attribute(), pism::io::read_time_bounds(), pism::io::read_timeseries(), pism::io::read_valid_range(), pism::File::read_variable(), pism::File::read_variable_transposed(), pism::options::Real::Real(), pism::File::redef(), pism::IceModelVec::regrid(), pism::io::regrid_vec_generic(), pism::File::remove_attribute(), pism::IceGrid::Shallow(), pism::energy::enthSystemCtx::solve(), pism::AgeColumnSystem::solve(), pism::energy::tempSystemCtx::solveThisColumn(), pism::IceModel::step(), pism::File::sync(), pism::Time::Time(), pism::stressbalance::StressBalance::update(), pism::File::variable_name(), pism::File::write_attribute(), pism::io::write_attributes(), pism::File::write_distributed_array(), pism::io::write_time_bounds(), pism::io::write_timeseries(), and pism::File::write_variable().