PISM, A Parallel Ice Sheet Model: pism::File::nrecords
append_history
attribute_name
attribute_type
backend
close
com
define_dimension
define_variable
dimension_length
dimension_type
dimensions
enddef
File
File
filename
find_dimension
find_variable
find_variable
m_impl
nattributes
nrecords
nrecords
nvariables
open
operator=
read_dimension
read_double_attribute
read_text_attribute
read_variable
read_variable_transposed
redef
remove_attribute
set_compression_level
sync
variable_name
write_attribute
write_attribute
write_distributed_array
write_variable
~File
nrecords() [1/2]
unsigned int pism::File::nrecords () const
Get the number of records. Uses the length of an unlimited dimension.
Definition at line 313 of file File.cc.
References pism::RuntimeError::add_context(), dimension_length(), filename(), m_impl, and pism::File::Impl::nc.
Referenced by pism::Isochrones::bootstrap(), pism::array::Forcing::Forcing(), pism::stressbalance::Blatter::init_impl(), pism::stressbalance::SSA::init_impl(), pism::ocean::InitializationHelper::init_impl(), pism::ocean::sea_level::InitializationHelper::init_impl(), pism::surface::InitializationHelper::init_impl(), pism::array::Forcing::init_periodic_data(), pism::process_input_options(), pism::Isochrones::restart(), and write_distributed_array().