PISM, A Parallel Ice Sheet Model: pism::ocean::Pico::write_model_state_impl
beckmann_goosse
compute_box_area
compute_box_average
compute_ocean_input_per_basin
define_model_state_impl
diagnostics_impl
init_impl
m_basal_melt_rate
m_geometry
m_n_basins
m_n_boxes
m_n_shelves
m_overturning
m_salinity_ocean
m_Soc
m_Soc_box0
m_T_star
m_theta_ocean
m_Toc
m_Toc_box0
max_timestep_impl
Pico
process_box1
process_other_boxes
set_ocean_input_fields
update_impl
write_model_state_impl
~Pico
write_model_state_impl()
void pism::ocean::Pico::write_model_state_impl (const File & output) const protected virtual
The default (empty implementation).
Reimplemented from pism::ocean::OceanModel.
Definition at line 189 of file Pico.cc.
References pism::ocean::PicoGeometry::basin_mask(), m_geometry, m_overturning, m_Soc_box0, m_Toc_box0, pism::IceModelVec::write(), and pism::ocean::OceanModel::write_model_state_impl().