PISM, A Parallel Ice Sheet Model: pism::energy::TemperatureModel::initialize_impl
bootstrap_impl
column_drainage
define_model_state_impl
initialize_impl
m_ice_temperature
restart_impl
temperature
TemperatureModel
update_impl
update_impl
write_model_state_impl
initialize_impl()
void pism::energy::TemperatureModel::initialize_impl (const IceModelVec2S & basal_melt_rate, const IceModelVec2S & ice_thickness, const IceModelVec2S & surface_temperature, const IceModelVec2S & climatic_mass_balance, const IceModelVec2S & basal_heat_flux) protected virtual
Implements pism::energy::EnergyModel.
Reimplemented in pism::energy::TemperatureModel_Verification.
Definition at line 92 of file TemperatureModel.cc.
References pism::energy::EnergyModel::basal_melt_rate(), pism::energy::bootstrap_ice_temperature(), pism::energy::compute_enthalpy_cold(), pism::IceModelVec2S::copy_from(), pism::energy::EnergyModel::m_basal_melt_rate, pism::energy::EnergyModel::m_ice_enthalpy, m_ice_temperature, pism::Component::m_log, pism::Component::regrid(), pism::Component::REGRID_WITHOUT_REGRID_VARS, and pism::IceModelVec::state_counter().
Referenced by pism::energy::TemperatureModel_Verification::initialize_impl().