PISM, A Parallel Ice Sheet Model: pism::PCFactory::key_list
add_model
add_modifier
create
create
key_list
m_grid
m_models
m_modifiers
m_parameter
model
modifier
PCFactory
~PCFactory
key_list()
template<class Model > template<typename T > std::string pism::PCFactory< Model >::key_list (std::map< std::string, T > list) inline protected
Definition at line 83 of file PCFactory.hh.
References pism::join().
Referenced by pism::PCFactory< Model >::model(), and pism::PCFactory< Model >::modifier().