PISM, A Parallel Ice Sheet Model: pism::Diagnostic::set_attrs
compute
compute_impl
define
define_impl
define_state
define_state_impl
Diagnostic
init
init_impl
m_config
m_fill_value
m_grid
m_sys
m_vars
metadata
n_variables
Ptr
reset
reset_impl
set_attrs
to_external
to_internal
update
update_impl
wrap
write_state
write_state_impl
~Diagnostic
set_attrs()
void pism::Diagnostic::set_attrs (const std::string & long_name, const std::string & standard_name, const std::string & units, const std::string & glaciological_units, unsigned int N = 0) protected
A method for setting common variable attributes.
Definition at line 136 of file Diagnostic.cc.
References pism::RuntimeError::formatted(), m_config, m_vars, and PISM_ERROR_LOCATION.
Referenced by pism::surface::diagnostics::Accumulation::Accumulation(), pism::atmosphere::diagnostics::AirTemperature::AirTemperature(), pism::atmosphere::diagnostics::AirTemperatureSnapshot::AirTemperatureSnapshot(), pism::diagnostics::BasalFlux::BasalFlux(), pism::hydrology::diagnostics::BasalWaterPressure::BasalWaterPressure(), pism::hydrology::diagnostics::BasalWaterVelocity::BasalWaterVelocity(), pism::diagnostics::BedTopographySeaLevelAdjusted::BedTopographySeaLevelAdjusted(), pism::diagnostics::BMBSplit::BMBSplit(), pism::energy::BTU_geothermal_flux_at_ground_level::BTU_geothermal_flux_at_ground_level(), pism::diagnostics::CalvingFlux::CalvingFlux(), pism::CHHeatFlux::CHHeatFlux(), pism::CHLiquidWaterFraction::CHLiquidWaterFraction(), pism::CHTemperature::CHTemperature(), pism::hydrology::diagnostics::ConservationErrorFlux::ConservationErrorFlux(), pism::diagnostics::ConservationErrorFlux::ConservationErrorFlux(), pism::diagnostics::CTS::CTS(), pism::diagnostics::DischargeFlux::DischargeFlux(), pism::hydrology::diagnostics::DomainBoundaryFlux::DomainBoundaryFlux(), pism::hydrology::diagnostics::EffectiveBasalWaterPressure::EffectiveBasalWaterPressure(), pism::frontalmelt::diagnostics::FrontalMeltRate::FrontalMeltRate(), pism::frontalmelt::diagnostics::FrontalMeltRetreatRate::FrontalMeltRetreatRate(), pism::hydrology::diagnostics::GroundedMarginFlux::GroundedMarginFlux(), pism::hydrology::diagnostics::GroundingLineFlux::GroundingLineFlux(), pism::diagnostics::GroundingLineFlux::GroundingLineFlux(), pism::diagnostics::HardnessAverage::HardnessAverage(), pism::diagnostics::HeightAboveFloatation::HeightAboveFloatation(), pism::hydrology::diagnostics::HydraulicPotential::HydraulicPotential(), pism::diagnostics::IceAreaFraction::IceAreaFraction(), pism::diagnostics::IceAreaFractionFloating::IceAreaFractionFloating(), pism::diagnostics::IceAreaFractionGrounded::IceAreaFractionGrounded(), pism::diagnostics::IceBottomSurfaceElevation::IceBottomSurfaceElevation(), pism::diagnostics::IceEnthalpyBasal::IceEnthalpyBasal(), pism::diagnostics::IceEnthalpySurface::IceEnthalpySurface(), pism::diagnostics::IceHardness::IceHardness(), pism::diagnostics::IceMarginPressureDifference::IceMarginPressureDifference(), pism::diagnostics::IceMass::IceMass(), pism::diagnostics::IceSurfaceElevation::IceSurfaceElevation(), pism::diagnostics::IceThickness::IceThickness(), pism::diagnostics::IceViscosity::IceViscosity(), pism::diagnostics::LatLonBounds::LatLonBounds(), pism::diagnostics::LiquidFraction::LiquidFraction(), pism::atmosphere::diagnostics::MeanSummerTemperature::MeanSummerTemperature(), pism::ocean::diagnostics::PO_shelf_base_mass_flux::PO_shelf_base_mass_flux(), pism::ocean::diagnostics::PO_shelf_base_temperature::PO_shelf_base_temperature(), pism::atmosphere::diagnostics::Precipitation::Precipitation(), pism::surface::diagnostics::PS_climatic_mass_balance::PS_climatic_mass_balance(), pism::surface::diagnostics::PS_ice_surface_temp::PS_ice_surface_temp(), pism::surface::diagnostics::PS_layer_mass::PS_layer_mass(), pism::surface::diagnostics::PS_layer_thickness::PS_layer_thickness(), pism::surface::diagnostics::PS_liquid_water_fraction::PS_liquid_water_fraction(), pism::stressbalance::PSB_bfrict::PSB_bfrict(), pism::stressbalance::PSB_deviatoric_stresses::PSB_deviatoric_stresses(), pism::stressbalance::PSB_flux::PSB_flux(), pism::stressbalance::PSB_flux_mag::PSB_flux_mag(), pism::stressbalance::PSB_pressure::PSB_pressure(), pism::stressbalance::PSB_strain_rates::PSB_strain_rates(), pism::stressbalance::PSB_strainheat::PSB_strainheat(), pism::stressbalance::PSB_tauxz::PSB_tauxz(), pism::stressbalance::PSB_tauyz::PSB_tauyz(), pism::stressbalance::PSB_uvel::PSB_uvel(), pism::stressbalance::PSB_velbar::PSB_velbar(), pism::stressbalance::PSB_velbar_mag::PSB_velbar_mag(), pism::stressbalance::PSB_velbase::PSB_velbase(), pism::stressbalance::PSB_velbase_mag::PSB_velbase_mag(), pism::stressbalance::PSB_velsurf::PSB_velsurf(), pism::stressbalance::PSB_velsurf_mag::PSB_velsurf_mag(), pism::stressbalance::PSB_vonmises_stress::PSB_vonmises_stress(), pism::stressbalance::PSB_vvel::PSB_vvel(), pism::stressbalance::PSB_wvel::PSB_wvel(), pism::stressbalance::PSB_wvel_rel::PSB_wvel_rel(), pism::stressbalance::PSB_wvelbase::PSB_wvelbase(), pism::stressbalance::PSB_wvelsurf::PSB_wvelsurf(), pism::diagnostics::Rank::Rank(), pism::hydrology::diagnostics::RelativeBasalWaterPressure::RelativeBasalWaterPressure(), pism::stressbalance::SIAFD_diffusivity::SIAFD_diffusivity(), pism::stressbalance::SIAFD_diffusivity_staggered::SIAFD_diffusivity_staggered(), pism::stressbalance::SIAFD_h_x::SIAFD_h_x(), pism::stressbalance::SIAFD_h_y::SIAFD_h_y(), pism::stressbalance::SIAFD_schoofs_theta::SIAFD_schoofs_theta(), pism::stressbalance::SIAFD_thksmooth::SIAFD_thksmooth(), pism::stressbalance::SIAFD_topgsmooth::SIAFD_topgsmooth(), pism::ocean::sea_level::diagnostics::SL::SL(), pism::stressbalance::SSA_taud::SSA_taud(), pism::stressbalance::SSA_taud_mag::SSA_taud_mag(), pism::stressbalance::SSAFD_nuH::SSAFD_nuH(), pism::stressbalance::SSB_beta::SSB_beta(), pism::stressbalance::SSB_taub::SSB_taub(), pism::stressbalance::SSB_taub_mag::SSB_taub_mag(), pism::stressbalance::SSB_taud::SSB_taud(), pism::stressbalance::SSB_taud_mag::SSB_taud_mag(), pism::hydrology::diagnostics::SubglacialWaterFlux::SubglacialWaterFlux(), pism::diagnostics::SurfaceFlux::SurfaceFlux(), pism::surface::diagnostics::SurfaceMelt::SurfaceMelt(), pism::surface::diagnostics::SurfaceRunoff::SurfaceRunoff(), pism::diagnostics::TemperateIceThickness::TemperateIceThickness(), pism::diagnostics::TemperateIceThicknessBasal::TemperateIceThicknessBasal(), pism::diagnostics::Temperature::Temperature(), pism::diagnostics::TemperatureBasal::TemperatureBasal(), pism::diagnostics::TemperaturePA::TemperaturePA(), pism::diagnostics::TemperaturePABasal::TemperaturePABasal(), pism::diagnostics::TemperatureSurface::TemperatureSurface(), pism::diagnostics::TendencyOfIceAmount::TendencyOfIceAmount(), pism::diagnostics::TendencyOfIceAmountDueToFlow::TendencyOfIceAmountDueToFlow(), pism::hydrology::diagnostics::TendencyOfWaterMass::TendencyOfWaterMass(), pism::hydrology::diagnostics::TendencyOfWaterMassDueToFlow::TendencyOfWaterMassDueToFlow(), pism::diagnostics::ThicknessRateOfChange::ThicknessRateOfChange(), pism::hydrology::diagnostics::TotalInputRate::TotalInputRate(), pism::hydrology::diagnostics::WallMelt::WallMelt(), and pism::hydrology::diagnostics::WaterInputFlux::WaterInputFlux().