PISM, A Parallel Ice Sheet Model: pism::inverse::IPLogRelativeFunctional::gradientAt
gradientAt
IPLogRelativeFunctional
m_eps
m_normalization
m_u_observed
m_weights
normalize
valueAt
~IPLogRelativeFunctional
gradientAt()
void pism::inverse::IPLogRelativeFunctional::gradientAt (IceModelVec2V & x, IceModelVec2V & gradient) virtual
Computes the gradient of the functional at the vector x.
On an \(m\times n\) IceGrid, an IceModelVec \(x\) with \(d\) degrees of freedom will be \(d m n\)-dimensional with components \(x_i\). The gradient computed here is the vector of directional derivatives \(\nabla J\) of the functional \(J\) with respect to \(x\). Concretely, the \(i^{\rm th}\) component of \(\nabla J\) is
\[ \nabla J_i = \frac{\partial}{\partial x_i} J(x). \]
This vector is returned as gradient.
Implements pism::inverse::IPFunctional< IceModelVec2V >.
Definition at line 92 of file IPLogRelativeFunctional.cc.
References pism::IceModelVec2< T >::add(), m_eps, pism::inverse::IPFunctional< IceModelVec2V >::m_grid, m_normalization, m_u_observed, m_weights, pism::PointsWithGhosts::next(), pism::IceModelVec::set(), pism::Vector2::u, and pism::Vector2::v.