PISM, A Parallel Ice Sheet Model: pism::inverse::IPLogRatioFunctional::valueAt
gradientAt
IPLogRatioFunctional
m_eps
m_normalization
m_u_observed
m_weights
normalize
valueAt
~IPLogRatioFunctional
valueAt()
void pism::inverse::IPLogRatioFunctional::valueAt (IceModelVec2V & x, double * OUTPUT) virtual
Computes the value of the functional at the vector x.
Implements pism::inverse::IPFunctional< IceModelVec2V >.
Definition at line 65 of file IPLogRatioFunctional.cc.
References pism::IceModelVec2V::add(), pism::GlobalSum(), m_eps, pism::inverse::IPFunctional< IceModelVec2V >::m_grid, m_normalization, m_u_observed, m_weights, pism::PointsWithGhosts::next(), pism::Vector2::u, and pism::Vector2::v.