PISM, A Parallel Ice Sheet Model: pism::grid::InputGridInfo::report
dimension_types
filename
InputGridInfo
Lx
Ly
report
reset
t_len
variable_name
x
x0
y
y0
z
z_max
z_min
report()
void pism::grid::InputGridInfo::report (const Logger & log, int threshold, std::shared_ptr< units::System > s) const
Definition at line 1025 of file Grid.cc.
References pism::Grid::Lx(), pism::Grid::Ly(), pism::Logger::message(), pism::Grid::x(), pism::Grid::x0(), pism::Grid::y(), pism::Grid::y0(), and pism::Grid::z().
Referenced by pism::array::Array::regrid_impl(), and pism::array::Array3D::regrid_impl().