PISM, A Parallel Ice Sheet Model: pism::inverse::IP_L2NormFunctional2V::dot
dot
gradientAt
IP_L2NormFunctional2V
IP_L2NormFunctional2V
operator=
valueAt
~IP_L2NormFunctional2V
dot()
void pism::inverse::IP_L2NormFunctional2V::dot (IceModelVec2V & a, IceModelVec2V & b, double * OUTPUT) virtual
Computes the inner product \(Q(a, b)\).
Implements pism::inverse::IPInnerProductFunctional< IceModelVec2V >.
Definition at line 195 of file IP_L2NormFunctional.cc.
References pism::IceModelVec2Struct< T >::array(), pism::fem::Element2::evaluate(), pism::GlobalSum(), pism::fem::ElementIterator::lxm, pism::fem::ElementIterator::lxs, pism::fem::ElementIterator::lym, pism::fem::ElementIterator::lys, pism::inverse::IPFunctional< IceModelVec2V >::m_element, pism::inverse::IPFunctional< IceModelVec2V >::m_element_index, pism::inverse::IPFunctional< IceModelVec2V >::m_grid, pism::fem::MAX_QUADRATURE_SIZE, pism::fem::q1::n_chi, pism::fem::Element::n_pts(), pism::fem::Element2::nodal_values(), pism::fem::Element2::reset(), pism::Vector2::u, pism::Vector2::v, and pism::fem::Element::weight().