PISM, A Parallel Ice Sheet Model: pism::IceModelVec3::interpolate
ConstPtr
copy_from
get_column
get_column
IceModelVec3
IceModelVec3
interpolate
operator()
operator()
Ptr
set_column
set_column
~IceModelVec3
interpolate()
double pism::IceModelVec3::interpolate (int i, int j, double z) const
Return value of scalar quantity at level z (m) above base of ice (by linear interpolation).
Definition at line 102 of file iceModelVec3.cc.
References pism::IceModelVec::Impl::bsearch_accel, pism::IceModelVec::check_array_indices(), pism::fem::column(), pism::RuntimeError::formatted(), get_column(), pism::IceModelVec::levels(), pism::IceModelVec::m_array, pism::IceModelVec::m_impl, pism::IceModelVec::Impl::name, and PISM_ERROR_LOCATION.
Referenced by pism::computeSurfaceVelocityErrors(), pism::IceCompModel::computeSurfaceVelocityErrors(), and pism::extract_surface().