PISM, A Parallel Ice Sheet Model: pism::ParallelSection::failed
check
failed
m_com
m_failed
ParallelSection
reset
~ParallelSection
failed()
void pism::ParallelSection::failed ()
Indicates a failure of a parallel section.
This should be called from a catch (...) { ... } block only.
Definition at line 185 of file error_handling.cc.
References pism::handle_fatal_errors(), m_com, and m_failed.
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::GeometryEvolution::apply_mass_fluxes(), pism::inverse::IP_H1NormFunctional2S::assemble_form(), pism::Poisson::assemble_matrix(), pism::stressbalance::SSAFD::assemble_matrix(), pism::rheology::averaged_hardness_vec(), pism::bedrock_surface_temperature(), pism::energy::BTU_Verification::bootstrap(), pism::energy::bootstrap_ice_temperature(), pism::bed::LingleClark::bootstrap_impl(), pism::stressbalance::SSAFEM::cache_inputs(), pism::stressbalance::SSAFEM::cache_residual_cfbc(), pism::hydrology::check_bounds(), pism::check_minimum_ice_thickness(), pism::hydrology::Distributed::check_P_bounds(), pism::stressbalance::PSB_wvel::compute(), pism::ocean::OceanModel::compute_average_water_column_pressure(), pism::stressbalance::BedSmoother::compute_coefficients_on_proc0(), pism::ocean::PicoGeometry::compute_continental_shelf_mask(), pism::stressbalance::SIAFD::compute_diffusive_flux(), pism::stressbalance::SIAFD::compute_diffusivity(), pism::ocean::PicoGeometry::compute_distances_cf(), pism::ocean::PicoGeometry::compute_distances_gl(), pism::GeometryEvolution::compute_flux_divergence(), pism::compute_grounded_cell_fraction(), pism::stressbalance::SSAFD::compute_hardav_staggered(), pism::stressbalance::SIAFD::compute_I(), pism::atmosphere::diagnostics::AirTemperatureSnapshot::compute_impl(), pism::diagnostics::FluxStaggered::compute_impl(), pism::diagnostics::IceMarginPressureDifference::compute_impl(), pism::diagnostics::HardnessAverage::compute_impl(), pism::diagnostics::Temperature::compute_impl(), pism::diagnostics::TemperaturePA::compute_impl(), pism::diagnostics::TemperaturePABasal::compute_impl(), pism::diagnostics::TemperatureBasal::compute_impl(), pism::diagnostics::TemperatureSurface::compute_impl(), pism::diagnostics::TemperateIceThickness::compute_impl(), pism::diagnostics::TemperateIceThicknessBasal::compute_impl(), pism::diagnostics::IceAreaFraction::compute_impl(), pism::diagnostics::IceAreaFractionGrounded::compute_impl(), pism::diagnostics::HeightAboveFloatation::compute_impl(), pism::diagnostics::IceMass::compute_impl(), pism::diagnostics::IceHardness::compute_impl(), pism::diagnostics::IceViscosity::compute_impl(), pism::stressbalance::PSB_flux::compute_impl(), pism::stressbalance::PSB_pressure::compute_impl(), pism::stressbalance::PSB_tauxz::compute_impl(), pism::stressbalance::PSB_tauyz::compute_impl(), pism::GeometryEvolution::compute_interface_fluxes(), pism::RegionalGeometryEvolution::compute_interface_fluxes(), pism::ocean::PicoGeometry::compute_lakes(), pism::energy::compute_liquid_water_fraction(), pism::stressbalance::SSAFEM::compute_local_function(), pism::stressbalance::SSAFEM::compute_local_jacobian(), pism::surface::Elevation::compute_mass_flux(), pism::FrontRetreat::compute_modified_mask(), pism::compute_node_types(), pism::IceModel::compute_original_ice_fraction(), pism::frontalmelt::FrontalMelt::compute_retreat_rate(), pism::compute_strain_heating_errors(), pism::IceCompModel::compute_strain_heating_errors(), pism::GeometryEvolution::compute_surface_and_basal_mass_balance(), pism::RegionalGeometryEvolution::compute_surface_and_basal_mass_balance(), pism::IceModel::compute_temperate_base_fraction(), pism::surface::Elevation::compute_temperature(), pism::stressbalance::StressBalance::compute_volumetric_strain_heating(), pism::IceCompModel::computeBasalTemperatureErrors(), pism::IceCompModel::computeGeometryErrors(), pism::IceCompModel::computeSurfaceVelocityErrors(), pism::IceCompModel::computeTemperatureErrors(), pism::inverse::IPDesignVariableParameterization::convertFromDesignVariable(), pism::inverse::IPDesignVariableParameterization::convertToDesignVariable(), pism::IceModelVec3::copy_from(), pism::count_CFL_violations(), pism::energy::cryo_hydrologic_warming_flux(), pism::bed::LingleClark::elastic_load_response_matrix(), pism::Geometry::ensure_consistency(), pism::GeometryEvolution::ensure_nonnegativity(), pism::extract_surface(), pism::fem::DirichletData_Scalar::fix_jacobian(), pism::fem::DirichletData_Vector::fix_jacobian(), pism::IceModelVec::get_dof(), pism::inverse::gradientFD(), pism::grounding_line_flux(), pism::IceModel::ice_area_cold(), pism::IceModel::ice_area_temperate(), pism::ice_bottom_surface(), pism::IceModel::ice_volume_cold(), pism::IceModel::ice_volume_temperate(), pism::bed::LingleClark::init_impl(), pism::IceCompModel::initTestABCDH(), pism::energy::TemperatureModel_Verification::initTestsKO(), pism::label_components(), pism::ocean::PicoGeometry::label_tmp(), pism::bed::LingleClark::LingleClark(), pism::LocalInterpCtx::LocalInterpCtx(), pism::max_timestep_cfl_3d(), pism::stressbalance::SSAFEM::monitor_function(), pism::ocean::relabel(), pism::IceModelVec::set_dof(), pism::stressbalance::BedSmoother::smooth_the_bed_on_proc0(), pism::stressbalance::BedSmoother::smoothed_thk(), pism::ocean::PicoGeometry::split_ice_shelves(), pism::bed::LingleClark::step(), pism::stressbalance::BedSmoother::theta(), pism::total_grounding_line_flux(), pism::energy::total_ice_enthalpy(), pism::stressbalance::WeertmanSliding::update(), pism::AgeModel::update(), pism::surface::Verification::update_ABCDH(), pism::atmosphere::OrographicPrecipitation::update_impl(), pism::surface::TemperatureIndex::update_impl(), pism::calving::IcebergRemover::update_impl(), pism::calving::IcebergRemoverFEM::update_impl(), pism::energy::BTU_Full::update_impl(), pism::bed::PointwiseIsostasy::update_impl(), pism::energy::CHSystem::update_impl(), pism::energy::EnthalpyModel::update_impl(), pism::energy::TemperatureModel::update_impl(), pism::GeometryEvolution::update_in_place(), pism::wall_clock_hours(), and pism::stressbalance::zero_above_ice().