PISM, A Parallel Ice Sheet Model: pism::array::Array2D::star
add
add
array
array
Array2D
box
copy_from
operator()
operator()
star
value_type
star()
template<typename T > stencils::Star<T> pism::array::Array2D< T >::star (int i, int j) const inline protected
Definition at line 79 of file Array2D.hh.
References pism::stencils::Star< T >::c, pism::stencils::Star< T >::e, pism::stencils::Star< T >::n, pism::stencils::Star< T >::s, and pism::stencils::Star< T >::w.
Referenced by pism::Poisson::assemble_matrix(), pism::stressbalance::SSAFD::assemble_matrix(), pism::stressbalance::SSAFD::assemble_rhs(), pism::ocean::PicoGeometry::basin_neighbors(), pism::stressbalance::compute_2D_principal_strain_rates(), pism::stressbalance::compute_2D_stresses(), pism::ocean::PicoGeometry::compute_distances_cf(), pism::stressbalance::SSAFD_Regional::compute_driving_stress(), pism::stressbalance::SSA::compute_driving_stress(), pism::diagnostics::IceAreaFraction::compute_impl(), pism::stressbalance::BlatterMod::compute_max_diffusivity(), pism::hydrology::EmptyingProblem::compute_potential(), pism::hydrology::diagnostics::compute_sinks(), pism::hydrology::EmptyingProblem::compute_velocity(), pism::hydrology::Routing::compute_velocity(), pism::hydrology::NullTransport::diffuse_till_water(), pism::ocean::eikonal_equation(), pism::stressbalance::SSA::extrapolate_velocity(), pism::grounding_line_flux(), pism::ocean::PicoGeometry::identify_calving_front_connection(), pism::fct::limit(), pism::GeometryEvolution::residual_redistribution_iteration(), pism::ocean::Pico::set_ocean_input_fields(), pism::array::staggered_to_regular(), pism::step(), pism::total_grounding_line_flux(), pism::calving::HayhurstCalving::update(), pism::hydrology::EmptyingProblem::update(), pism::FractureDensity::update(), pism::FrontRetreat::update_geometry(), pism::frontalmelt::DischargeGiven::update_impl(), pism::frontalmelt::DischargeRouting::update_impl(), pism::GeometryEvolution::update_in_place(), pism::hydrology::Distributed::update_P(), and pism::hydrology::Routing::W_change_due_to_flow().