PISM, A Parallel Ice Sheet Model: pism::TSDiagnostic::flush
compute
flush
init
m_bounds
m_buffer_size
m_config
m_current_time
m_dimension
m_grid
m_output_filename
m_requested_times
m_start
m_sys
m_time
m_time_bounds
m_time_name
m_values
m_variable
metadata
Ptr
set_units
TSDiagnostic
update
update_impl
~TSDiagnostic
flush()
void pism::TSDiagnostic::flush ()
Definition at line 332 of file Diagnostic.cc.
References pism::io::define_time_bounds(), pism::io::define_timeseries(), pism::File::dimension_length(), pism::VariableMetadata::get_name(), m_bounds, m_config, m_dimension, m_grid, m_output_filename, m_start, m_time, m_time_bounds, m_values, m_variable, pism::io::PISM_DOUBLE, pism::io::PISM_NETCDF3, pism::io::PISM_READWRITE, pism::File::read_dimension(), pism::vector_max(), pism::io::write_time_bounds(), and pism::io::write_timeseries().
Referenced by ~TSDiagnostic().