PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSA::init_impl
compute_driving_stress
define_model_state_impl
diagnostics_impl
driving_stress
init_impl
m_da
m_event_ssa
m_mask
m_stdout_ssa
m_taud
m_velocity_global
set_initial_guess
solve
SSA
stdout_report
strength_extension
update
write_model_state_impl
~SSA
init_impl()
void pism::stressbalance::SSA::init_impl () protected virtual
Initialize a generic regular-grid SSA solver.
Reimplemented from pism::stressbalance::ShallowStressBalance.
Reimplemented in pism::stressbalance::SSAFEM, and pism::stressbalance::SSAFD.
Definition at line 126 of file SSA.cc.
References pism::InputOptions::filename, pism::File::find_variable(), pism::stressbalance::ShallowStressBalance::init_impl(), pism::INIT_RESTART, pism::Component::m_config, pism::stressbalance::ShallowStressBalance::m_flow_law, pism::Component::m_grid, pism::Component::m_log, pism::stressbalance::ShallowStressBalance::m_velocity, pism::File::nrecords(), pism::PISM_GUESS, pism::PISM_READONLY, pism::process_input_options(), pism::IceModelVec::read(), pism::IceModelVec::set(), and pism::InputOptions::type.
Referenced by pism::stressbalance::SSAFD::init_impl(), and pism::stressbalance::SSAFEM::init_impl().