PISM, A Parallel Ice Sheet Model: pism::surface::SurfaceModel::allocate_accumulation
accumulation
accumulation_impl
allocate_accumulation
allocate_layer_mass
allocate_layer_thickness
allocate_liquid_water_fraction
allocate_mass_flux
allocate_melt
allocate_runoff
allocate_temperature
define_model_state_impl
diagnostics_impl
dummy_accumulation
dummy_melt
dummy_runoff
init
init_impl
layer_mass
layer_mass_impl
layer_thickness
layer_thickness_impl
liquid_water_fraction
liquid_water_fraction_impl
m_accumulation
m_atmosphere
m_input_model
m_layer_mass
m_layer_thickness
m_liquid_water_fraction
m_melt
m_runoff
mass_flux
mass_flux_impl
max_timestep_impl
melt
melt_impl
runoff
runoff_impl
SurfaceModel
SurfaceModel
SurfaceModel
temperature
temperature_impl
ts_diagnostics_impl
update
update_impl
write_model_state_impl
~SurfaceModel
allocate_accumulation()
std::shared_ptr< array::Scalar > pism::surface::SurfaceModel::allocate_accumulation (std::shared_ptr< const Grid > grid) static protected
Definition at line 106 of file SurfaceModel.cc.
References pism::Component::grid().
Referenced by pism::surface::Anomaly::Anomaly(), pism::surface::Cache::Cache(), pism::surface::DEBMSimple::DEBMSimple(), pism::surface::ElevationChange::ElevationChange(), pism::surface::ForceThickness::ForceThickness(), pism::surface::InitializationHelper::InitializationHelper(), pism::surface::NoGLRetreat::NoGLRetreat(), pism::surface::PSFormulas::PSFormulas(), SurfaceModel(), and pism::surface::TemperatureIndex::TemperatureIndex().