PISM, A Parallel Ice Sheet Model: pism::EnthalpyConverter::L
c
enthalpy
enthalpy_cold
enthalpy_cts
enthalpy_liquid
enthalpy_permissive
EnthalpyConverter
is_temperate
is_temperate_relaxed
L
m_beta
m_c_i
m_c_w
m_do_cold_ice_methods
m_g
m_L
m_p_air
m_rho_i
m_T_0
m_T_melting
m_T_tolerance
melting_temperature
pressure
pressure
pressure_adjusted_temperature
Ptr
temperature
temperature_cold
validate_E_P
validate_T_omega_P
water_fraction
~EnthalpyConverter
L()
double pism::EnthalpyConverter::L (double T_pm) const
Latent heat of fusion of water as a function of pressure melting temperature.
Following a re-interpretation of [AschwandenBuelerKhroulevBlatter], we require that \(\Diff{H}{p} = 0 \):
\[ \Diff{H}{p} = \diff{H_w}{p} + \diff{H_w}{p}\Diff{T}{p} \]
We assume that water is incompressible, so \(\Diff{T}{p} = 0 \) and the second term vanishes.
As for the first term, equation (5) of [AschwandenBuelerKhroulevBlatter] defines \(H_w \) as follows:
\[ H_w = \int_{T_0}^{T_m(p)} C_i(t) dt + L + \int_{T_m(p)}^T C_w(t)dt \]
Using the fundamental theorem of Calculus, we get
\[ \diff{H_w}{p} = (C_i(T_m(p)) - C_w(T_m(p))) \diff{T_m(p)}{p} + \diff{L}{p} \]
Assuming that \(C_i(T) = c_i \) and \(C_w(T) = c_w \) (i.e. specific heat capacities of ice and water do not depend on temperature) and using the Clausius-Clapeyron relation
\[ T_m(p) = T_m(p_{\text{air}}) - \beta p, \]
we get
\begin{align} \Diff{H}{p} &= (c_i - c_w)\diff{T_m(p)}{p} + \diff{L}{p}\\ &= \beta(c_w - c_i) + \diff{L}{p}\\ \end{align}
Requiring \(\Diff{H}{p} = 0 \) implies
\[ \diff{L}{p} = -\beta(c_w - c_i), \]
and so
\begin{align} L(p) &= -\beta p (c_w - c_i) + C\\ &= (T_m(p) - T_m(p_{\text{air}})) (c_w - c_i) + C. \end{align}
Letting \(p = p_{\text{air}} \) we find \(C = L(p_\text{air}) = L_0 \), so
\[ L(p) = (T_m(p) - T_m(p_{\text{air}})) (c_w - c_i) + L_0, \]
where \(L_0 \) is the latent heat of fusion of water at atmospheric pressure.
Therefore a consistent interpretation of [AschwandenBuelerKhroulevBlatter] requires the temperature-dependent approximation of the latent heat of fusion of water given above.
Note that this form of \(L(p) \) also follows from Kirchhoff's law of thermochemistry.
Definition at line 359 of file EnthalpyConverter.cc.
References m_c_i, m_c_w, and m_L.
Referenced by enthalpy(), enthalpy_liquid(), and water_fraction().