PISM, A Parallel Ice Sheet Model: pism::calving::vonMisesCalving::update
diagnostics_impl
init
m_calving_threshold
m_flow_law
threshold
update
vonMisesCalving
~vonMisesCalving
update()
void pism::calving::vonMisesCalving::update (const IceModelVec2CellType & cell_type, const IceModelVec2S & ice_thickness, const IceModelVec2V & ice_velocity, const IceModelVec3 & ice_enthalpy)
Uses principal strain rates to apply the "von Mises" calving method.
See equation (4) in [Morlighem2016].
Definition at line 97 of file vonMisesCalving.cc.
References pism::rheology::averaged_hardness(), pism::stressbalance::compute_2D_principal_strain_rates(), pism::IceModelVec2S::copy_from(), pism::IceModelVec3::get_column(), I, pism::IceModelVec2CellType::ice_free_ocean(), pism::IceModelVec2CellType::icy(), J, pism::k, pism::calving::StressCalving::m_calving_rate, m_calving_threshold, pism::calving::StressCalving::m_cell_type, m_flow_law, pism::Component::m_grid, pism::calving::StressCalving::m_stencil_width, pism::calving::StressCalving::m_strain_rates, pism::max(), pism::PointsWithGhosts::next(), pism::IceModelVec2CellType::next_to_ice(), and pism::IceModelVec::update_ghosts().