PISM, A Parallel Ice Sheet Model: pism::ocean::Pico::set_ocean_input_fields
beckmann_goosse
compute_box_area
compute_box_average
compute_ocean_input_per_basin
define_model_state_impl
diagnostics_impl
init_impl
m_basal_melt_rate
m_geometry
m_n_basins
m_n_boxes
m_n_shelves
m_overturning
m_salinity_ocean
m_Soc
m_Soc_box0
m_T_star
m_theta_ocean
m_Toc
m_Toc_box0
max_timestep_impl
Pico
process_box1
process_other_boxes
set_ocean_input_fields
update_impl
write_model_state_impl
~Pico
set_ocean_input_fields()
void pism::ocean::Pico::set_ocean_input_fields (const PicoPhysics & physics, const IceModelVec2S & ice_thickness, const IceModelVec2CellType & mask, const IceModelVec2Int & basin_mask, const IceModelVec2Int & shelf_mask, const std::vector< double > & basin_temperature, const std::vector< double > & basin_salinity, IceModelVec2S & Toc_box0, IceModelVec2S & Soc_box0) const private
Set ocean ocean input from box 0 as boundary condition for box 1.
Set ocean temperature and salinity (Toc_box0, Soc_box0) from box 0 (in front of the ice shelf) as inputs for box 1, which is the ocean box adjacent to the grounding line.
We enforce that Toc_box0 is always at least the local pressure melting point.
Definition at line 454 of file Pico.cc.
References pism::IceModelVec2Int::as_int(), pism::GlobalSum(), pism::IceModelVec2Int::int_star(), pism::Component::m_grid, pism::Component::m_log, m_n_basins, m_n_shelves, pism::MASK_FLOATING, pism::MASK_ICE_FREE_OCEAN, pism::PointsWithGhosts::next(), pism::ocean::PicoPhysics::pressure(), and pism::ocean::PicoPhysics::theta_pm().
Referenced by update_impl().