PISM, A Parallel Ice Sheet Model: pism::stressbalance::Blatter::nodal_parameter_values
Blatter
compute_averaged_velocity
compute_jacobian
compute_node_type
compute_residual
copy_solution
define_model_state_impl
dirichlet_node
exterior_element
function_callback
get_basal_velocity
grounding_line
init_2d_parameters
init_ice_hardness
init_impl
jacobian_basal
jacobian_callback
jacobian_dirichlet
jacobian_f
m_da
m_E_viscosity
m_eta_transform
m_face100
m_face4
m_glen_exponent
m_ksp_use_ew
m_n_work
m_Nq
m_parameters
m_rho_ice_g
m_rho_ocean_g
m_scaling
m_snes
m_u_sigma
m_v_sigma
m_viscosity_eps
m_work
m_work2
m_x
m_x_old
marine_boundary
nodal_parameter_values
parameter_continuation
partially_submerged_face
report_mesh_info
residual_basal
residual_dirichlet
residual_f
residual_lateral
residual_source_term
residual_surface
set_initial_guess
setup
solve
u_bc
update
velocity_u_sigma
velocity_v_sigma
write_model_state_impl
~Blatter
nodal_parameter_values()
void pism::stressbalance::Blatter::nodal_parameter_values (const fem::Q1Element3 & element, Parameters ** P, int i, int j, int * node_type, double * bottom_elevation, double * ice_thickness, double * surface_elevation, double * sea_level) const protected virtual
Get values of 2D parameters at element nodes.
This method is re-implemented by derived classes that use periodic boundary conditions.
Reimplemented in pism::stressbalance::BlatterISMIPHOM.
Definition at line 627 of file Blatter.cc.
References pism::stressbalance::Blatter::Parameters::bed, I, pism::fem::Element3::local_to_global(), n, and pism::fem::q13d::n_chi.
Referenced by compute_jacobian(), and compute_residual().