PISM, A Parallel Ice Sheet Model: pism::VariableMetadata::report_to_stdout
all_doubles
all_strings
check_range
clear
get_name
get_number
get_numbers
get_output_type
get_string
get_time_independent
has_attribute
has_attributes
long_name
m_doubles
m_n_spatial_dims
m_output_type
m_short_name
m_strings
m_time_independent
m_unit_system
n_spatial_dimensions
operator[]
operator[]
output_units
report_range
report_to_stdout
set_name
set_number
set_numbers
set_output_type
set_string
set_time_independent
set_units_without_validation
standard_name
unit_system
units
VariableMetadata
~VariableMetadata
report_to_stdout()
void pism::VariableMetadata::report_to_stdout (const Logger & log, int verbosity_threshold) const
Definition at line 358 of file VariableMetadata.cc.
References all_doubles(), all_strings(), pism::array::max(), and pism::Logger::message().