PISM, A Parallel Ice Sheet Model: pism::stressbalance::BlatterMod::compute_max_diffusivity
BlatterMod
compute_max_diffusivity
init
m_solver
transfer
update
~BlatterMod
compute_max_diffusivity()
void pism::stressbalance::BlatterMod::compute_max_diffusivity (const IceModelVec2V & velocity, const IceModelVec2S & ice_thickness, const IceModelVec2S & surface) private
Estimate max SIA-type diffusivity assuming that Q = -D \nabla h.
Definition at line 113 of file BlatterMod.cc.
References pism::GlobalMax(), pism::stressbalance::SSB_Modifier::m_D_max, pism::Component::m_grid, pism::Vector2::magnitude(), pism::max(), pism::PointsWithGhosts::next(), and pism::IceModelVec2S::star().
Referenced by update().