PISM, A Parallel Ice Sheet Model: pism::GeometryEvolution::compute_interface_fluxes
apply_flux_divergence
apply_mass_fluxes
area_specific_volume_change_due_to_flow
bottom_surface_mass_balance
compute_flux_divergence
compute_interface_fluxes
compute_surface_and_basal_mass_balance
conservation_error
diagnostics_impl
ensure_nonnegativity
flow_step
flux_divergence
flux_staggered
GeometryEvolution
init
init_impl
m_impl
reset
residual_redistribution_iteration
set_no_model_mask
set_no_model_mask_impl
source_term_step
thickness_change_due_to_flow
top_surface_mass_balance
update_in_place
~GeometryEvolution
compute_interface_fluxes()
void pism::GeometryEvolution::compute_interface_fluxes (const IceModelVec2CellType & cell_type, const IceModelVec2S & ice_thickness, const IceModelVec2V & velocity, const IceModelVec2Stag & diffusive_flux, IceModelVec2Stag & output) protected virtual
Combine advective velocity and the diffusive flux on the staggered grid with the ice thickness to compute the total flux through cell interfaces.
Uses first-order upwinding to compute the advective flux.
Limits the diffusive flux to prevent SIA-driven flow in the ocean and ice-free areas.
Reimplemented in pism::RegionalGeometryEvolution.
Definition at line 534 of file GeometryEvolution.cc.
References pism::ParallelSection::check(), pism::ParallelSection::failed(), pism::mask::icy(), pism::limit_advective_flux(), pism::limit_diffusive_flux(), pism::Component::m_grid, pism::max(), n, and pism::PointsWithGhosts::next().
Referenced by pism::RegionalGeometryEvolution::compute_interface_fluxes(), and flow_step().