PISM, A Parallel Ice Sheet Model: label_connected_components
label_connected_components
label_connected_components()
void label_connected_components (double * image, int nrows, int ncols, bool identify_icebergs, int mask_grounded, int first_label)
Label connected components. Modifies image in place.
Definition at line 40 of file connected_components.cc.
References pism::k, L, Run::label, Run::length, n, resolve_label(), and pism::fem::row().
Referenced by pism::ocean::PicoGeometry::compute_continental_shelf_mask(), pism::ocean::PicoGeometry::compute_lakes(), pism::label_components(), pism::ocean::PicoGeometry::label_tmp(), pism::calving::IcebergRemover::update_impl(), and pism::calving::IcebergRemoverFEM::update_impl().