PISM, A Parallel Ice Sheet Model: adapt_integrate
adapt_integrate
integrand
adapt_integrate()
int adapt_integrate (integrand f, void * fdata, unsigned dim, const double * xmin, const double * xmax, unsigned maxEval, double reqAbsError, double reqRelError, double * val, double * estimated_error)
Definition at line 701 of file cubature.c.
References destroy_hypercube(), destroy_rule(), esterr::err, make_hypercube_range(), make_rule15gauss(), make_rule75genzmalik(), ruleadapt_integrate(), and esterr::val.
Referenced by dblquad_cubature(), and main().