PISM, A Parallel Ice Sheet Model: heap_resize
adapt_integrate
compute_vol
cut_region
destroy_hypercube
destroy_region
destroy_rule
destroy_rule75genzmalik
eval_region
evalR0_0fs4d
evalR_Rfs
evalRR0_0fs
heap_alloc
heap_free
heap_item
heap_pop
heap_push
heap_resize
isqr
KEY
ls0
make_hypercube
make_hypercube_range
make_region
make_rule15gauss
make_rule75genzmalik
num0_0
numR0_0fs
numR_Rfs
numRR0_0fs
real
relError
rule
rule15gauss_evalError
rule75genzmalik_evalError
ruleadapt_integrate
to_int
heap_resize()
static void heap_resize (heap * h, unsigned nalloc) static
Definition at line 554 of file cubature.c.
References heap::items, and heap::nalloc.
Referenced by heap_alloc(), heap_free(), and heap_push().