PISM, A Parallel Ice Sheet Model: funcM_ode_G
barB
dF_M
exactM
exactM_old
F_M
funcM_ode_G
g
H0
INVALID_METHOD
MAX
MIN
n
NEGATIVE_R
NOT_DONE
Rc
Rg
rho
rhow
SperA
funcM_ode_G()
int funcM_ode_G (double r, const double alpha[], double f[], void * params)
Definition at line 60 of file exactTestM.c.
References barB, dF_M(), F_M(), g, H0, n, pism::printf(), Rc, rho, and rhow.
Referenced by exactM().