PISM, A Parallel Ice Sheet Model: pism::mask::ocean
floating_ice
grounded
grounded_ice
ice_free
ice_free_land
ice_free_ocean
icy
ocean
ocean()
bool pism::mask::ocean (int M) inline
An ocean cell (floating ice or ice-free).
Definition at line 40 of file Mask.hh.
References pism::MASK_FLOATING.
Referenced by pism::IceEISModel::allocate_couplers(), pism::IceModel::allocate_couplers(), pism::stressbalance::SSAFEM::cache_residual_cfbc(), floating_ice(), grounded(), ice_free_ocean(), pism::array::CellType::ocean(), pism::energy::tempSystemCtx::solveThisColumn(), and pism::energy::TemperatureModel::update_impl().