PISM, A Parallel Ice Sheet Model: pism::mask::ice_free_land
floating_ice
grounded
grounded_ice
ice_free
ice_free_land
ice_free_ocean
icy
ocean
ice_free_land()
bool pism::mask::ice_free_land (int M) inline
Definition at line 63 of file Mask.hh.
References grounded(), and ice_free().
Referenced by pism::stressbalance::SSAFD::assemble_matrix(), pism::stressbalance::SSAFD::assemble_rhs(), pism::IceModelVec2CellType::ice_free_land(), pism::limit_advective_flux(), pism::limit_diffusive_flux(), and pism::stressbalance::SSAFEM::PointwiseNuHAndBeta().