PISM, A Parallel Ice Sheet Model: pism::fct::flux_in
beta_down
beta_up
flux_in
flux_out
limit
maximum
minimum
np
pp
flux_in()
static double pism::fct::flux_in (const stencils::Star< double > & u, const stencils::Star< double > & psi, double dx, double dy, double dt) static
Definition at line 60 of file MPDATA2.cc.
References pism::stencils::Star< T >::e, pism::stencils::Star< T >::n, np(), pp(), pism::stencils::Star< T >::s, and pism::stencils::Star< T >::w.
Referenced by beta_up().