PISM, A Parallel Ice Sheet Model: pism::surface::details::solar_longitude
CalovGreveIntegrand
distance_factor_paleo
distance_factor_present_day
hour_angle
insolation
solar_declination_paleo
solar_declination_present_day
solar_longitude
solar_longitude()
static double pism::surface::details::solar_longitude (double year_fraction, double eccentricity, double perihelion_longitude) static
Solar longitude (radians) at current time in the year.
Parameters
[in] year_fraction year fraction (between 0 and 1)
[in] eccentricity eccentricity of the earth’s orbit (no units)
[in] perihelion_longitude perihelion longitude (radians)
Implements equation A2 in Zeitz et al.
Definition at line 101 of file DEBMSimplePointwise.cc.
Referenced by distance_factor_paleo(), pism::surface::DEBMSimplePointwise::orbital_parameters(), and solar_declination_paleo().