PISM, A Parallel Ice Sheet Model: pism::inverse::gradientFD
DesignVec
gradientFD
gradientFD
StateVec
gradientFD() [1/2]
void pism::inverse::gradientFD (IPFunctional< IceModelVec2S > & f, IceModelVec2S & x, IceModelVec2S & gradient)
Computes finite difference approximations of a IPFunctional<IceModelVec2S> gradient.
Useful for debugging a hand coded gradient.
Definition at line 27 of file IPFunctional.cc.
References pism::ParallelSection::check(), pism::IceGrid::com, pism::ParallelSection::failed(), pism::IceModelVec::grid(), pism::PointsWithGhosts::next(), pism::IceModelVec::update_ghosts(), and pism::inverse::IPFunctional< IMVecType >::valueAt().