PISM, A Parallel Ice Sheet Model: pism::atmosphere::era_interim_lon
era_interim
era_interim_lon
era_interim_sin
huybrechts_dewolde
huybrechts_dewolde_mean_annual
huybrechts_dewolde_mean_summer
martin2011
martin2011_mean_annual
martin_huybrechts_dewolde
era_interim_lon()
static void pism::atmosphere::era_interim_lon (const Geometry & geometry, array::Scalar & T_ma, array::Scalar & T_ms) static
Parametrization based on multiple regression analysis of ERA INTERIM data with cos(lon)
Definition at line 191 of file PIK.cc.
References pism::array::Array::grid(), pism::Geometry::ice_surface_elevation, pism::Geometry::latitude, pism::Geometry::longitude, and pism::array::max().
Referenced by pism::atmosphere::PIK::update_impl().