PISM, A Parallel Ice Sheet Model: pism::rheology::averaged_hardness
averaged_hardness
averaged_hardness_vec
create_arr
create_arrwarm
create_goldsby_kohlstedt
create_gpbld
create_hooke
create_isothermal_glen
create_pb
FlowLawCreator
FlowLawIsPatersonBuddCold
FlowLawUsesGrainSize
averaged_hardness()
double pism::rheology::averaged_hardness (const FlowLaw & ice, double thickness, unsigned int kbelowH, const double * zlevels, const double * enthalpy)
Computes vertical average of B(E, p) ice hardness, namely \(\bar B(E, p)\).
See comment for hardness(). Note E[0], ..., E[kbelowH] must be valid.
Definition at line 213 of file FlowLaw.cc.
References pism::rheology::FlowLaw::EC(), pism::h0, and pism::rheology::FlowLaw::hardness().
Referenced by averaged_hardness_vec(), pism::stressbalance::SSAFEM::cache_inputs(), pism::stressbalance::SSAFD::compute_hardav_staggered(), pism::diagnostics::HardnessAverage::compute_impl(), pism::stressbalance::PSB_vonmises_stress::compute_impl(), and pism::calving::vonMisesCalving::update().