PISM, A Parallel Ice Sheet Model: pism::units::are_convertible
are_convertible
convert
are_convertible()
bool pism::units::are_convertible (const Unit & u1, const Unit & u2)
Check if units are convertible without creating a converter.
Parameters
[in] u1 first Unit instance
[in] u2 second Unit instance
Returns
true if units are convertible, false otherwise
Definition at line 244 of file Units.cc.
References pism::units::Unit::is_convertible().
Referenced by pism::File::dimension_type(), pism::Time::parse_interval_length(), and pism::VariableMetadata::set_string().