PISM, A Parallel Ice Sheet Model: pism::energy::bootstrap_ice_enthalpy
ApforG
bootstrap_ice_enthalpy
bootstrap_ice_temperature
check_input
compute_cts
compute_enthalpy
compute_enthalpy_cold
compute_liquid_water_fraction
compute_temperature
cryo_hydrologic_warming_flux
ice_temperature_guess
ice_temperature_guess_smb
LforFG
marginal
ST
Tmin
total_ice_enthalpy
upwind
bootstrap_ice_enthalpy()
void pism::energy::bootstrap_ice_enthalpy (const IceModelVec2S & ice_thickness, const IceModelVec2S & ice_surface_temp, const IceModelVec2S & surface_mass_balance, const IceModelVec2S & basal_heat_flux, IceModelVec3 & result)
Definition at line 445 of file utilities.cc.
References bootstrap_ice_temperature(), and compute_enthalpy_cold().
Referenced by pism::energy::CHSystem::bootstrap_impl(), pism::energy::EnthalpyModel::bootstrap_impl(), pism::energy::CHSystem::initialize_impl(), and pism::energy::EnthalpyModel::initialize_impl().