PISM, A Parallel Ice Sheet Model: pism::hydrology::diagnostics::hydraulic_potential
compute_sinks
effective_water_velocity
hydraulic_potential
hydraulic_potential()
void pism::hydrology::diagnostics::hydraulic_potential (const array::Scalar & W, const array::Scalar & P, const array::Scalar & sea_level, const array::Scalar & bed, const array::Scalar & ice_thickness, array::Scalar & result)
Compute the hydraulic potential.
Computes \(\psi = P + \rho_w g (b + W)\).
Definition at line 186 of file Routing.cc.
References C, pism::array::Array::grid(), and pism::array::max().
Referenced by pism::hydrology::diagnostics::HydraulicPotential::compute_impl().