PISM, A Parallel Ice Sheet Model: pism::stressbalance::SSAFDFactory
A_bed
A_surface
aspect_schoof
B_bed
B_schoof
blatter_coarsening_hook
blatter_restriction_hook
C_bed
C_surface
compute_2D_principal_strain_rates
compute_2D_stresses
copy_staggered_vec
create
D2
disable_ew
enable_ew
H0_schoof
H_exact
ISMIPHOMTest
L_schoof
m_schoof
set_diagonal_matrix_entry
SSAFactory
SSAFD_RegionalFactory
SSAFDFactory
SSAFEMFactory
u_exact
u_exterior
weight
weight
zero_above_ice
SSAFDFactory()
SSA * pism::stressbalance::SSAFDFactory (std::shared_ptr< const Grid > g)
Constructs a new SSAFD.
Definition at line 49 of file SSAFD.cc.
References pism::g, and pism::stressbalance::SSAFD::SSAFD().
Referenced by create(), and main().