PISM, A Parallel Ice Sheet Model: pism::array::staggered_to_regular
absmax
absmax
apply_mask
cast
compute_magnitude
compute_range
diff_x
diff_x_p
diff_y
diff_y_p
extract_surface
extract_surface
global_to_local
int_to_normtype
interpolate
Kind
max
min
set_default_value_or_stop
staggered_to_regular
staggered_to_regular
sum
sum_columns
staggered_to_regular() [2/2]
void pism::array::staggered_to_regular (const array::CellType1 & cell_type, const array::Staggered1 & input, bool include_floating_ice, array::Vector & result)
Average a vector field from the staggered grid onto the regular grid by considering only ice-covered grid.
If include_floating_ice is true, include floating ice, otherwise consider grounded icy cells only.
Definition at line 131 of file Staggered.cc.
References pism::F(), pism::array::Array::grid(), pism::mask::grounded_ice(), pism::mask::icy(), n, pism::array::Array2D< T >::star(), pism::array::Staggered1::star(), and pism::array::Array::stencil_width().