PISM, A Parallel Ice Sheet Model: pism::k
AccessType
Aglen
args_string
average_water_column_pressure
axis_type_from_string
AxisType
backend_to_string
bedrock_surface_temperature
blatter_xy_exact
blatter_xy_source
blatter_xz_cfbc_base
blatter_xz_cfbc_exact
blatter_xz_cfbc_source
blatter_xz_cfbc_surface
blatter_xz_exact
blatter_xz_halfar_exact
blatter_xz_halfar_source
blatter_xz_halfar_source_base
blatter_xz_halfar_source_lateral
blatter_xz_halfar_source_surface
blatter_xz_source
blatter_xz_source_bed
blatter_xz_source_surface
blatter_xz_vanderveen_beta
blatter_xz_vanderveen_exact
blatter_xz_vanderveen_source_lateral
blatter_xz_vanderveen_source_surface
blatter_xz_vanderveen_thickness
Box
c1
c2
calendar
calendar_from_file
check_c_call
check_consistency_epsg
check_forcing_duration
check_input
check_petsc_call
choose_backend
clear_fftw_array
clip
combine
compute_cell_areas
compute_coordinates
compute_corrective_velocity
compute_grounded_cell_fraction
compute_horizontal_spacing
compute_interface_velocity
compute_lat_bounds
compute_latitude
compute_lon_bounds
compute_lon_lat
compute_lon_lat_bounds
compute_longitude
compute_node_types
compute_nprocs
compute_ownership_ranges
compute_strain_heating_errors
computeSurfaceVelocityErrors
config_from_options
ConfigSettingFlag
context_from_options
convert_vec
convert_vec
copy_fftw_array
count_CFL_violations
create_backend
create_restriction
criticalW
diag_metadata
DiagnosticList
Direction
effective_change
end_time
ends_with
enthalpy_from_temperature_cold
epsg_to_cf
exactFG
exactP
exactP_list
F
F
fftfreq
filename_add_suffix
find_json_value
fletcher64
floating_ice_sheet_area_fraction_name
funcP
g
generate_mound_topography
generate_trough_topography
get_all_arrays
get_all_values
get_projection_info
get_real_part
get_time
get_value
getsb
getW
GlobalMax
GlobalMax
GlobalMax
GlobalMin
GlobalMin
GlobalReduce
GlobalReduce
GlobalSum
GlobalSum
GlobalSum
GlobalSum
GlobalSum
Grid_FromFile
grid_transpose
grid_z
grounded_area_fraction
grounded_ice_sheet_area_fraction_name
grounding_line_flux
h0
handle_fatal_errors
ice_area
ice_area_floating
ice_area_grounded
ice_bottom_surface
ice_volume
ice_volume_not_displacing_seawater
IceModelTerminationReason
increment_date
init_interpolation_indexes
init_step
initialconditionW
InitializationType
integration_weights
integration_weights
InterpolationType
intersect_ab
intersect_ac
intersect_bc
invalid
is_increasing
join
join_impl
k
label_components
label_components
land_ice_area_fraction_name
lapse_rate_correction
limit_advective_flux
limit_diffusive_flux
logger_from_options
LoggerLevel
LonLat
m0
make_nonnegative_preserving
MaskValue
max_timestep_cfl_2d
max_timestep_cfl_3d
max_timestep_diffusivity
member
Metadata
nc_type_to_pism_type
NodeType
operator*
operator<
operator==
operator>
ownership_ranges
p3
p4
pack_json_array
parse_date
parse_integer
parse_number
part_grid_threshold_thickness
pism_is_valid_calendar_name
pism_type_to_nc_type
print_checksum
print_config
print_diagnostics
print_diagnostics_json
print_unused_parameters
print_vector
print_vector
printf
process_extra_shortcuts
process_input_options
process_ts_shortcuts
psteady
R1
reference_date
reference_date_from_file
regional_grid_from_options
remove_narrow_tongues
replace_character
report_range
reportErrors
reporting_max_timestep
restrict_data
rhoi
rhow
same
sea_level_rise_potential
secondInvariant_2D
set_config_from_options
set_flag_from_option
set_integer_from_option
set_integer_list_from_option
set_join
set_keyword_from_option
set_no_model_strip
set_no_model_yield_stress
set_number_from_option
set_number_list_from_option
set_parameter_from_options
set_real_part
set_split
set_string_from_option
set_value
setInitStateF
setup_level
show_usage
show_usage_check_req_opts
SNESScalarProblem
SNESVectorProblem
special_parameter
SperA
split
square
start_time
step
step
string_is_false
string_is_true
string_strip
string_to_backend
subset_extent
subset_start_and_count
TEMPORARY_STRING_LENGTH
timestamp
total_grounding_line_flux
triangle_area
ts_diag_metadata
TSDiagnosticList
UNOType
unpack_json_array
upwind
username_prefix
v0
validate_format_string
validate_range
vector_max
vector_min
version
wall_clock_hours
warn_about_missing
weights_piecewise_constant
weights_piecewise_linear
Wr
write
write_mapping
write_run_stats
k
const double pism::k = (0.01 / (rhow * g)) static
Definition at line 42 of file exactTestP.cc.
Referenced by pism::fem::Element2::add_contribution(), pism::NetCDFConfig::all_strings_impl(), pism::Diagnostic::allocate(), pism::details::allocate_layer_thickness(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_H1NormFunctional2S::assemble_form(), pism::inverse::IPGroundedIceH1NormFunctional2S::assemble_form(), pism::stressbalance::SSAFD::assemble_matrix(), pism::energy::enthSystemCtx::assemble_R(), pism::array::Forcing::average(), pism::energy::BTU_Full::bootstrap(), pism::energy::BTU_Verification::bootstrap(), pism::Isochrones::bootstrap(), pism::energy::bootstrap_ice_temperature(), pism::energy::BTU_Full::BTU_Full(), pism::array::Array::check_array_indices(), pism::fem::q13d::chi(), pism::fem::linear::chi(), pism::fem::q0::chi(), pism::fem::q1::chi(), pism::fem::p1::chi(), pism::fem::Element::chi(), pism::fem::Q1Element3Face::chi(), pism::ColumnInterpolation::coarse_to_fine_linear(), pism::ColumnInterpolation::coarse_to_fine_quadratic(), pism::fem::column(), pism::stressbalance::PSB_wvel::compute(), pism::stressbalance::SIAFD::compute_3d_horizontal_velocity(), pism::stressbalance::Blatter::compute_averaged_velocity(), pism::ocean::PicoGeometry::compute_box_mask(), pism::stressbalance::BedSmoother::compute_coefficients_on_proc0(), pism::hydrology::Routing::compute_conductivity(), pism::energy::compute_cts(), pism::stressbalance::SIAFD::compute_diffusivity(), pism::icebin::IBIceModel::compute_enth2(), pism::energy::compute_enthalpy(), pism::energy::compute_enthalpy_cold(), pism::energy::enthSystemCtx::compute_enthalpy_CTS(), pism::stressbalance::SSAFD::compute_hardav_staggered(), pism::stressbalance::SIAFD::compute_I(), pism::diagnostics::IsochroneDepths::compute_impl(), pism::diagnostics::Temperature::compute_impl(), pism::diagnostics::TemperaturePA::compute_impl(), pism::diagnostics::TemperateIceThickness::compute_impl(), pism::diagnostics::TemperateIceThicknessBasal::compute_impl(), pism::diagnostics::IceHardness::compute_impl(), pism::diagnostics::IceViscosity::compute_impl(), pism::stressbalance::PSB_flux::compute_impl(), pism::stressbalance::PSB_pressure::compute_impl(), pism::stressbalance::PSB_tauxz::compute_impl(), pism::stressbalance::PSB_tauyz::compute_impl(), pism::stressbalance::PSB_vonmises_stress::compute_impl(), pism::DiagWithDedicatedStorage< T >::compute_impl(), pism::UNO::compute_interface_fluxes(), pism::stressbalance::Blatter::compute_jacobian(), pism::energy::enthSystemCtx::compute_lambda(), pism::energy::tempSystemCtx::compute_lambda(), pism::energy::compute_liquid_water_fraction(), pism::stressbalance::SSAFEM::compute_local_function(), pism::stressbalance::SSAFEM::compute_local_jacobian(), pism::stressbalance::Blatter::compute_node_type(), pism::IceModel::compute_original_ice_fraction(), compute_ownership_ranges(), pism::array::compute_range(), pism::stressbalance::Blatter::compute_residual(), compute_strain_heating_errors(), pism::IceCompModel::compute_strain_heating_errors(), pism::energy::compute_temperature(), pism::Time::compute_times_simple(), pism::grid::compute_vertical_levels(), pism::stressbalance::StressBalance::compute_vertical_velocity(), pism::stressbalance::StressBalance::compute_volumetric_strain_heating(), pism::IceCompModel::computeIceBedrockTemperatureErrors(), pism::IceCompModel::computeTemperatureErrors(), pism::fem::DirichletData::constrain(), pism::io::convert_data(), pism::stressbalance::Blatter::copy_solution(), count_CFL_violations(), pism::energy::cryo_hydrologic_warming_flux(), pism::TridiagonalSystem::ddratio(), pism::io::define_dimensions(), diag_metadata(), pism::fem::DirichletData::DirichletData(), pism::array::Forcing::discard(), pism::stressbalance::SSAFEM::driving_stress(), pism::Grid::dz_max(), pism::Grid::dz_min(), pism::fem::element_type(), pism::fem::DirichletData_Scalar::enforce(), pism::fem::DirichletData_Vector::enforce(), pism::fem::DirichletData_Scalar::enforce_homogeneous(), pism::fem::DirichletData_Vector::enforce_homogeneous(), enthalpy_from_temperature_cold(), pism::fem::Element::evaluate(), pism::fem::Q1Element3Face::evaluate(), pism::fem::Element2::evaluate(), pism::fem::Element3::evaluate(), pism::TSRateDiagnostic::evaluate(), pism::TSSnapshotDiagnostic::evaluate(), exactFG(), exactK(), pism::stressbalance::SSAFEM::explicit_driving_stress(), pism::ColumnInterpolation::fine_to_coarse(), pism::rheology::FlowLaw::flow_n_impl(), pism::rheology::GPBLD::flow_n_impl(), funcP(), pism::io::get_att_string(), pism::Vars::get_internal(), pism::Vars::get_internal_shared(), pism::Config::get_numbers(), pism::surface::PDDMassBalance::get_PDDs(), pism::surface::PDDrandMassBalance::get_PDDs(), pism::io::NC_Serial::get_var_double(), pism::inverse::IP_H1NormFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2S::gradientAt(), pism::inverse::IPGroundedIceH1NormFunctional2S::gradientAt(), pism::inverse::IPTotalVariationFunctional2S::gradientAt(), pism::inverse::IP_L2NormFunctional2V::gradientAt(), grid_z(), pism::rheology::FlowLaw::hardness_n_impl(), pism::details::ice_volume(), pism::array::Forcing::init(), pism::energy::enthSystemCtx::init(), pism::IceModel::init_extras(), pism::columnSystemCtx::init_fine_grid(), pism::stressbalance::Blatter::init_ice_hardness(), pism::ColumnInterpolation::init_interpolation(), pism::array::Forcing::init_interpolation(), init_interpolation_indexes(), pism::hydrology::SteadyState::init_time(), pism::atmosphere::CosineYearlyCycle::init_timeseries_impl(), pism::atmosphere::Delta_P::init_timeseries_impl(), pism::atmosphere::Delta_T::init_timeseries_impl(), pism::atmosphere::Frac_P::init_timeseries_impl(), pism::atmosphere::PrecipitationScaling::init_timeseries_impl(), pism::atmosphere::WeatherStation::init_timeseries_impl(), pism::atmosphere::YearlyCycle::init_timeseries_impl(), pism::ScalarForcing::initialize(), pism::fem::Element::initialize(), pism::IceCompModel::initTestL(), pism::energy::TemperatureModel_Verification::initTestsKO(), pism::io::NC4File::inq_vardimid_impl(), pism::io::NC_Serial::inq_vardimid_impl(), pism::io::ParallelIO::inq_vardimid_impl(), pism::io::PNCFile::inq_vardimid_impl(), pism::ScalarForcing::integral(), pism::Interpolation::interpolate(), pism::Interpolation::Interpolation(), is_increasing(), pism::stressbalance::Blatter::jacobian_dirichlet(), label_connected_components(), pism::fem::Element3::local_to_global(), pism::fem::Element2::local_to_global(), pism::fem::Element::mark_col_invalid(), pism::fem::Element::mark_row_invalid(), max_timestep_cfl_3d(), pism::Isochrones::max_timestep_deposition_times(), pism::OptTillphiYieldStress::max_timestep_impl(), pism::bed::LingleClark::max_timestep_impl(), pism::hydrology::SteadyState::max_timestep_impl(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::monitorTao(), pism::inverse::IPTaoTikhonovProblem< ForwardProblem >::monitorTao(), pism::fem::Element2::nodal_values(), pism::details::non_decreasing(), pism::array::Array::norm(), pism::TridiagonalSystem::norm1(), pism::array::Staggered::operator()(), pism::fem::P1Element2::P1Element2(), pism::stressbalance::Blatter::partially_submerged_face(), pism::stressbalance::SSAFD::picard_manager(), pism::stressbalance::SSAFD::picard_strategy_regularization(), pism::fem::Quadrature::point(), pism::atmosphere::Delta_P::precip_time_series_impl(), pism::atmosphere::YearlyCycle::precip_time_series_impl(), pism::atmosphere::Anomaly::precip_time_series_impl(), pism::atmosphere::Frac_P::precip_time_series_impl(), pism::atmosphere::OrographicPrecipitation::precip_time_series_impl(), pism::atmosphere::PrecipitationScaling::precip_time_series_impl(), pism::atmosphere::SeaRISEGreenland::precip_time_series_impl(), pism::atmosphere::Uniform::precip_time_series_impl(), pism::EnthalpyConverter::pressure(), pism::RuntimeError::print(), print_alpha_k(), pism::io::NC_Serial::put_vara_double_impl(), pism::fem::Q13DQuadrature64::Q13DQuadrature64(), pism::fem::Q13DQuadrature8::Q13DQuadrature8(), pism::fem::Q1QuadratureN::Q1QuadratureN(), pism::stressbalance::SSAFEM::quad_point_values(), pism::io::read_spatial_variable(), pism::io::read_time_info(), pism::io::regrid(), pism::details::regrid_layer_thickness(), pism::ocean::relabel(), pism::details::renormalize(), pism::stressbalance::Blatter::report_mesh_info(), pism::Grid::report_parameters(), pism::fem::Element2::reset(), pism::fem::Q1Element3::reset(), pism::stressbalance::Blatter::residual_dirichlet(), pism::stressbalance::Blatter::residual_source_term(), pism::fem::row(), pism::IceModel::save_variables(), pism::TridiagonalSystem::save_vector(), pism::array::Array3D::set_column(), pism::stressbalance::Blatter::set_initial_guess(), pism::Grid::Impl::set_ownership_ranges(), pism::stressbalance::SSAFD::solve(), pism::energy::BedrockColumn::solve(), pism::energy::enthSystemCtx::solve(), pism::AgeColumnSystem::solve(), pism::TridiagonalSystem::solve(), pism::energy::tempSystemCtx::solveThisColumn(), pism::array::sum_columns(), pism::atmosphere::YearlyCycle::temp_time_series_impl(), pism::atmosphere::Anomaly::temp_time_series_impl(), pism::atmosphere::Delta_T::temp_time_series_impl(), pism::atmosphere::Uniform::temp_time_series_impl(), pism::energy::total_ice_enthalpy(), pism::stressbalance::BlatterMod::transfer(), unpack_json_array(), pism::calving::vonMisesCalving::update(), pism::stressbalance::WeertmanSliding::update(), pism::MPDATA2::update(), pism::AgeModel::update(), pism::Isochrones::update(), pism::energy::BTU_Full::update_impl(), pism::surface::DEBMSimple::update_impl(), pism::surface::TemperatureIndex::update_impl(), pism::energy::CHSystem::update_impl(), pism::energy::EnthalpyModel::update_impl(), pism::energy::TemperatureModel::update_impl(), pism::energy::EnthalpyModel_Regional::update_impl(), pism::hydrology::Distributed::update_P(), pism::IceModel::view_field(), pism::energy::tempSystemCtx::w(), pism::hydrology::Routing::W_change_due_to_flow(), pism::hydrology::wall_melt(), pism::fem::Quadrature::weight(), weights_piecewise_constant(), weights_piecewise_linear(), pism::io::write_spatial_variable(), and pism::stressbalance::zero_above_ice().