PISM, A Parallel Ice Sheet Model: pism::io::get_att_string
append_time
append_time
Backend
check
check
check
check
check
check
check_and_abort
check_grid_overlap
check_input_grid
compute_start_and_count
convert_data
define_dimension
define_dimensions
define_spatial_variable
define_time
define_time
define_time_bounds
define_timeseries
Dim_Length
dimension_types
file_exists
Fill_Mode
get_att_string
get_att_string
get_att_text
get_att_text
Mode
move_if_exists
read_attributes
read_distributed_array
read_for_interpolation
read_spatial_variable
read_time_bounds
read_time_info
read_timeseries
read_valid_range
regrid
regrid_spatial_variable
remove_if_exists
time_dimension
Type
use_transposed_io
write_attributes
write_dimension_data
write_dimensions
write_spatial_variable
write_time_bounds
write_timeseries
get_att_string() [1/2]
static void pism::io::get_att_string (int ncid, int varid, const std::string & att_name, std::string & result) static
Definition at line 307 of file NC4File.cc.
References check(), pism::join(), pism::k, and PISM_ERROR_LOCATION.
Referenced by pism::io::NC4File::get_att_text_impl(), and pism::io::NC_Serial::get_att_text_impl().