PISM, A Parallel Ice Sheet Model: pism::ocean::compute_average_water_column_pressure
compute_average_water_column_pressure
eikonal_equation
extend_basal_melt_rates
melting_point_temperature
relabel
RelabelingType
shelf_base_melt_rate
compute_average_water_column_pressure()
void pism::ocean::compute_average_water_column_pressure (const Geometry & geometry, double ice_density, double water_density, double g, array::Scalar & result)
Definition at line 217 of file OceanModel.cc.
References pism::average_water_column_pressure(), pism::Geometry::bed_elevation, pism::ParallelSection::check(), pism::ParallelSection::failed(), pism::g, pism::array::Array::grid(), pism::Component::grid(), pism::Geometry::ice_thickness, and pism::Geometry::sea_level_elevation.
Referenced by pism::ocean::Constant::init_impl(), pism::ocean::PIK::init_impl(), pism::ocean::Given::init_impl(), pism::ocean::GivenTH::init_impl(), pism::ocean::Pico::init_impl(), pism::ocean::OceanModel::init_impl(), pism::ocean::PIK::update_impl(), pism::ocean::Constant::update_impl(), pism::ocean::Given::update_impl(), pism::ocean::GivenTH::update_impl(), and pism::ocean::Pico::update_impl().