PISM, A Parallel Ice Sheet Model: pism::array::max
absmax
absmax
apply_mask
cast
compute_magnitude
compute_range
diff_x
diff_x_p
diff_y
diff_y_p
extract_surface
extract_surface
global_to_local
int_to_normtype
interpolate
Kind
max
min
set_default_value_or_stop
staggered_to_regular
staggered_to_regular
sum
sum_columns
max()
double pism::array::max (const array::Scalar & input)
Finds maximum over all the values in an array::Scalar object. Ignores ghosts.
Definition at line 165 of file Scalar.cc.
References pism::GlobalMax(), and pism::array::Array::grid().
Referenced by absmax(), pism::surface::DEBMSimplePointwise::albedo(), pism::average_water_column_pressure(), pism::fct::beta_up(), pism::IceModel::bootstrap_2d(), pism::LocalInterpCtx::buffer_size(), pism::surface::CalovGreveIntegrand(), pism::surface::details::CalovGreveIntegrand(), pism::array::Array::check_array_indices(), pism::inverse::IP_SSATaucTikhonovGNSolver::check_convergence(), pism::VariableMetadata::check_range(), pism::clip(), pism::diagnostics::scalar::MaxHorizontalVelocity::compute(), pism::ocean::PicoGeometry::compute_box_mask(), pism::stressbalance::BedSmoother::compute_coefficients_on_proc0(), pism::hydrology::Routing::compute_conductivity(), pism::stressbalance::SIAFD::compute_diffusivity(), pism::diagnostics::IceEnthalpySurface::compute_impl(), pism::diagnostics::TemperateIceThicknessBasal::compute_impl(), pism::stressbalance::PSB_vonmises_stress::compute_impl(), pism::GeometryEvolution::compute_interface_fluxes(), pism::UNO::compute_interface_fluxes(), pism::compute_interface_velocity(), pism::bed::compute_load(), pism::stressbalance::BlatterMod::compute_max_diffusivity(), pism::Grid::compute_point_neighbors(), compute_range(), pism::frontalmelt::FrontalMelt::compute_retreat_rate(), pism::compute_strain_heating_errors(), pism::IceCompModel::compute_strain_heating_errors(), pism::IceCompModel::computeBasalMeltRateErrors(), pism::IceCompModel::computeBasalTemperatureErrors(), pism::IceCompModel::computeGeometryErrors(), pism::IceCompModel::computeIceBedrockTemperatureErrors(), pism::computeSurfaceVelocityErrors(), pism::IceCompModel::computeSurfaceVelocityErrors(), pism::IceCompModel::computeTemperatureErrors(), pism::inverse::IPTaoTikhonovProblem< ForwardProblem >::convergenceTest(), pism::array::Array3D::copy_from(), pism::array::Array::copy_to_vec(), pism::energy::cryo_hydrologic_warming_flux(), pism::TridiagonalSystem::ddratio(), pism::io::define_dimensions(), pism::array::Array::dm(), pism::surface::SurfaceModel::dummy_accumulation(), pism::surface::SurfaceModel::dummy_runoff(), pism::Grid::dz_max(), pism::hydrology::diagnostics::effective_water_velocity(), pism::EnthalpyConverter::enthalpy_permissive(), pism::atmosphere::era_interim_lon(), pism::stressbalance::SSA::extrapolate_velocity(), pism::array::Forcing::Forcing(), pism::generate_trough_topography(), pism::surface::PDDMassBalance::get_timeseries_length(), pism::surface::PDDrandMassBalance::get_timeseries_length(), pism::IceCompModel::getCompSourcesTestFG(), pism::hydrology::diagnostics::hydraulic_potential(), pism::ice_bottom_surface(), pism::increment_date(), pism::ocean::PicoGeometry::init(), pism::calving::EigenCalving::init(), pism::calving::HayhurstCalving::init(), pism::calving::vonMisesCalving::init(), pism::stressbalance::Blatter::init_2d_parameters(), pism::ocean::Pico::init_impl(), pism::ColumnInterpolation::init_interpolation(), pism::IceCompModel::initTestFG(), pism::energy::TemperatureModel_Verification::initTestFG(), pism::hydrology::K(), pism::LocalInterpCtx::LocalInterpCtx(), pism::make_nonnegative_preserving(), pism::FrontRetreat::max_timestep(), pism::IceModel::max_timestep(), pism::max_timestep_cfl_2d(), pism::max_timestep_cfl_3d(), pism::fct::maximum(), pism::surface::DEBMSimplePointwise::melt(), pism::TridiagonalSystem::norm1(), pism::rheology::grain_size_vostok::operator()(), pism::hydrology::Distributed::P_from_W_steady(), pism::stressbalance::Blatter::parameter_continuation(), pism::parse_date(), pism::part_grid_threshold_thickness(), pism::details::pp(), pism::fct::pp(), pism::print_config(), pism::IceModel::print_summary_line(), pism::array::Array::range(), pism::io::read_spatial_variable(), pism::IceModel::regrid(), pism::array::Array::regrid_impl(), pism::ocean::relabel(), pism::stressbalance::SSATestCase::report(), pism::stressbalance::Blatter::report_mesh_info(), pism::VariableMetadata::report_range(), pism::report_range(), pism::VariableMetadata::report_to_stdout(), pism::stressbalance::Blatter::residual_lateral(), pism::ocean::Pico::set_ocean_input_fields(), pism::setInitStateF(), pism::stressbalance::BedSmoother::smoothed_thk(), pism::IceModel::step(), pism::surface::PDDMassBalance::step(), pism::surface::DEBMSimplePointwise::step(), pism::stressbalance::BedSmoother::theta(), pism::surface::DEBMSimple::timeseries_length(), pism::calving::HayhurstCalving::update(), pism::calving::vonMisesCalving::update(), pism::ocean::PicoGeometry::update(), pism::FractureDensity::update(), pism::Isochrones::update(), pism::atmosphere::OrographicPrecipitationSerial::update(), pism::surface::Verification::update_FG(), pism::frontalmelt::DischargeRouting::update_impl(), pism::ocean::Pico::update_impl(), pism::surface::DEBMSimple::update_impl(), pism::icebin::NullTransportHydrology::update_impl(), pism::energy::CHSystem::update_impl(), pism::energy::EnthalpyModel::update_impl(), pism::GeometryEvolution::update_in_place(), pism::hydrology::Distributed::update_P(), pism::vector_max(), and pism::io::write_spatial_variable().