PISM, A Parallel Ice Sheet Model: pism::hydrology::diagnostics::compute_sinks
compute_sinks
effective_water_velocity
hydraulic_potential
compute_sinks()
static void pism::hydrology::diagnostics::compute_sinks (const IceModelVec2Int & domain_mask, const IceModelVec2S & psi, IceModelVec2S & result) static
Compute the map of sinks.
This field is purely diagnostic: it can be used to diagnose failures of the code filling dips to eliminate sinks (and get a better estimate of the steady state flow direction).
Definition at line 37 of file EmptyingProblem.cc.
References pism::IceModelVec::grid(), pism::PointsWithGhosts::next(), and pism::IceModelVec2S::star().
Referenced by pism::hydrology::EmptyingProblem::update().