PISM, A Parallel Ice Sheet Model: pism::mask::grounded
floating_ice
grounded
grounded_ice
ice_free
ice_free_land
ice_free_ocean
icy
ocean
grounded()
bool pism::mask::grounded (int M) inline
Grounded cell (grounded ice or ice-free).
Definition at line 43 of file Mask.hh.
References ocean().
Referenced by pism::stressbalance::SSAFD::assemble_rhs(), pism::frontalmelt::FrontalMelt::compute_retreat_rate(), pism::stressbalance::SSAFEM::driving_stress(), pism::IceModelVec2CellType::grounded(), grounded_ice(), pism::stressbalance::Blatter::grounding_line(), pism::grounding_line_flux(), ice_free_land(), pism::stressbalance::Blatter::jacobian_basal(), pism::stressbalance::Blatter::residual_basal(), pism::total_grounding_line_flux(), pism::calving::IcebergRemoverFEM::update_impl(), and pism::stressbalance::weight().