PISM, A Parallel Ice Sheet Model: pism::inverse::gradientFD
DesignVec
gradientFD
gradientFD
StateVec
gradientFD() [1/2]
void pism::inverse::gradientFD (IPFunctional< array::Scalar > & f, array::Scalar & x, array::Scalar & gradient)
Computes finite difference approximations of a IPFunctional<array::Scalar> gradient.
Useful for debugging a hand coded gradient.
Definition at line 28 of file IPFunctional.cc.
References pism::ParallelSection::check(), pism::Grid::com, pism::ParallelSection::failed(), pism::array::Array::grid(), pism::PointsWithGhosts::next(), pism::Grid::points(), pism::array::Array::update_ghosts(), and pism::inverse::IPFunctional< IMVecType >::valueAt().