PISM, A Parallel Ice Sheet Model: pism::io::regrid_spatial_variable
append_time
append_time
check
check
check
check
check
check
check_and_abort
check_grid_overlap
check_input_grid
compute_range
compute_start_and_count
convert_data
define_dimension
define_dimensions
define_spatial_variable
define_time
define_time
define_time_bounds
define_timeseries
file_exists
get_att_string
get_att_string
get_att_text
get_att_text
move_if_exists
read_attributes
read_distributed_array
read_spatial_variable
read_time_bounds
read_time_info
read_timeseries
read_valid_range
regrid
regrid_spatial_variable
regrid_spatial_variable
regrid_vec
regrid_vec_fill_missing
regrid_vec_generic
remove_if_exists
time_dimension
use_transposed_io
write_attributes
write_dimension_data
write_dimensions
write_spatial_variable
write_time_bounds
write_timeseries
regrid_spatial_variable() [1/2]
void pism::io::regrid_spatial_variable (SpatialVariableMetadata & var, const IceGrid & grid, const File & file, RegriddingFlag flag, bool report_range, bool allow_extrapolation, double default_value, InterpolationType interpolation_type, double * output)
Regrid from a NetCDF file into a distributed array output.
if flag is CRITICAL or CRITICAL_FILL_MISSING, stops if the variable was not found in the input file
if flag is one of CRITICAL_FILL_MISSING and OPTIONAL_FILL_MISSING, replace _FillValue with default_value.
sets v to default_value if flag is OPTIONAL and the variable was not found in the input file
uses the last record in the file
Definition at line 783 of file io_helpers.cc.
References pism::VariableMetadata::get_name(), pism::VariableMetadata::get_string(), pism::File::nrecords(), pism::report_range(), and pism::VariableMetadata::unit_system().
Referenced by pism::IceModelVec2T::init_periodic_data(), pism::IceModelVec::regrid_impl(), and pism::IceModelVec2T::update().