PISM, A Parallel Ice Sheet Model: pism::mask::icy
floating_ice
grounded
grounded_ice
ice_free
ice_free_land
ice_free_ocean
icy
ocean
icy()
bool pism::mask::icy (int M) inline
Ice-filled cell (grounded or floating).
Definition at line 47 of file Mask.hh.
References pism::MASK_FLOATING, and pism::MASK_GROUNDED.
Referenced by pism::stressbalance::SSAFD::assemble_matrix(), pism::GeometryEvolution::compute_interface_fluxes(), pism::compute_node_types(), floating_ice(), grounded_ice(), ice_free(), pism::IceModelVec2CellType::icy(), pism::stressbalance::SSAFD::is_marginal(), pism::part_grid_threshold_thickness(), pism::staggered_to_regular(), pism::calving::HayhurstCalving::update(), pism::frontalmelt::DischargeGiven::update_impl(), pism::frontalmelt::DischargeRouting::update_impl(), pism::calving::IcebergRemoverFEM::update_impl(), and pism::stressbalance::weight().