PISM, A Parallel Ice Sheet Model: pism::units::convert
are_convertible
convert
convert()
double pism::units::convert (System::Ptr system, double input, const std::string & spec1, const std::string & spec2)
Convert a quantity from unit1 to unit2.
Example: convert(1, "m year-1", "m second-1").
Please avoid using in computationally-intensive code.
Definition at line 72 of file Units.cc.
Referenced by pism::IceModel::allocate_storage(), pism::stressbalance::BedSmoother::BedSmoother(), pism::stressbalance::BlatterTestvanderVeen::BlatterTestvanderVeen(), pism::stressbalance::BlatterTestXZ::BlatterTestXZ(), pism::surface::TemperatureIndex::compute_next_balance_year_start(), pism::IceModel::compute_original_ice_fraction(), pism::IceModel::compute_temperate_base_fraction(), pism::IceCompModel::computeGeometryErrors(), pism::Time::convert_time_interval(), pism::stressbalance::SSATestCaseExp::exactSolution(), pism::Config::get_number(), pism::surface::PDDMassBalance::get_timeseries_length(), pism::IceCompModel::IceCompModel(), pism::calving::HayhurstCalving::init(), pism::Time::init_calendar(), pism::atmosphere::ElevationChange::init_impl(), pism::surface::EISMINTII::init_impl(), pism::surface::ElevationChange::init_impl(), pism::surface::ForceThickness::init_impl(), pism::stressbalance::SSATestCaseJ::initializeSSACoefficients(), main(), pism::ocean::PIK::mass_flux(), pism::FrontRetreat::max_timestep(), pism::parse_date(), pism::IceBasalResistancePlasticLaw::print_info(), pism::IceBasalResistancePseudoPlasticLaw::print_info(), pism::IceBasalResistanceRegularizedLaw::print_info(), pism::IceModel::print_summary_line(), pism::options::Real::Real(), pism::grid_info::report(), pism::stressbalance::SSATestCase::report(), pism::IceCompModel::reportErrors(), pism::reportErrors(), pism::IceModel::run(), pism::stressbalance::SIAFD::SIAFD(), pism::stressbalance::SSATestCase::SSATestCase(), pism::stressbalance::SSATestCaseCFBC::SSATestCaseCFBC(), pism::stressbalance::SSATestCaseConst::SSATestCaseConst(), pism::stressbalance::SSATestCaseExp::SSATestCaseExp(), pism::IceCompModel::test_V_init(), pism::Diagnostic::to_external(), pism::Diagnostic::to_internal(), pism::calving::HayhurstCalving::update(), pism::energy::TemperatureModel::update_impl(), pism::hydrology::Distributed::update_impl(), pism::hydrology::Routing::update_impl(), pism::surface::Verification::update_L(), and pism::IceModel::update_run_stats().