PISM, A Parallel Ice Sheet Model: pism::atmosphere::huybrechts_dewolde
era_interim
era_interim_lon
era_interim_sin
huybrechts_dewolde
huybrechts_dewolde_mean_annual
huybrechts_dewolde_mean_summer
martin2011
martin2011_mean_annual
martin_huybrechts_dewolde
huybrechts_dewolde()
static void pism::atmosphere::huybrechts_dewolde (const Geometry & geometry, IceModelVec2S & T_ma, IceModelVec2S & T_ms) static
Parameterization of mean annual and mean summer near-surface temperature as in Huybrechts & DeWolde (1999)
Definition at line 131 of file PIK.cc.
References pism::IceModelVec::grid(), huybrechts_dewolde_mean_annual(), huybrechts_dewolde_mean_summer(), pism::Geometry::ice_surface_elevation, pism::Geometry::latitude, and pism::PointsWithGhosts::next().
Referenced by pism::atmosphere::PIK::update_impl().