PISM, A Parallel Ice Sheet Model: pism::bed::compute_load
compute_load
compute_load
ge_integrand
vd_integrand
viscDisc
compute_load() [2/2]
double pism::bed::compute_load (double bed, double ice_thickness, double sea_level, double ice_density, double ocean_density)
Definition at line 184 of file BedDef.cc.
References pism::max().
Referenced by pism::bed::PointwiseIsostasy::bootstrap_impl(), pism::bed::LingleClark::bootstrap_impl(), compute_load(), pism::bed::PointwiseIsostasy::init_impl(), pism::bed::LingleClark::init_impl(), pism::bed::LingleClark::step(), and pism::bed::PointwiseIsostasy::update_impl().