PISM, A Parallel Ice Sheet Model: pism::uno::difference_quotient
central
difference_quotient
downstream
psi_fromm
psi_lax_wendroff
psi_uno2
psi_uno3
psi_upwind1
sign
upstream
difference_quotient()
static double pism::uno::difference_quotient (const double * x, const double * f, size_t A, size_t B) inline static
Definition at line 39 of file UNO.cc.
Referenced by psi_fromm(), psi_lax_wendroff(), psi_uno2(), and psi_uno3().