PISM, A Parallel Ice Sheet Model: pism::array::min
absmax
absmax
apply_mask
cast
compute_magnitude
compute_range
diff_x
diff_x_p
diff_y
diff_y_p
extract_surface
extract_surface
global_to_local
int_to_normtype
interpolate
Kind
max
min
set_default_value_or_stop
staggered_to_regular
staggered_to_regular
sum
sum_columns
min()
double pism::array::min (const array::Scalar & input)
Finds minimum over all the values in an array::Scalar object. Ignores ghosts.
Definition at line 193 of file Scalar.cc.
References pism::GlobalMin(), and pism::array::Array::grid().
Referenced by pism::fct::beta_down(), pism::energy::bootstrap_ice_temperature(), pism::hydrology::Distributed::check_P_bounds(), pism::VariableMetadata::check_range(), pism::clip(), pism::diagnostics::scalar::TimeStepRatio::compute(), pism::ocean::PicoGeometry::compute_box_mask(), pism::diagnostics::TemperateIceThicknessBasal::compute_impl(), pism::diagnostics::IceAreaFraction::compute_impl(), pism::energy::enthSystemCtx::compute_lambda(), pism::energy::tempSystemCtx::compute_lambda(), pism::Grid::compute_point_neighbors(), compute_range(), pism::IceCompModel::computeBasalMeltRateErrors(), pism::io::define_dimensions(), pism::Grid::dz_min(), pism::MohrCoulombPointwise::effective_pressure(), pism::EnthalpyConverter::enthalpy_permissive(), pism::fletcher64(), pism::array::Forcing::Forcing(), pism::energy::ice_temperature_guess(), pism::energy::ice_temperature_guess_smb(), pism::increment_date(), pism::calving::EigenCalving::init(), pism::calving::HayhurstCalving::init(), pism::calving::vonMisesCalving::init(), pism::columnSystemCtx::init_fine_grid(), pism::ocean::Pico::init_impl(), pism::ColumnInterpolation::init_interpolation(), pism::init_step(), pism::surface::EISMINTII::initialize_using_formulas(), pism::fct::limit(), pism::make_nonnegative_preserving(), pism::array::Forcing::max_timestep(), pism::max_timestep_cfl_2d(), pism::max_timestep_cfl_3d(), pism::IceModel::max_timestep_diffusivity(), pism::Isochrones::max_timestep_impl(), pism::OptTillphiYieldStress::max_timestep_impl(), pism::frontalmelt::DischargeGiven::max_timestep_impl(), pism::ocean::Cache::max_timestep_impl(), pism::surface::Cache::max_timestep_impl(), pism::surface::ForceThickness::max_timestep_impl(), pism::surface::ISMIP6::max_timestep_impl(), pism::hydrology::SteadyState::max_timestep_impl(), pism::fct::minimum(), pism::details::np(), pism::fct::np(), pism::rheology::grain_size_vostok::operator()(), pism::stressbalance::Blatter::parameter_continuation(), pism::parse_date(), pism::uno::psi_uno2(), pism::uno::psi_uno3(), pism::array::Array::range(), pism::array::Array::regrid_impl(), pism::stressbalance::Blatter::report_mesh_info(), pism::Grid::report_parameters(), pism::VariableMetadata::report_range(), pism::report_range(), pism::IceModel::skip_counter(), pism::rheology::GPBLD::softness_impl(), pism::surface::PDDMassBalance::step(), pism::surface::DEBMSimplePointwise::step(), pism::subset_extent(), pism::subset_start_and_count(), pism::stressbalance::BlatterMod::transfer(), pism::calving::HayhurstCalving::update(), pism::FractureDensity::update(), pism::array::Forcing::update(), pism::icebin::NullTransportHydrology::update_impl(), pism::energy::EnthalpyModel::update_impl(), pism::hydrology::Distributed::update_impl(), pism::hydrology::Routing::update_impl(), and pism::vector_min().