PISM, A Parallel Ice Sheet Model: pism::fem::tensor_product_quadrature
column
cross
det
dot
element_type
ElementType
invert
MAX_QUADRATURE_SIZE
multiply
row
set_to_identity
tensor_product_quadrature
tensor_product_quadrature()
static void pism::fem::tensor_product_quadrature (unsigned int n, const double * points1, const double * weights1, std::vector< QuadPoint > & points, std::vector< double > & weights) static
Build quadrature points and weights for a tensor product quadrature based on a 1D quadrature rule. Uses the same 1D quadrature in both directions.
Parameters
[in] n 1D quadrature size (the resulting quadrature has size n*n)
[in] points1 1D quadrature points
[in] weights1 1D quadrature weights
[out] points resulting 2D quadrature points
[out] weights resulting 2D quadrature weights
Definition at line 42 of file Quadrature.cc.
References n.
Referenced by pism::fem::Q1Quadrature16::Q1Quadrature16(), pism::fem::Q1Quadrature4::Q1Quadrature4(), pism::fem::Q1Quadrature9::Q1Quadrature9(), and pism::fem::Q1QuadratureN::Q1QuadratureN().