PISM, A Parallel Ice Sheet Model: pism::surface::details::insolation
CalovGreveIntegrand
distance_factor_paleo
distance_factor_present_day
hour_angle
insolation
solar_declination_paleo
solar_declination_present_day
solar_longitude
insolation()
static double pism::surface::details::insolation (double solar_constant, double distance_factor, double hour_angle, double latitude, double declination) static
Average top of atmosphere insolation (rate) during the daily melt period, in W/m^2.
This should be equation 5 in Zeitz et al or equation 12 in Krebs-Kanzow et al, but both of these miss a factor of Delta_t (day length in seconds) in the numerator.
To confirm this, see the derivation of equation 2.2.21 in Liou and note that
omega = 2 * pi (radian/day)
or
omega = (2 * pi / 86400) (radian/second).
The correct equation should say
S_Phi = A * B^2 * (h_phi * sin(phi) * sin(delta) + cos(phi) * cos(delta) * sin(h_phi)),
where
A = (S0 * Delta_t) / (Delta_t_Phi * pi), B = d_bar / d.
Note that we do not know Delta_t_phi but we can use equation 2 in Zeitz et al (or equation 11 in Krebs-Kanzow et al) to get
Delta_t_phi = h_phi * Delta_t / pi.
This gives
S_Phi = C * B^2 * (h_phi * sin(phi) * sin(delta) + cos(phi) * cos(delta) * sin(h_phi))
with
C = (S0 * Delta_t * pi) / (h_phi * Delta_t * pi)
or
C = S0 / h_phi.
Parameters
[in] solar constant solar constant, W/m^2
[in] distance_factor square of the ratio of the mean sun-earth distance to the current sun-earth distance (no units)
[in] hour_angle hour angle (radians) when the sun reaches the critical angle Phi
[in] latitude latitude (radians)
[in] declination declination (radians)
Definition at line 266 of file DEBMSimplePointwise.cc.
References hour_angle().
Referenced by pism::surface::DEBMSimplePointwise::insolation(), and pism::surface::DEBMSimplePointwise::melt().