PISM, A Parallel Ice Sheet Model: pism::bed::viscDisc
compute_load
compute_load
ge_integrand
vd_integrand
viscDisc
viscDisc()
double pism::bed::viscDisc (double t, double H0, double R0, double r, double rho, double rho_ice, double grav, double D, double eta)
Actually compute the response of the viscous half-space model in LingleClark, to a disc load.
Compute the response of the viscous half-space model in [LingleClark] to a disc load.
Parameters
[in] t time in seconds
[in] H0 thickness of the disc load, meters
[in] R0 radius of the disc load, meters
[in] r radius, meters
[in] rho mantle density, kg/m3
[in] rho_ice ice (load) density, kg/m3
[in] grav acceleration due to gravity, m/s2
[in] D lithosphere flexural rigidity, N meter
[in] eta mantle viscosity, Pascal second
Definition at line 135 of file greens.cc.
References pism::F(), grav, H0, rho, rho_ice, pism::array::sum(), and vd_integrand().
Referenced by pism::bed::LingleClarkSerial::tweak().