PISM, A Parallel Ice Sheet Model: pism::hydrology::wall_melt
check_bounds
K
wall_melt
wall_melt()
void pism::hydrology::wall_melt (const Routing & model, const IceModelVec2S & bed_elevation, IceModelVec2S & result)
Compute the wall melt rate which comes from (turbulent) dissipation of flow energy.
This code fills result with
\[ \frac{m_{wall}}{\rho_w} = - \frac{1}{L \rho_w} \mathbf{q} \cdot \nabla \psi = \left(\frac{k}{L \rho_w}\right) W^\alpha |\nabla R|^\beta \]
where \(R = P+\rho_w g b\).
Note that conductivity_staggered() computes the related quantity \(K = k W^{\alpha-1} |\nabla R|^{\beta-2}\) on the staggered grid, but contriving to reuse that code would be inefficient because of the staggered-versus-regular change.
At the current state of the code, this is a diagnostic calculation only.
Definition at line 544 of file Routing.cc.
References pism::IceModelVec2S::add(), pism::IceModelVec2S::copy_from(), pism::RuntimeError::formatted(), pism::g, pism::IceModelVec::grid(), pism::k, L, pism::PointsWithGhosts::next(), PISM_ERROR_LOCATION, pism::rhow, pism::hydrology::Routing::subglacial_water_pressure(), pism::hydrology::Hydrology::subglacial_water_thickness(), and pism::WITH_GHOSTS.
Referenced by pism::hydrology::diagnostics::WallMelt::compute_impl().