PISM, A Parallel Ice Sheet Model: pism::hydrology::K
check_bounds
K
wall_melt
K()
static double pism::hydrology::K (double psi_x, double psi_y, double speed, double epsilon) static
Definition at line 396 of file EmptyingProblem.cc.
References pism::max().
Referenced by pism::fem::Element::add_contribution(), pism::inverse::IP_H1NormFunctional2S::assemble_form(), pism::inverse::IPGroundedIceH1NormFunctional2S::assemble_form(), pism::energy::bootstrap_ice_temperature(), pism::stressbalance::Blatter::compute_jacobian(), pism::stressbalance::SSAFEM::compute_local_jacobian(), pism::hydrology::EmptyingProblem::compute_velocity(), pism::hydrology::Routing::compute_velocity(), pism::IceCompModel::computeIceBedrockTemperatureErrors(), pism::hydrology::NullTransport::diffuse_till_water(), pism::energy::enthSystemCtx::enthSystemCtx(), pism::energy::ice_temperature_guess_smb(), pism::surface::Elevation::init_impl(), pism::stressbalance::Blatter::jacobian_basal(), pism::stressbalance::BlatterTestCFBC::jacobian_basal(), pism::stressbalance::BlatterTestHalfar::jacobian_basal(), pism::stressbalance::Blatter::jacobian_f(), pism::hydrology::NullTransport::max_timestep_impl(), pism::energy::enthSystemCtx::set_basal_heat_flux(), pism::energy::enthSystemCtx::set_surface_heat_flux(), pism::hydrology::Distributed::update_P(), pism::hydrology::Routing::update_W(), and pism::hydrology::Routing::W_change_due_to_flow().