PISM, A Parallel Ice Sheet Model: pismv_context
help
main
pismv_context
pismv_grid
pismv_grid_defaults
pismv_context()
std::shared_ptr<Context> pismv_context (MPI_Comm com, const std::string & prefix)
Allocate the PISMV (verification) context. Uses ColdEnthalpyConverter.
Definition at line 41 of file pismv.cc.
References pism::config_from_options(), pism::logger_from_options(), pism::print_config(), and pism::set_config_from_options().
Referenced by main().