PISM, A Parallel Ice Sheet Model: main
help
main
pismv_context
pismv_grid
pismv_grid_defaults
main()
int main (int argc, char * argv[])
Definition at line 161 of file pismv.cc.
References pism::options::Bool(), pism::g, pism::handle_fatal_errors(), help, pism::IceModel::init(), pismv_context(), pismv_grid(), pism::print_unused_parameters(), pism::IceCompModel::reportErrors(), pism::IceModel::run(), pism::IceModel::save_results(), and pism::show_usage_check_req_opts().