PISM, A Parallel Ice Sheet Model: pismv_grid
help
main
pismv_context
pismv_grid
pismv_grid_defaults
pismv_grid()
std::shared_ptr<Grid> pismv_grid (std::shared_ptr< Context > ctx, char testname)
Definition at line 134 of file pismv.cc.
References pism::Grid::FromFile(), PISM_ERROR_LOCATION, pismv_grid_defaults(), and pism::grid::string_to_registration().
Referenced by main().