PISM, A Parallel Ice Sheet Model: main
help
main
main()
int main (int argc, char * argv[])
Definition at line 263 of file siafd_test.cc.
References pism::stressbalance::Inputs::age, pism::io::append_time(), pism::Geometry::bed_elevation, pism::Geometry::cell_type, pism::grid::compute_vertical_levels(), pism::context_from_options(), pism::io::define_time(), pism::Geometry::ensure_consistency(), pism::stressbalance::Inputs::enthalpy, pism::grid::EQUAL, pism::stressbalance::Inputs::geometry, pism::handle_fatal_errors(), help, pism::grid::Parameters::horizontal_size_from_options(), pism::Geometry::ice_surface_elevation, pism::Geometry::ice_thickness, pism::stressbalance::StressBalance::init(), pism::VariableMetadata::long_name(), pism::grid::Parameters::Lx, pism::grid::Parameters::Ly, pism::array::Array::metadata(), pism::grid::Parameters::ownership_ranges_from_options(), pism::io::PISM_NETCDF3, pism::io::PISM_READWRITE_MOVE, pism::reportErrors(), pism::Geometry::sea_level_elevation, pism::array::Array::set(), pism::set_config_from_options(), pism::setInitStateF(), pism::show_usage_check_req_opts(), pism::VariableMetadata::units(), pism::stressbalance::StressBalance::update(), pism::stressbalance::StressBalance::velocity_u(), pism::stressbalance::StressBalance::velocity_v(), pism::stressbalance::StressBalance::velocity_w(), pism::stressbalance::StressBalance::volumetric_strain_heating(), pism::stressbalance::Inputs::water_column_pressure, pism::array::WITH_GHOSTS, pism::array::WITHOUT_GHOSTS, pism::array::Array::write(), and pism::grid::Parameters::z.