PISM, A Parallel Ice Sheet Model: rule_s::destroy
destroy
dim
evalError
num_points
destroy
void(* rule_s::destroy) (struct rule_s *r)
Definition at line 140 of file cubature.c.
Referenced by destroy_rule(), make_rule15gauss(), and make_rule75genzmalik().