PISM, A Parallel Ice Sheet Model: cccalendar::c_date2jday
c_date2jday
c_dpm
c_isleap
c_jday2date
day_px
day_x
early_cal
jday_x
late_cal
mixed
month_px
month_x
name
ndays_leap
ndays_reg
sig
year_px
year_x
c_date2jday
int(* cccalendar::c_date2jday) (int, int, int, int *)
Definition at line 35 of file calcalcs.h.
Referenced by ccs_date2jday(), ccs_dayssince(), and ccs_init_calendar().