PISM, A Parallel Ice Sheet Model: pism::icebin::MassEnthVec2S::set_attrs
begin_access
end_access
enth
mass
MassEnthVec2S
set_attrs
set_attrs()
void pism::icebin::MassEnthVec2S::set_attrs (const std::string & long_name, const std::string & units)
Definition at line 13 of file MassEnergyBudget.cc.
References enth, pism::VariableMetadata::long_name(), mass, pism::array::Array::metadata(), and pism::VariableMetadata::units().
Referenced by pism::icebin::MassEnergyBudget::MassEnergyBudget().