PISM, A Parallel Ice Sheet Model: utInvCalendar2_cal
UT_EINVALID
UT_ENOINIT
utCalendar2_cal
utInvCalendar2_cal
utInvCalendar2_cal()
int utInvCalendar2_cal (int year, int month, int day, int hour, int minute, double second, ut_unit * user_unit, double * value, const char * calendar_name)
Definition at line 210 of file utCalendar2_cal.c.
References ccs_date2jday(), ccs_err_str(), get_day_to_user_converter(), get_origin(), getcal(), pism::h0, have_initted, initialize(), cccalendar::name, unknown_cal_emit_warning(), and UT_EINVALID.
Referenced by pism::units::Unit::time().