PISM, A Parallel Ice Sheet Model: pism::options::Option::is_set
is_set
m_is_set
m_value
operator T
operator->
operator->
operator==
Option
set
value
is_set()
template<typename T > bool pism::options::Option< T >::is_set () const inline
Definition at line 35 of file options.hh.
References pism::options::Option< T >::m_is_set.
Referenced by pism::options::Bool(), pism::calendar_from_options(), pism::options::deprecated(), pism::options::ignored(), pism::Time_Calendar::init(), pism::DefaultConfig::init(), pism::surface::EISMINTII::init_impl(), pism::surface::Elevation::init_impl(), pism::initialize_time(), pism::options::Integer::Integer(), pism::options::IntegerList::IntegerList(), pism::options::Keyword::Keyword(), main(), pism::Time::process_y(), pism::Time_Calendar::process_y(), pism::Time::process_ye(), pism::Time_Calendar::process_ye(), pism::Time::process_ys(), pism::Time_Calendar::process_ys(), pism::options::Real::Real(), pism::options::RealList::RealList(), pism::stressbalance::SSATestCase::report_netcdf(), pism::IceCompModel::reportErrors(), pism::set_config_from_options(), pism::set_flag_from_option(), pism::set_integer_from_option(), pism::set_integer_list_from_option(), pism::set_keyword_from_option(), pism::set_number_from_option(), pism::set_number_list_from_option(), pism::set_string_from_option(), pism::stressbalance::SSAFEM::solve_nocache(), pism::options::StringList::StringList(), and pism::options::StringSet::StringSet().