PISM, A Parallel Ice Sheet Model: pism::IceModelVec3::sum_columns
ConstPtr
extract_surface
extract_surface
get_column
get_column
get_column_vector
IceModelVec3
IceModelVec3
interpolate
legal_level
operator()
operator()
Ptr
set_column
set_column
set_column
sum_columns
To3DScalar
~IceModelVec3
sum_columns()
void pism::IceModelVec3::sum_columns (double A, double B, IceModelVec2S & output) const
Sum a 3-D vector in the Z direction to create a 2-D vector.
Note that this sums up all the values in a column, including ones above the ice. This may or may not be what you need. Also, take a look at IceModel::compute_ice_enthalpy(PetscScalar &result) in iMreport.cc.
As for the difference between IceModelVec2 and IceModelVec2S, the former can store fields with more than 1 "degree of freedom" per grid point (such as 2D fields on the "staggered" grid, with the first degree of freedom corresponding to the i-offset and second to j-offset).
IceModelVec2S is just IceModelVec2 with "dof == 1", and IceModelVec2V is IceModelVec2 with "dof == 2". (Plus some extra methods, of course.)
Either one of IceModelVec2 and IceModelVec2S would work in this case.
Computes output = A*output + B*sum_columns(input) + C
See also
https://github.com/pism/pism/issues/229
Definition at line 268 of file iceModelVec3.cc.
References pism::fem::column(), get_column(), pism::IceModelVec::Impl::grid, pism::k, pism::IceModelVec::m_impl, and pism::PointsWithGhosts::next().
Referenced by pism::icebin::IBIceModel::energy_step().