PISM, A Parallel Ice Sheet Model: pism::IceModelVec2V::copy_from
add
add
ConstPtr
copy_from
IceModelVec2V
interpolate
Ptr
ToVector
~IceModelVec2V
copy_from()
void pism::IceModelVec2V::copy_from (const IceModelVec & source) virtual
Result: v <- source. Leaves metadata alone but copies values in Vec. Uses VecCopy.
Reimplemented from pism::IceModelVec.
Definition at line 71 of file iceModelVec2V.cc.
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design_transpose(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization(), pism::inverse::IP_SSAHardavForwardProblem::apply_linearization_transpose(), pism::inverse::IP_SSATaucForwardProblem::apply_linearization_transpose(), pism::stressbalance::SSAFEM::cache_inputs(), pism::stressbalance::PSB_strain_rates::compute_impl(), pism::stressbalance::PSB_deviatoric_stresses::compute_impl(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluate_objective_and_gradient(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::evaluateConstraints(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::evaluateConstraintsJacobianDesign(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::evaluateConstraintsJacobianState(), pism::GeometryEvolution::flow_step(), pism::stressbalance::SSAFEM::init_impl(), pism::stressbalance::SSAFD::picard_iteration(), pism::stressbalance::SSAFD::picard_manager(), pism::stressbalance::SSAFD::picard_strategy_regularization(), pism::stressbalance::SSA::set_initial_guess(), pism::stressbalance::SSAFD::solve(), pism::stressbalance::SSAFEM::solve_nocache(), pism::FractureDensity::update(), and pism::hydrology::SteadyState::update_impl().