PISM, A Parallel Ice Sheet Model: pism::stressbalance::BlatterTestXY::residual_source_term
BlatterTestXY
dirichlet_node
m_B
marine_boundary
residual_source_term
u_bc
residual_source_term()
void pism::stressbalance::BlatterTestXY::residual_source_term (const fem::Q1Element3 & element, const double * surface, const double * bed, Vector2 * residual) protected virtual
Computes the residual contribution of the "source term".
This term contains the driving stress.
Reimplemented from pism::stressbalance::Blatter.
Definition at line 66 of file BlatterTestXY.cc.
References pism::blatter_xy_source(), pism::fem::Element::chi(), pism::fem::Element3::evaluate(), m_B, pism::stressbalance::Blatter::m_scaling, pism::stressbalance::Blatter::m_work, n, pism::fem::Element::n_chi(), pism::fem::Element::n_pts(), pism::fem::Element::weight(), pism::fem::Q1Element3::x(), and pism::fem::Q1Element3::y().