PISM, A Parallel Ice Sheet Model: pism::Timeseries::report_range
average
m_com
m_time
m_time_bounds
m_unit_system
m_use_bounds
m_values
m_variable
name
operator()
operator[]
read
report_range
Timeseries
Timeseries
variable
report_range()
void pism::Timeseries::report_range (const Logger & log) private
Report the range of a time-series stored in values.
Definition at line 127 of file Timeseries.cc.
References pism::VariableMetadata::get_name(), pism::VariableMetadata::get_string(), m_unit_system, m_values, m_variable, and pism::Logger::message().
Referenced by read().