PISM, A Parallel Ice Sheet Model: pism::surface::Simple::update_impl
accumulation_impl
init_impl
m_mass_flux
m_temperature
mass_flux_impl
melt_impl
runoff_impl
Simple
temperature_impl
update_impl
update_impl()
void pism::surface::Simple::update_impl (const Geometry & geometry, double t, double dt) protected virtual
Reimplemented from pism::surface::SurfaceModel.
Definition at line 45 of file Simple.cc.
References pism::surface::SurfaceModel::dummy_accumulation(), pism::surface::SurfaceModel::dummy_melt(), pism::surface::SurfaceModel::dummy_runoff(), pism::surface::SurfaceModel::m_accumulation, pism::surface::SurfaceModel::m_atmosphere, m_mass_flux, pism::surface::SurfaceModel::m_melt, pism::surface::SurfaceModel::m_runoff, and m_temperature.