PISM, A Parallel Ice Sheet Model: pism::IceModelVec2S::copy_from
absmax
add
add
array
array
box
ConstPtr
copy_from
diff_x
diff_x_p
diff_y
diff_y_p
IceModelVec2S
interpolate
mask_by
max
min
operator()
operator()
Ptr
set_to_magnitude
set_to_magnitude
star
sum
To2DScalar
copy_from()
void pism::IceModelVec2S::copy_from (const IceModelVec & source) virtual
Result: v <- source. Leaves metadata alone but copies values in Vec. Uses VecCopy.
Reimplemented from pism::IceModelVec.
Definition at line 475 of file iceModelVec2.cc.
Referenced by pism::inverse::IP_SSAHardavForwardProblem::apply_jacobian_design(), pism::inverse::IP_SSATaucForwardProblem::apply_jacobian_design(), pism::energy::EnthalpyModel_Regional::bootstrap_impl(), pism::RegionalYieldStress::bootstrap_impl(), pism::bed::BedDef::bootstrap_impl(), pism::bed::PointwiseIsostasy::bootstrap_impl(), pism::bed::LingleClark::bootstrap_impl(), pism::stressbalance::SSAFEM::cache_inputs(), pism::ocean::PicoGeometry::compute_continental_shelf_mask(), pism::inverse::IP_SSATaucTikhonovGNSolver::compute_dlogalpha(), pism::ocean::PicoGeometry::compute_ice_rises(), pism::ocean::PicoGeometry::compute_ice_shelf_mask(), pism::ocean::PicoGeometry::compute_lakes(), pism::ocean::PicoGeometry::compute_ocean_mask(), pism::hydrology::EmptyingProblem::compute_potential(), pism::hydrology::Routing::compute_velocity(), pism::hydrology::NullTransport::diffuse_till_water(), pism::IceModel::enforce_consistency_of_geometry(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluate_objective_and_gradient(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::evaluateConstraintsJacobianDesign(), pism::inverse::IP_SSATaucTikhonovGNSolver::evaluateGNFunctional(), pism::GeometryEvolution::flow_step(), pism::IceModel::front_retreat_step(), pism::IceModel::hydrology_step(), pism::IceRegionalModel::hydrology_step(), pism::inverse::IP_SSAHardavForwardProblem::init(), pism::inverse::IP_SSATaucForwardProblem::init(), pism::hydrology::Distributed::init_impl(), pism::hydrology::Hydrology::init_impl(), pism::hydrology::Routing::init_impl(), pism::energy::BTU_Minimal::init_impl(), pism::bed::BedDef::init_impl(), pism::bed::LingleClark::init_impl(), pism::RegionalYieldStress::init_impl(), pism::FractureDensity::initialize(), pism::energy::EnthalpyModel::initialize_impl(), pism::energy::TemperatureModel::initialize_impl(), pism::energy::EnthalpyModel_Regional::initialize_impl(), pism::IceCompModel::initTestABCDH(), pism::IceCompModel::initTestL(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::IP_SSATaucTaoTikhonovProblemLCL(), pism::inverse::IP_SSATaucTikhonovGNSolver::linesearch(), main(), pism::IceModel::model_state_setup(), pism::IceRegionalModel::model_state_setup(), pism::diagnostics::ThicknessRateOfChange::reset_impl(), pism::GeometryEvolution::residual_redistribution_iteration(), pism::energy::EnthalpyModel_Regional::restart_impl(), pism::RegionalYieldStress::restart_impl(), pism::RegionalGeometryEvolution::set_no_model_mask_impl(), pism::MohrCoulombYieldStress::set_till_friction_angle(), pism::inverse::IP_SSATaucTaoTikhonovProblemLCL::setInitialGuess(), pism::setInitStateF(), pism::Poisson::solve(), pism::inverse::IP_SSATaucTikhonovGNSolver::solve_linearized(), pism::ocean::PicoGeometry::split_ice_shelves(), pism::IceModel::step(), pism::bed::LingleClark::step(), pism::hydrology::EmptyingProblem::update(), pism::calving::vonMisesCalving::update(), pism::calving::EigenCalving::update(), pism::FractureDensity::update(), pism::calving::CalvingAtThickness::update(), pism::energy::BTU_Full::update_flux_through_top_surface(), pism::FrontRetreat::update_geometry(), pism::atmosphere::ElevationChange::update_impl(), pism::ocean::sea_level::Delta_SL::update_impl(), pism::ocean::sea_level::InitializationHelper::update_impl(), pism::surface::InitializationHelper::update_impl(), pism::bed::PointwiseIsostasy::update_impl(), pism::bed::Given::update_impl(), pism::RegionalYieldStress::update_impl(), pism::hydrology::Distributed::update_impl(), pism::hydrology::Routing::update_impl(), pism::GeometryEvolution::update_in_place(), and pism::hydrology::wall_melt().