PISM, A Parallel Ice Sheet Model: pism::ocean::Given::Given
Given
init_impl
m_shelf_base_mass_flux
m_shelf_base_temperature
m_shelfbmassflux
m_shelfbtemp
max_timestep_impl
shelf_base_mass_flux_impl
shelf_base_temperature_impl
update_impl
~Given
Given()
pism::ocean::Given::Given (IceGrid::ConstPtr g)
Definition at line 29 of file GivenClimate.cc.
References pism::ocean::OceanModel::allocate_shelf_base_mass_flux(), pism::ocean::OceanModel::allocate_shelf_base_temperature(), pism::ForcingOptions::filename, pism::IceModelVec2T::ForcingField(), pism::g, pism::LINEAR, pism::Component::m_config, pism::Component::m_grid, m_shelf_base_mass_flux, m_shelf_base_temperature, m_shelfbmassflux, m_shelfbtemp, pism::ForcingOptions::period, pism::PISM_NETCDF3, and pism::PISM_READONLY.