PISM, A Parallel Ice Sheet Model: pism::IceModelVec2::regrid_impl
ConstPtr
get_component
IceModelVec2
operator()
operator()
Ptr
read_impl
regrid_impl
set_component
To2D
view
view
write_impl
regrid_impl()
void pism::IceModelVec2::regrid_impl (const File & file, RegriddingFlag flag, double default_value = 0.0) protected virtual
Gets an IceModelVec from a file file, interpolating onto the current grid.
Stops if the variable was not found and critical == true.
Reimplemented from pism::IceModelVec.
Definition at line 197 of file iceModelVec2.cc.
References pism::IceModelVec::Impl::dof, pism::petsc::VecArray::get(), pism::IceModelVec::Impl::ghosted, pism::IceModelVec::Impl::grid, pism::IceModelVec::Impl::interpolation_type, pism::IceModelVec::m_impl, pism::IceModelVec::Impl::metadata, pism::IceModelVec::regrid_impl(), pism::io::regrid_spatial_variable(), pism::IceModelVec::Impl::report_range, pism::IceModelVec::set_dof(), and pism::IceModelVec::update_ghosts().